### ISSUE TITLE
How to show text with latest version bwip-js on html?

### ISSUE THREAD

**Issue by dtanh72** [metafloor/bwip-js#10]
Dear men,

How are you?

I downloaded the latest version of bwipjs. But i can not show text below the 1D barcodes.

Would you like to show me how to apply the text below the 1D Barcode?

thanks and best regards.

![bwippjs](https://cloud.githubusercontent.com/assets/5634004/9381482/f28d30e2-4761-11e5-8323-2fb76468fe87.png)

**Comment by dtanh72** [comment]
![bwippjs](https://cloud.githubusercontent.com/assets/5634004/9381472/d7509d5a-4761-11e5-9f4c-6bfc5df0d547.png)

**Comment by metafloor** [comment]
Are you trying to access the demo from a file:// URL?  If so, that is not supported.  The emscripten-compiled freetype library uses XHR to request the library's memory image.  See the Usage section of the bwip-js home page for more details.

If you are using an http server, please show the bwip-js files being served in the access log.

**Comment by dtanh72** [comment]
Yes, i downloaded the latest version of bwipjs at URL: http://metafloor.github.io/bwip-js/. I use server local, I used all means to run the demo, but i can not show text below the 1D barcode. I think that I have downloaded the source code is missing the display text below the 1D barcode.

![bwippjs_demo](https://cloud.githubusercontent.com/assets/5634004/9399315/b6adbf62-47dc-11e5-97e5-955f1d4b7d99.png)

**Comment by metafloor** [comment]
Please show the server's access log for the bwip-js files.  I suspect the freetype.js.mem file is not being served correctly.

Do you see any console/error messages in Chrome's debugger panel?

**Comment by dtanh72** [comment]
yes, when i debug console occurs error: uncaught initializer memory could not load freetype.js.mem

![bwippjs_demo](https://cloud.githubusercontent.com/assets/5634004/9399747/a2ee4342-47e2-11e5-9c66-492c37f8eb31.png)

**Comment by dtanh72** [comment]
Please guide me fix this error
Thank you very much.

**Comment by dtanh72** [comment]
Please guide me fix this error
Thank you very much

**Comment by metafloor** [comment]
You are getting a 404 on freetype.js.mem.  This means either the file does not exist (unlikely), or is unreadable (check access permissions on the file), or the server does not understand the .mem file extension.  

I suspect the .mem file extension is not configured in the http server you are using.  You need to set its MIME type to application/octet-stream.  

Check the error log for the server and see if it is complaining about an unknown file type.  And let me know what type of http server (and OS) you are using.  I work with apache and node.js.  I may or may not be able to help you with other http servers...  It's almost 23:00 my time, so I am off to bed soon.

**Comment by dtanh72** [comment]
Thanks again, this is now useful. 
Regards,

**Comment by metafloor** [comment]
Leaving this issue open to remind me to document the odd-ball .mem file extension.
