### ISSUE TITLE
Generating Code128A

### ISSUE THREAD

**Issue by judylin1** [metafloor/bwip-js#102]
I have an existing barcode encoded in Code128A with text "12ABC456". I don't think parse or parsefnc is necessary, but even testing with / without those, the barcode does not match my existing one. Is there a way to force a CODE128A barcode to be generated?

For reference, the barcode I have looks like the attached barcode.
![linear](https://user-images.githubusercontent.com/10840985/36817935-984c98d8-1ca8-11e8-9e3c-1175c275d4b0.png)
The one generated by bwip looks like this:
![download](https://user-images.githubusercontent.com/10840985/36817959-acf04672-1ca8-11e8-820e-d7c25a203cf3.png)

**Comment by metafloor** [comment]
BWIPP only supports two encoding methods for code128 - `raw` and `auto` - and there is no way to force the encoder to use only subset A.  

Is there a reason why only subset A can be used?

If you can guarantee that the text to encode will always be subset A characters, it is not hard to generate the raw encoding.  As a reference, see the [code128 wikipedia page](https://en.wikipedia.org/wiki/Code_128).

**Comment by terryburton** [comment]
The following issue represents the current status of fixed-mode support in the underlying BWIPP library:

https://github.com/bwipp/postscriptbarcode/issues/58#issuecomment-210457247

This linked workaround should be sufficient to generate your required Code 128A:

```
Encoder: code128
Data: ^103^017^018^033^034^035^020^021^022
Options: raw
```

Representing:

```
[Start A] [1] [2] [A] [B] [C] [4] [5] [6]
```

**Comment by judylin1** [comment]
You guys are awesome!! Thanks for the super quick clarification!
