### ISSUE TITLE
Generating ECC-200 datamatrix images

### ISSUE THREAD

**Issue by bmedici** [metafloor/bwip-js#103]
Hi all,

We're trying to integrate bwip-js in a NodeJS api server, in order to generate ECC-200 datamatrix code images.
ECC-200 isn't explictely listed in the supported barcode types : maybe it can be generated as another standard with specific parameters or has another name we don't figure out ?
If not yet supported, maybe it is planned in a near future ?
Any idea of an alternative to generate ECC-200 codes from plain strings ?

Thank you for any information !

**Comment by metafloor** [comment]
I believe ECC-200 is just another name for datamatrix.

**Comment by terryburton** [comment]
> I believe ECC-200 is just another name for datamatrix.

Affirmative. See "Also known as:" https://github.com/bwipp/postscriptbarcode/wiki/Data-Matrix

**Comment by metafloor** [comment]
Closing as resolved.
