### ISSUE TITLE
Return promise with PNG file

### ISSUE THREAD

**Issue by nove1398** [metafloor/bwip-js#105]
Is there a plan to integrate a promise chain with the node.js implementation of this library? Or is there a way to do so with the current version?

**Comment by c-bandy** [comment]
You can wrap the program around a promise.

```js
function bwipAsync(options) {
  return new Promise((resolve, reject) => {
    bwipjs.toBuffer(options, (err, png) => {
      if (err) {
        reject(err);
      } else {
        resolve(png);
      }
    });
  });
}
```

**Comment by metafloor** [comment]
The pending 2.0 release will accept either a callback or return a promise on async node.js calls.  Browser is fully synchronous.
