### ISSUE TITLE
Can't figure out how to actually display the barcode

### ISSUE THREAD

**Issue by drewk2525** [metafloor/bwip-js#106]
I've been tasked with updating our app to use the newer version of this framework (previous version was 0.16), and I'm struggling to figure out how to actually get the barcode to display.

Below is my JavaScript code, which I've created based on the demo.html code.  What am I missing to actually display the barcode in my canvas?

    function render(canvas,xScale,text) {
        var inkspread = 0.15;

        var elt  = {};
        elt.sym = 'code39';

        var altx = '';
        var opts = '';

        var bw = new BWIPJS(bwipjs_fonts, true);

        // Convert the options to a dictionary object, so we can pass alttext with
        // spaces.
        var tmp = opts.split(' ');
        opts = {
            inkspread : inkspread
        };
        for (var i = 0; i < tmp.length; i++) {
            if (!tmp[i])
                continue;		var eq = tmp[i].indexOf('=');
            if (eq == -1)
                opts[tmp[i]] = bw.value(true);
            else
                opts[tmp[i].substr(0, eq)] = bw.value(tmp[i].substr(eq+1));
        }

        // Add the alternate text
        if (altx)
            opts.alttext = bw.value(altx);

        var rot  = 'N';

        // Feature or bug, BWIPP does not extend the background color into the
        // human readable text.  Fix that in the bitmap interface.
        if (opts.backgroundcolor) {
            bw.bitmap(new Bitmap(canvas.id, rot, '#' + opts.backgroundcolor));
            delete opts.backgroundcolor;
        } else {
            bw.bitmap(new Bitmap(canvas.id, rot));
        }

        var scaleX = xScale * 4;
        var scaleY = .7 * 4 ;
        bw.scale(scaleX, scaleY);

        // Add optional padding to the image
        bw.bitmap().pad(+opts.paddingwidth*scaleX || 0,
            +opts.paddingheight*scaleY || 0);

        // var ts0 = Date.now();
        try {
            // Call into the BWIPP cross-compiled code.
            BWIPP()(bw, elt.sym, text, opts);
            bwipjs_fonts.loadfonts(function(e) {
                if (e) {
                    $('#output').text(e.stack || (''+e));
                } else {
                    show(elt, altx, opts, text, scaleX, scaleY, rot);
                }
            });
        } catch (e) {
            // Watch for BWIPP generated raiseerror's.
            var msg = ''+e;
            if (msg.indexOf("bwipp.") >= 0) {
                $('#output').text(msg);
            } else if (e.stack) {
                $('#output').text(e.stack);
            } else {
                $('#output').text(e);
            }
            return;
        }
        // Draw the barcode to the canvas
        function show(elt, altx, opts, text, scaleX, scaleY, rot, mono=false) {
            bw.render();
            canvas.style.visibility = 'visible';
    // Set URL            
            var strOpts = JSON.stringify(opts);
            var url = 'http://bwipjs-api.metafloor.com/?bcid=' + elt.sym +
                '&text=' + encodeURIComponent(text) +
                (altx ? '&alttext=' + encodeURIComponent(altx) : '') +
                (strOpts ? '&' + strOpts.replace(/ +/g, '&') : '') +
                (rot != 'N' ? '&rotate=' + rot : '') +
                (scaleX == scaleY ? '&scale=' + scaleX
                    : '&scaleX=' + scaleX + '&scaleY=' + scaleY) +
                (mono ? '&monochrome' : '');
            document.getElementById('apiurl').href = url;
    // End Set URL
            saveCanvas.basename = elt.sym + '-' +
                text.replace(/[^a-zA-Z0-9._]+/g, '-');
        }
    }
    function saveCanvas(type, ext) {
        var canvas = document.getElementById('barcode-canvas');
        canvas.toBlob(function (blob) {
            saveAs(blob, saveCanvas.basename + ext);
        }, type, 1);
    }

**Comment by metafloor** [comment]
That is a bit too much code to take in at one glance.  I suggest you simplify it down to the bare essentials - just pass in a hard coded options object, without all the extra processing logic. Then I might be able to help.

**Comment by drewk2525** [comment]
@metafloor, if I strip this down to what I would think are the essentials, it looks something like this:
`function render(canvas,xScale,text) {
    var bw = new BWIPJS(bwipjs_fonts, true);

    try {
        BWIPP()(bw, elt.sym, text, opts);
        bwipjs_fonts.loadfonts(function(e) {
            if (e) {
                $('#output').text(e.stack || (''+e));
            } else {
                show(elt, altx, opts, text, scaleX, scaleY, rot);
            }
        });
    } catch (e) {
        // Error handling //
        return;
    }
    // Draw the barcode to the canvas
    function show(elt, altx, opts, text, scaleX, scaleY, rot, mono=false) {
        bw.render();
        canvas.style.visibility = 'visible';
    }
}`

I stripped out a lot of the variable declarations and logic that shouldn't impact the rendering.  From what I gather, it seems to me that bw.render() should be rendering the barcode on the canvas.  I'm just trying to figure out what other piece I need to get it to show up.

**Comment by metafloor** [comment]
This works for me.  Used a simple http server with `/` mapped to `node_modules/bwip-js`

```
<!doctype html>
<html><head><title>Basic Browser Example</title>
<meta charset="utf-8" />
<script type="text/javascript" src="bwipp.js"></script>
<script type="text/javascript" src="bwipjs.js"></script>
<script type="text/javascript" src="lib/xhr-fonts.js"></script>
<script type="text/javascript" src="lib/bitmap.js"></script>
<script type="text/javascript">
function render() {
	var canvas = document.getElementById('canvas');
	var output = document.getElementById('output');
	canvas.width = canvas.height = 1;
	output.textContent = '';

	var bw = new BWIPJS(bwipjs_fonts, false);	// false == aa fonts
	bw.bitmap(new Bitmap(canvas, 'N'));
	bw.scale(3,3);

	try {
		BWIPP()(bw, 'code39', 'ABC012', { includetext:true, textxalign:'center' });

		// Allow the font manager to demand-load any required fonts
		// before calling render().
		bwipjs_fonts.loadfonts(function(e) {
			bw.render();
		});
	} catch (e) {
		output.textContent = (''+e) + (e.stack ? '\n\n' + e.stack : '');
	}
}
</script>
</head>
<body>
<button onclick="render()">Show Barcode</button><br><br>
<canvas id="canvas"></canvas>
<xmp id="output"></xmp>
</body>
</html>
```

The one issue I encountered was clicking the button too quickly.  There is a timing issue with the xhr-font code that you need to let it load the font metrics first, but there is no way to know programmatically when they have loaded.  

Could that be the issue you are seeing?  The try-catch block will spit out `fontset undefined` when that happens.

**Comment by drewk2525** [comment]
@metafloor, Thanks for the reply!  It looks like my issue had something to do with how we're creating the options.  When I cut that variable out and used what you have, I'm now seeing a barcode.  I really appreciate the help!
