### ISSUE TITLE
code93 gets rendered differently (and wrong) on nodejs

### ISSUE THREAD

**Issue by nlang** [metafloor/bwip-js#107]
I noticed that code93 generated with a tool that I built with bwip-js on node is not recognizable by barcodereaders. When generating a code93 with online barcode-generators you can see a notable difference in barcode width (the bwip-js nodejs barcode misses a notable amount of bars).

However, the issue seems not to be in my code and also seems nodejs realted, as the browser version of bwip-js generates a readable and correct code.

You can easily reproduce the issue by generating a code93 code with your browser tool compared to your nodejs based api.

![image](https://user-images.githubusercontent.com/1759992/41790302-6801bbb4-7652-11e8-896c-e210c52bd69a.png)

![image](https://user-images.githubusercontent.com/1759992/41790364-a7aca51c-7652-11e8-8e52-e3def19dce6e.png)

Any ideas why this is happening?
Thanks a bunch!

**Comment by metafloor** [comment]
I am not able to reproduce this issue.  I tried several different text values for the bar code and got identical results from the browser and nodejs.  Here is your example:

![image](https://user-images.githubusercontent.com/385436/41797144-2709a90e-7626-11e8-8d8a-0ba5370395e5.png)

The image is a screen capture, with the nodejs bar code pasted on top.

**Comment by metafloor** [comment]
How are you displaying the node-generated bar codes?  Is there a chance the display is cropping/resizing the image?

**Comment by nlang** [comment]
Thats super weird. I mean, I tried nodejs commandline, nodejs in an application I wrote with different version of bwipjs and your online barcode API. They all give me identical, wrong results. Can you send the link you generated the code with for your online api?

I used http://bwipjs-api.metafloor.com/?bcid=code93&text=HELLO-BWIPJS in the browser (chrome, safari, firefox),  in Postman and stored the image to disk - same results.

![image](https://user-images.githubusercontent.com/1759992/41797598-f59e23f0-766a-11e8-9336-ddc40cda27d6.png)

**Comment by metafloor** [comment]
It's really hard to tell from your example images as they have been resized (evidenced by all the blurry lines).  Can you post the originals without resizing them?

**Comment by nlang** [comment]
Hm, no, the image in the browser hasnt been resized. But anyways, if you take a look at the barcode, it is obvious that there is a part missing. Whey you use the link I provided, do you get a correct result from your online API?

Here, is the image uploaded from my downloads folder, saved by right clicking -> save image in Safari.

![bwipjs-api metafloor com](https://user-images.githubusercontent.com/1759992/41798137-d3262f1e-766c-11e8-8d1b-a70ab841f510.png)

**Comment by metafloor** [comment]
The piece that is missing is the check digit via the `includecheck` option:

![image](https://user-images.githubusercontent.com/385436/41798627-96fbb8f6-762b-11e8-8392-98032e202d3d.png)

I suspect your bar code scanner is requiring a check digit, making the bar code unreadable.  My 1d and 2d scanners read all three bar codes.

**Comment by nlang** [comment]
That did the trick! The barcode is scanned by a cash desk scanner, and I also couldnt read it with the scandit app, that usually reads everything. Thanks so much for your quick help 👍
