### ISSUE TITLE
Online Barcode API Certificate error

### ISSUE THREAD

**Issue by mopx** [metafloor/bwip-js#108]
Hi, I'm getting an invalid certificate error when I try to access https://bwipjs-api.metafloor.com do you plan to keep it running or I should consider making a local installation?

**Comment by metafloor** [comment]
Please see the wiki page on the API (https://github.com/metafloor/bwip-js/wiki/Online-Barcode-API).  Specifically:

27 June 2018: There are some issues with the automated certificate renewal. If you are having trouble connecting to the https: URL, try the alternate names:

- http://api-bwipjs.metafloor.com/
- https://api-bwipjs.metafloor.com/

For some reason, the greenlock certificate manager renewed the one, but not the other.  I am still trying to figure out why.

**Comment by mopx** [comment]
oh, thanks for the update... and hosting this for free :)

**Comment by DoktorJ** [comment]
@metafloor this can probably be closed? :)
