### ISSUE TITLE
0.13 version on github

### ISSUE THREAD

**Issue by tunix** [metafloor/bwip-js#11]
Could you please tag 0.13 on github so that it'll also be downloadable from tools like bower?

**Comment by metafloor** [comment]
Release 0.14 will be made this weekend; will incorporate the BWIPP 2015-08-10 changes.

**Comment by tunix** [comment]
Hi! Thanks for the answer. I've just checked out releases on github but cannot see a tag that belongs to 0.14 release. Is it released?

**Comment by metafloor** [comment]
Finally found the time to update the repo.  BWIPP version is now 2015-08-10 (the latest).  bwip-js version is 0.14.  A new 0.14.0 release has been cut on github.

I do not use bower so please let me know if this version updates correctly with it.

**Comment by tunix** [comment]
@metafloor - it's working perfectly! thank you!
