### ISSUE TITLE
Image DPI Option?

### ISSUE THREAD

**Issue by itsachen** [metafloor/bwip-js#111]
Hi,

I'm wondering if there is an option when using `bwipjs.toBuffer` to generate a PNG to set the DPI of the resulting image. I'm planning on printing the image in a document and I would like to have the ability to set the DPI higher to ensure a higher quality print.

I was poking around the documentation but wasn't able to find anything so far.

**Comment by metafloor** [comment]
While it is possible to store dpi in a png image, the chunk used to do so (pHYs - physical pixel dimensions) is optional and not emitted by the bwip-js png module.  For reference, see: http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.pHYs

More interestingly, what value should be stored?

As currently designed (and based on target usage in HTML/CSS), `scale=1` maps roughly to 96dpi, `scale=2` is ~192dpi, etc.   Are these the dpi values you would want to use?  Or would you want to specify dpi explicitly?

I am not against adding the pHYs chunk (it would only expand image size by 17 bytes) and making it an option-enabled feature.  Just need to understand use-cases better.

**Comment by itsachen** [comment]
Thanks for the context! As I mentioned before, I'm interested in setting the DPI because I plan on printing the generated image in a document. A higher DPI image, printed with a printer that can print at that DPI, would result in a higher quality (and possibly more scannable) barcode. I'm running some tests on my end to verify this.

I've tried using the `scale` option but the DPI seems to consistently be 72. The pixel dimensions of the image change - instead I'd like for the pixel dimensions to remain consistent but the pixel density to increase. I've been experimenting with using ImageMagick (`convert -units PixelsPerInch xxx.png -density yyy.png`) as well.

Also, for my understanding, how is the DPI currently set to 72? Is this a default that doesn't use the pHYs chunk?

**Comment by metafloor** [comment]
> instead I'd like for the pixel dimensions to remain consistent but the pixel density to increase.

I think you are misunderstanding image formats.  Increasing the pixel density of an image always increases its pixel dimensions.  The dpi parameter in an image format has no bearing on how the image data/pixels are stored.  

You are seeing 72dpi probably because you are on MacOS or are using an application where 72dpi is the default.  On Windows and with HTML/CSS, 96dpi is the standard.

**Comment by metafloor** [comment]
One thing to amend.  Postscript and hence the BWIPP uses 72dpi, and bwip-js's graphics interface maps pixels one-to-one.  That may be why you are seeing 72dpi.

**Comment by itsachen** [comment]
Ah I used the wrong term. I'd like for the pixel dimensions to remain consistent but the DPI to change.

**Comment by metafloor** [comment]
This is a quick patch of `node-bitmap.js` that optionally adds the dpi to the png image.  Use it by specifying `dpi` as an option to the `bwipjs.toBuffer()` call.  I recommend you set dpi based on scale, using 72dpi multiples.  That is, if `scale:2`, then `dpi:144`, etc.

[node-bitmap.zip](https://github.com/metafloor/bwip-js/files/2237082/node-bitmap.zip)

I tested the generated images with irfanview and it was showing the correct dpi in each.

**Comment by metafloor** [comment]
The dpi option is now available in version 1.7.1.

**Comment by itsachen** [comment]
This is awesome! Thank you!

**Comment by adomguo** [comment]
@metafloor hello. how to set to dpi?
