### ISSUE TITLE
browser-fonts.js onready callback never fires with require1k.

### ISSUE THREAD

**Issue by aldeka** [metafloor/bwip-js#112]
When loading browser-fonts.js and require1k, the last line in browser-fonts.js:
if (bwipjs_fonts.onready) { bwipjs_fonts.onready.call(null); }
has already executed before browser-bwipjs.js registers its onready callback.

So the fonts never become ready.  I fixed this in my local copy by setting a variable 'ready' when the fonts are ready and, should anyone attempt to hook a new onready callback when 'ready' is true, the callback is called immediately.  

I know require1k is a non-compliant implementation of require, but I thought I'd describe this issue I saw.

**Comment by metafloor** [comment]
Can you test against the attached browser-bwipjs.js?  I have removed the `onready` call and encompassing logic as it is now obsolete.  It tests ok inside a simple-minded react app, but it also tested ok with the original version, which means there is some kind of timing issue involved.

[browser-bwipjs.zip](https://github.com/metafloor/bwip-js/files/2245741/browser-bwipjs.zip)

**Comment by metafloor** [comment]
Fix is available in version 1.7.1.

**Comment by aldeka** [comment]
Yes, that version fixes things for me.  

Thanks for the fast response.  I'm using this in a very simple app that doesn't compile any of the client-side resources.  I appreciate your support for this unusual use.
