### ISSUE TITLE
includetext does not work for React.js 16.4

### ISSUE THREAD

**Issue by nurulmac11** [metafloor/bwip-js#114]
`
    componentDidMount() {
        const {number, type} = this.props;
        const _number = number ? number : '0123456789';
        const _type = type ? type : 'code128';

        bwipjs('canvas', {
                bcid:        _type,       // Barcode type
                text:        _number,    // Text to encode
                scale:       3,               // 3x scaling factor
                height:      10,              // Bar height, in millimeters
                includetext: true,            // Show human-readable text
                textxalign:  'center',        // Always good to set this
            }, (err, cvs) => {
                if (err) {
                    this.setState({
                        errorMessage: err,
                    });
                } else {
                    // Nothing else to do in this example...
                }
            });
    }
`

This is my component code. But text doesn't show up.
![image](https://user-images.githubusercontent.com/2218618/45099739-b51e2b80-b130-11e8-9448-1ed39ad4014b.png)
I do not get any console error or bwipjs error. What can cause this?
Thanks.

**Comment by metafloor** [comment]
Are you seeing the GET requests (XHR) for the fonts?  Are the URLs correct for the location of the fonts on the server?

**Comment by nurulmac11** [comment]
![image](https://user-images.githubusercontent.com/2218618/45100417-14307000-b132-11e8-9cca-5b6171c341ea.png)
Yes, I see this request but I cant open that url in my browser. That does not download any font.

**Comment by metafloor** [comment]
Please see the the project's main README under the Browser section.  You need to copy or symlink the font files directory.  Look for the text:

  > If you want to generate barcodes with text, you must do one extra step after installing bwip-js. The browser-based font manager uses XHR to demand-load fonts as needed. The problem is that the fonts directory where bwip-js gets installed (under node_modules) is usually not accessible. Therefore, you must make the fonts visible to your applcation.
