### ISSUE TITLE
Difference in how text is rendered (differs when giving absolute width/height versus letting bwipjs decide)

### ISSUE THREAD

**Issue by deefeloper** [metafloor/bwip-js#116]
when you let bwipjs decide what size a barcode should be, the text is rendered correctly:

`?bcid=ean13&text=123456789012&includetext&guardwhitespace&scale=2&backgroundcolor=ffffff`
![image](https://user-images.githubusercontent.com/13310332/45550232-91db3680-b82a-11e8-9bec-5b302634a625.png)

when you give a width/height (in mm) the text is never in the right place, even after fiddling with other options like `scale` and `fontsize`

`?bcid=ean13&width=137&height=69&scale=1&text=123456789012&includetext&guardwhitespace&backgroundcolor=ffffff`
![image](https://user-images.githubusercontent.com/13310332/45550275-b1725f00-b82a-11e8-976c-d778fdb161ef.png)

Am I doing something wrong here or is this just a side effect of restricting size?

**Comment by metafloor** [comment]
The issue you are seeing is that bar codes do not scale linearly, at least not at the low resolution of images used on the web.  I recommend removing the width/height parameters and just use scale.

**Comment by deefeloper** [comment]
I made a component that tries to render the barcode + text as large as possible and then center it in it's container. The problem is I do not know what scale I have to use in advance so the only alternative would be to render it multiple times until I hit that ceiling.

Because I cannot use this code in a browser it would mean my server would get flooded really fast using an approach like this.
