### ISSUE TITLE
Fonts missing: Cannot read property 'minsize' of undefined

### ISSUE THREAD

**Issue by c-bandy** [metafloor/bwip-js#118]
Hi! First of all, thank you for this tool. It's incredibly useful.

In my local environment everything works as expected, a pretty barcode is generated. However, when run in an AWS Lambda, I get this error:

```
TypeError: Cannot read property 'minsize' of undefined
    at Object.getglyph (/var/task/barcode/index.js:43672:22)
    at BWIPJS.show (/var/task/barcode/index.js:14642:28)
    at Object.BWIPP.$0.renlinear (/var/task/barcode/index.js:42446:9)
    at Object.BWIPP.$0.ean13 (/var/task/barcode/index.js:15858:7)
    at /var/task/barcode/index.js:42847:14\n
    at Function.module.exports.toBuffer
```

I traced this error down to this line:
https://github.com/metafloor/bwip-js/blob/master/node-fonts.js#L83

My options look like this:

```js
{
  bcid: 'ean13',
  scale: 2,
  height: 18,
  includetext: true,
  text: '2299901000129',
}
```

Any ideas on why this might happen? I really am completely lost here.

**Comment by metafloor** [comment]
I suspect the font file is not being loaded, hence the undefined `fontset` property. I am not very familiar with aws lambda but a quick google of `aws lambda file system` does not look promising. It appears the environment only offers a transactional scratch file system and no persistent data interface.

For one application where I needed barcode images in a similar file-system-less environment (embedded device), I base64 encoding the font files and stored them as JS strings inside a custom module. The problem with this approach is you have to modify the font loading code to work with the custom module. And the file size of all the encoded fonts may be excessive, depending on environment. With the base64 overhead plus some extra JS, the entire font collection creates a module of about 13MB. If you only need one font type i.e. OCR-B and a handful of sizes, it works really well.

**Comment by metafloor** [comment]
At present, the font files are expected to exist at `bwip-js/fonts/`.  But I am thinking the code could be updated to use an environment variable to override, something like BWIPJS_FONTS  That would be a safe, non-breaking change to the nodejs code.  I don't have time today for pushing that out, but it should be available by end of week.

**Comment by c-bandy** [comment]
Great! Sounds like a good solution.

How would one go about adding "custom" fonts after the environment variable has been implemented? I understand the default font is OCR-B, which is the font I desire to use, and that is already included in`/fonts`. Does the file system not understand how to parse it, or what is the problem here?

**Comment by metafloor** [comment]
Can you please test the following code to ensure it works in the aws lambda environment.  In file node-fonts.js, line 105:

        var bytes = fs.readFileSync(__dirname + '/fonts/fnt' + fontid +
                                    (monochr ? 'm-' : 'a-') + size + '.bin');

Replace with:

        var fontdir = process.env.BWIPJS_FONTS || __dirname + '/fonts';
        if (fontdir[fontdir.length-1] == '/') {
            fontdir = fontdir.substr(0, fontdir.length-1);
        }
        var bytes = fs.readFileSync(fontdir + '/fnt' + fontid +
                                    (monochr ? 'm-' : 'a-') + size + '.bin');

You will need to set the environment variable `BWIPJS_FONTS` to the absolute path of the font directory where the `*.bin` files have been copied to.

My testing shows it working on windows and linux in a vanilla node.js environment.

**Comment by c-bandy** [comment]
I've tested it, the same error is still throwing for me still. It errors at line 83, so the part we are messing with does not get reached unfortunately. `fontset` appears to be undefined.

**Comment by metafloor** [comment]
The 2.0 release fixes this issue.  No more bitmapped fonts.  No more async font operations.
