### ISSUE TITLE
Having color barcodes like JABCode and HiQ

### ISSUE THREAD

**Issue by DonaldTsang** [metafloor/bwip-js#119]
## Proposal
Inclusion of JABCode and HiQ color barcode creators, to adapt those repos (C and Java respectively) into Javascript

### For JABCode
* Repo https://github.com/jabcode/jabcode
* Website https://jabcode.org/
* Standard https://www.bsi.bund.de/EN/Publications/TechnicalGuidelines/TR03137/TechnicalGuidelines_03137_node.html
### For HiQ
* Repo https://github.com/ouyangzhibo/HiQ-Robust-and-Fast-Decoding-of-High-Capacity-Color-QR-Codes
* Website http://authpaper.net/

**Comment by terryburton** [comment]
BWIP-JS is a transliteration (from PostScript to JavaScript) of the BWIPP project maintained by myself.

See here for the current status of JAB Code: https://github.com/bwipp/postscriptbarcode/issues/96

Please raise a new issue there requesting implementation of HiQ and specify whether you would be prepared to sponsor development or whether this is just a nice to have.

**Comment by DonaldTsang** [comment]
https://github.com/bwipp/postscriptbarcode/issues/97
