### ISSUE TITLE
Unable to reach https api

### ISSUE THREAD

**Issue by kylelynchkurzawa** [metafloor/bwip-js#121]
Hi,

I'm currently unable to reach the https version of the bwip-js api (https://bwipjs-api.metafloor.com/).
However, I can reach the http version of the api (http://bwipjs-api.metafloor.com/).

I saw on one of the wiki pages in the repo that there we're problems with the automated certificate renewal back in June 2018 (https://github.com/metafloor/bwip-js/wiki/Online-Barcode-API) and I can see in my browser that the https api is not secured currently.

Is it possible to have someone check the certificate to confirm this and update if necessary?

**Comment by thegust** [comment]
I'm having the same issue

**Comment by metafloor** [comment]
Thanks for the notice.  There is something not right about the code/config used to renew certificates.  The new certs had been saved by greenlock to the correct directories, but they did not get loaded by the worker processes.  I restarted the node processes and they loaded the up-to-date certs.
