### ISSUE TITLE
array-marker-not-found when trying to generate gs1datamatrix

### ISSUE THREAD

**Issue by carstenbaumhoegger** [metafloor/bwip-js#123]
hey!

I'm trying to generate `gs1datamatrix` with this lib.

I've added it to my Angular application, generation of `code128`-Barcodes works as expected.
When I try to generate the `gs1datamatrix` the lib fails with the error `array-marker-not-found`.

I've tried to generate this barcode with your online api, but this fails with the exact same error, here's the example link: http://bwipjs-api.metafloor.com/?bcid=gs1datamatrix&text=1234567890

What can I do to get `gs1datamatrix` working?

**Comment by metafloor** [comment]
I gs1 version of datamatrix has application-id requirements that your text string is missing.  I suspect the parsing logic is looking for an ID and not finding it.  For example, if you add (01) to the beginning of the text, it displays correctly: 

http://bwipjs-api.metafloor.com/?bcid=gs1datamatrix&text=(01)1234567890

The BWIPP documentation on gs1-datamatrix can be found here: https://github.com/bwipp/postscriptbarcode/wiki/GS1-DataMatrix.

**Comment by carstenbaumhoegger** [comment]
alright great, thanks for pointing that out!

Unfortunately now I have another error.
As I said, I can generate `code128`-Barcodes.

Now the error is:
```
TypeError: Cannot set property 'width' of null
    at Bitmap.imageinfo (browser-bitmap.js:46)
    at BWIPJS.push../node_modules/bwip-angular2/bwipjs.js.BWIPJS.render (bwipjs.js:592)
    at browser-bwipjs.js:116
    at Object.loadfonts (browser-fonts.js:103)
    at toCanvas (browser-bwipjs.js:112)
    at new QrcodeViewerComponent (qrcode-viewer.component.ts:46)
    at createClass (core.js:22054)
    at createDirectiveInstance (core.js:21931)
    at createViewNodes (core.js:23157)
    at createEmbeddedView (core.js:23065)
```

I'm sending the exact same value to `bwipjs`, that you defined in the api-url:

```js
    bwipjs('mycanvas', {
      bcid: 'gs1datamatrix',       // Barcode type
      text: '(01)1234567890',   	  // Text to encode
    }, function (err, cvs) {
      if (err) {
        // Decide how to handle the error
        // `err` may be a string or Error object
        console.error(err);
      } else {
        // Nothing else to do in this example...
      }
```

I tried setting width, height and scale properties, but nothing fix (or even changed) the thrown error.

**Comment by metafloor** [comment]
Did you look at the referenced line of code in `browser-bitmap.js`?  Here it is:

       cvs  = cvsid instanceof window.HTMLCanvasElement
                        ? cvsid : document.getElementById(cvsid);
       cvs.width  = imgwidth + 2*padx;
       cvs.height = imgheight + 2*pady;

Most likely, you are not passing in a valid `canvas` element or `id`.

**Comment by carstenbaumhoegger** [comment]
okay, thanks for the reference to the code.
But why is the exact same code working with `code128`?
The canvas is defined like this:
```html
<canvas id="mycanvas"></canvas>
```

**Comment by carstenbaumhoegger** [comment]
nevermind, I've implemented `bwip-js` into my node-based backend.
Works like a charm there, so I don't have to generate the barcodes in the frontend.

Thanks for your quick responses!
