### ISSUE TITLE
Terms for API Use

### ISSUE THREAD

**Issue by coreycoogan** [metafloor/bwip-js#126]
Your API works great and is just what I've been looking for. Is the hosted API free to use? Are there any restrictions?

**Comment by metafloor** [comment]
There are no restrictions.  The service is free to use for commercial and personal use.  And the bar code data (text) is not logged/recorded.

The only thing to keep is mind is it is a shared resource running on a limited "micro" AWS node.  And lately, it is maxing out CPU usage.

**Comment by coreycoogan** [comment]
Well that is extremely nice of you. If you had a hosted version running on something more than a micro I’d be willing to pay rather than deal with it myself. Any interest in that?

**Comment by coreycoogan** [comment]
I’m looking at hosting the node library as well, but if you don’t mind answering a quick question. I’d like to get the bytes of the image file so I can embed it in our document as an encoded string. The HTML page gets converted to a PDF and this is the easiest way for us to handle it. Something like this:

<img src="data:image/png;base64, asdfasdfasdf==" class="logo”/>

Do you have any suggestions for how to get the byte string out of the node command line?

**Comment by metafloor** [comment]
The command line interface does not support that but with node, it is not hard to take an image file and convert to base64.  The "one-liner" would look like:

    console.log('data:image/png;base64,' +
                require('fs').readFileSync(process.argv[2]).toString('base64'));

You might want to add some error and args checking....

Put that code in `pngtodataurl.js`  and once you have a png file, invoke as:

    $ node /path/to/pngtodataurl.js /path/to/png/file

Here's my test of it:

    metafloor@ubuntu:~/bwip-js
    $ master/bin/node-bwipjs.cmd --bcid=code128 --text=0123456789 --includetext code128.png
    Barcode has been encoded into code128.png

    metafloor@ubuntu:~/bwip-js
    $ node pngtodataurl.js code128.png
    data:image/png;base64,iVBORw0KGgoAAA ...snip... vc3fhdkAAAAASUVORK5CYII=

**Comment by coreycoogan** [comment]
Thank you very much. That is a huge help.

Best,
Corey
