### ISSUE TITLE
Async Exception Handling

### ISSUE THREAD

**Issue by semireg** [metafloor/bwip-js#127]
Thank you for the fantastic library. I have a small issue in my electron app. I generate barcodes wrapped in Promises. All is well. However, when it throws an error I can catch in the wrapping promise, but I'm also seeing a related error in the console:

```
Uncaught (in promise) Error: bwipp.upcAbadLength: UPC-A must be 11 or 12 digits
    at Object.BWIPP.$0.raiseerror (webpack://renderer/./node_modules/bwip-js/bwipp.js?:512:9)
    at Object.BWIPP.$0.upca (webpack://renderer/./node_modules/bwip-js/bwipp.js?:1343:7)
    at eval (webpack://renderer/./node_modules/bwip-js/bwipp.js?:27987:14)
    at toCanvas (webpack://renderer/./node_modules/bwip-js/browser-bwipjs.js?:93:10)
    at Promise (http://localhost:1212/dist/renderer.dev.js:10165:32)
    at new Promise (<anonymous>)
```

Has anyone seen this before? It seems slightly cosmetic because I am eventually catching in the wrapping promise... so it seems like this is begin generated as the exception escapes the 1st level promise, but before it gets caught by the next promise. I don't know... seems strange.

This doesn't work because of async:
```
      try {
        bwipjs(newCanvas, standardOptions, barcodeCallback);
      } catch (e) {
        reject(e);
      }
```

Again, I'm not sure why it's throwing and also calling the callback.

The callback here properly rejects the promise ... Hmm.

In other libraries, I have sometimes been forced to catch the errors by overriding the event emitter's error event like this:

```
    this.client.on('error', () => {
        // Handle error
    });
```

**Comment by metafloor** [comment]
When you say you are seeing it in the console, do you mean you have enabled the debugger to catch/trap all exceptions?  Or are you seeing `console.log()` output?__

**Comment by semireg** [comment]
That's a good question. I'm not sure what the default is with the Electron debugger. I believe it's the former, because in production I'm seeing non-fatal unhandled rejections (vs. uncaught exception) in Sentry's online error reporting dashboard.

```
UnhandledRejection: "Error: bwipp.ean8badCheckDigit: Incorrect EAN-8 check digit provided\n    at Object.t.raiseerror (file:///Applications/MyApp/Contents/Resources/app.asar/dist/renderer.prod.js:33:314152)\n    at Object.t.ean8 (file:///Applications/...
```

**Comment by semireg** [comment]
For more context, this is the only call to bwipjs in the entire app:

```
import bwipjs from 'bwip-js';
.....
  barcodePromise = (options: {}, uuid: string, canvas: fabric.Canvas): Promise<null> =>
    new Promise((resolve, reject) => {
      const standardOptions = ....

      const newCanvas = document.createElement('canvas');
      bwipjs(newCanvas, standardOptions, err => {
        if (err) {
          ....
          return reject(err);
        } 
       ......
```

**Comment by metafloor** [comment]
The 2.0 release will use a callback or return a Promise on node.js async operations; and is fully synchronous on the browser.
