### ISSUE TITLE
error names not unique.

### ISSUE THREAD

**Issue by shaehn** [metafloor/bwip-js#128]
I am in the process of having a translation mechanism set up for the errors that are reported and have found that the error names are all unique except for the following:

"bwipp.databaromniBadCheckDigit": "Incorrect GS1 DataBar Limited check digit provided",
"bwipp.databaromniBadCheckDigit": "Incorrect GS1 DataBar Omnidirectional check digit provided",

Would it be possible to change one of the mentioned names above to have a different name, or if it makes sense, have the actual messages be identical?

**Comment by metafloor** [comment]
Hi @terryburton,
Is this something you could implement in the upstream code?  Otherwise, I can add a `sed` step in the build process to make the change.

**Comment by terryburton** [comment]
I've just fixed this upstream: https://github.com/bwipp/postscriptbarcode/commit/5a7dc72961e0706ca1b65819df3f3ee5194066ae

I'm not going to cut a release just for this so feel free to patch it manually for the time being.

@shaehn One way to ensure that your contribution would have the most impact - if you are willing - would be if your translations were to exist in a format that could be included in the contrib area of the BWIPP project. Downstream projects could create workflows that process the same base data at either build or run time.

**Comment by metafloor** [comment]
Thanks Terry.  I have modified it in my local copy for now.

@shaehn: Will publish a patch-release later today that covers this and #122.

**Comment by shaehn** [comment]
Wow.... fastest turn around I have ever had on github..... Nice job!
