### ISSUE TITLE
Background color as parameter

### ISSUE THREAD

**Issue by milenon** [metafloor/bwip-js#129]
It would be nice if we could add backgroung color as parameter when generating the barcode image.

**Comment by metafloor** [comment]
See the BWIPP documentation:  https://github.com/bwipp/postscriptbarcode/wiki/Symbol-Colors#backgroundcolor

And an example:  https://bwipjs-api.metafloor.com/?bcid=code128&text=000123456789&includetext&backgroundcolor=ff0000
