### ISSUE TITLE
console messages in NodeJs

### ISSUE THREAD

**Issue by rogeriojlle** [metafloor/bwip-js#13]
As not to show messages on the console when I call bwipjs.toBuffer()?
ex:
```
...
2
x1,y1,x2,y2=2,0,2,144
optmz,penx,peny=true,4,4
x1,y1,x2,y2=7,0,7,144
...
```

**Comment by metafloor** [comment]
Release 0.14.1 fixes this issue.  The console debugging should never have been included in the released files.
