### ISSUE TITLE
Stuck without "pure" html/js sample

### ISSUE THREAD

**Issue by Paperalien** [metafloor/bwip-js#130]
Hi,

I'm using the web site version of your API, which works wonderfully, but I can only use that as I enter Beta, and I have to transition to using the API internally for release. But ... neither of the two browser examples work for me. I can't use React (way of scope for this release), and the Electron sample uses the "require" keyword, which I assume is just an Electron thing. When I try using that example, simply without the require, I get the error "Uncaught ReferenceError: bwipjs is not defined".

So ... help! Is there a plain old "pure" html sample?

Thanks

**Comment by metafloor** [comment]
The code in `demo.html` is pure html, no react or other framework.  You cannot run it under the `file:` scheme, it must be served due to the XHR usage.  It is also hosted on github.io if you want to check it out, available as http://bwip-js.metafloor.com/demo/demo.html.

**Comment by Paperalien** [comment]
Thanks; that's really thorough, and fantastic as a reference to what can be done.

**Comment by metafloor** [comment]
Please close this issue if you have no add'l questions.

**Comment by metafloor** [comment]
The 2.0 release totally simplifies working with generic browser usage.
