### ISSUE TITLE
Load many qrcode on 1 page ? 

### ISSUE THREAD

**Issue by dofay** [metafloor/bwip-js#131]
Hello, first i'm sorry for bad english. And second... i'm sorry because i'm still beginner using jquery 

i'm trying to make micor-qr with jquery, and found this github. The code is great, trying to print it with small size and working. But the problem is... can i make jquery function, like this?

`jQuery('class').qrcode(the qr text );`

I'm very new at jquery. and what i can is trying erase the code one by one in the demo.html and make the function from there... 

but i'm still confused. The option i'm making is like this.. 

`var elt  = symdesc['microqrcode'];
	var text = '56103';
	var altx = '';
	var opts = '';
	var rot  = 'N';
	var monochrome = 'M';
	var scaleX = 3 || 2;
	var scaleY = 3 || 2;`

Or you can see what i do with demo.html in this [pastebin](https://pastebin.com/5yvhqiPm)

It's working, but i'm stuck with only generating one qr and must clicking "show barcode" button. 
Thank you for reading this, and sorry for making dumb question like this

**Comment by metafloor** [comment]
The 2.0 release should simplify timing issues on the browser since drawing to canvas is now fully synchronous.
