### ISSUE TITLE
DataMatrix barcode does not generate (Infinite Loop)

### ISSUE THREAD

**Issue by fstrube** [metafloor/bwip-js#132]
Referencing bwipp/postscriptbarcode#101

Certain situations were causing DataMatrix barcode generation to crash BWIPP (infinite loop in Browser/Node). This has been fixed in the latest BWIPP version (2019-04-24).

Barcode text to test:
```
ABCDEFGHI|Xxxxxxx|123 W XXXXXXXX AVE
```

**Comment by metafloor** [comment]
Just released 1.7.3 which is patched with the datamatrix encoder in BWIPP 2019-04-24.

**Comment by fstrube** [comment]
The latest release has been working for me.

I think the **Status** section in the README needs to be updated to reflect the version of BWIPP. It still says "Current BWIPP version is 2018-02-04"

**Comment by metafloor** [comment]
Kind of a mixed bag in the 1.7.3 release.  The base code is actually the BWIPP '18 code.  But the datamatrix encoder has been upgraded to the '19 code.  Not sure how to label that.  There are some issues with the postscript graphics emulation when trying to cross-compile the latest BWIPP that have proven hard to resolve.  If node had a built-in (not addon) canvas implementation, it would make things much easier...

**Comment by metafloor** [comment]
Closing for the 2.0 release which now uses the full BWIPP source and compiles against the most recent release.
