### ISSUE TITLE
unable to use https api

### ISSUE THREAD

**Issue by kirkmaOTL** [metafloor/bwip-js#135]
hello,

Following url doesnt work.

https://api-bwipjs.metafloor.com/?bcid=code128&text=S111111&scaleY=1&includetext

Thanks.

**Comment by metafloor** [comment]
Try the sister URL:

https://bwipjs-api.metafloor.com/?bcid=code128&text=S111111&scaleY=1&includetext

I am having some issues with cert renewal.

**Comment by kirkmaOTL** [comment]
Hello,

Thanks for your reply. And this is a great project!

And I am using the http version for now, but as I already sent lots of email using the https version, want to know if it can be fixed quickly...

Thanks again for this great project!

**Comment by metafloor** [comment]
Just bounced the server.  Both URLs seem to be working now...

**Comment by kirkmaOTL** [comment]
yes, it works now! Thanks very much!
