### ISSUE TITLE
Handle encoded IMB (Intelligent Mail Barcode)

### ISSUE THREAD

**Issue by shaehn** [metafloor/bwip-js#136]
I have a package that already encodes IMB's into the standard 65 character ATDF string which just causes bwip to barf. Any chance this could be handled in the near future?

**Comment by metafloor** [comment]
bwip-js is a front-end to the BWIPP project and for the most part, uses the BWIPP functionality directly.  Looking at the postscript source, there is no `raw` option as is available with other bar code types.  So you will have to either convince @terryburton to add the `raw` option, or work with the original, unencoded text.

**Comment by terryburton** [comment]
The "daft" encoder is the means to do this:

https://github.com/bwipp/postscriptbarcode/wiki/DAFT

**Comment by metafloor** [comment]
Thanks Terry!  Forgot about that one.

**Comment by shaehn** [comment]
Ok, the alternate "daft" encoder will suffice for me. Thanks for the guidance.
