### ISSUE TITLE
Render barcodes running while using file://

### ISSUE THREAD

**Issue by vinod-hub** [metafloor/bwip-js#139]
Hi, I'm using BWIP-JS in forms and it works perfectly once we publish the forms to the server. But, we are having a feature of previewing the form using file:// before publishing. We are unable to load the fonts while previewing in browsers due to CORS issue resulting in error to render the barcodes. 
Is there any way, that I can render the barcode while running using file:// or avoiding the fonts to load?

Thanks.

**Comment by metafloor** [comment]
Until version 2 of bwip-js is released (not sure of timeframe), it is not be possible to use fonts with the file:// scheme.  My recommendation is to _not_ specify `includetext` when showing your previews.

**Comment by vinod-hub** [comment]
Thanks and closing the issue.
