### ISSUE TITLE
Bar Text of DataMatrix with Numeric

### ISSUE THREAD

**Issue by dtanh72** [metafloor/bwip-js#14]
Dear support team,

How are you?

Thanks for your module.

When i encrypt data which is "20150921" into DataMatrix, i scan barcode result " 09 ".

I don't know how to set the option.

Would you like to support me?

thanks

**Comment by metafloor** [comment]
I have verified this is a bug in the renmatrix module of bwip-js.  I will hopefully have a resolution for it later this week.

**Comment by metafloor** [comment]
Turned out to be a really interesting bug in the PostScript dictionary object emulation.  Version 0.14.2 fixes it.  If you are using bwip-js from the browser, make sure to clear cache to ensure that the most recent files are used.

Please let me know if you have success.

**Comment by dtanh72** [comment]
Thank you very much.
I have success.
