### ISSUE TITLE
Setting Narrow Bar Width

### ISSUE THREAD

**Issue by vinod-hub** [metafloor/bwip-js#140]
Is there any parameter to apply the Narrow Bar Width to the barcode? If yes, what is the parameter and in which units we have to give?

**Comment by metafloor** [comment]
Because the backend logic for generating bar codes is based on PostScript, graphics scaling is used to change the modulus width.  As scale=1, modulus is 1px; scale=2, modulus is 2px; etc.

**Comment by vinod-hub** [comment]
Thanks for the response.
