### ISSUE TITLE
PDF 417 Data compaction modes

### ISSUE THREAD

**Issue by vinod-hub** [metafloor/bwip-js#141]
Hi,

PDF417 has three data compaction modes: binary, text and numeric. Is there any way/option to send these modes while generating PDF417 barcode? 

-Thanks

**Comment by terryburton** [comment]
The specification is more nuanced that that, with additional submodes available in text compaction and the ability to shift and latch between the modes.

The encoder finds the optimal (smallest) encoding for any given input by switching between modes as necessary.

The transmission protocol for readers is well-defined to provide the byte string of the encoded message (sans non-data characters such as latches and switches), therefore any application should be oblivious to the actual compaction schemes that are in effect.

**Comment by vinod-hub** [comment]
Thanks for the response.
