### ISSUE TITLE
Increase width does not work

### ISSUE THREAD

**Issue by Gcaufy** [metafloor/bwip-js#146]
My option is :
```
{
          bcid: 'code128',
          height: 30,
          width: 200,
          scaleX: 1,
          scaleY: 1,
          includetext: true,
          textalign: 'center',
},
```

but width 200 is a little bit short for me, so I try 210. but 210 is too much for me.
and then I tried 205, 203, 201, I found they are all the same with width 210.

so is there a way to increase the width a little bit?

**Comment by metafloor** [comment]
Barcodes grow in quantums because a module width (the narrowest element in the symbol) can only be a whole number of pixels.  This primarily applies with low resolution usage, which is what most HTML applications use.
