### ISSUE TITLE
bwip-js webpack Can't resolve 'fs' error

### ISSUE THREAD

**Issue by ulvido** [metafloor/bwip-js#147]
after these updates webpack gives fs error.

### UPDATES
```
[npm-check] Update complete!
[npm-check] nanoid@2.1.8, core-js@3.5.0, css-loader@3.3.2, terser-webpack-plugin@2.3.0, bwip-js@2.0.2
```

### WEBPACK ERROR
```
ERROR in ./node_modules/bwip-js/dist/bwip-js.js
Module not found: Error: Can't resolve 'fs' in '/home/ulvi/Documents/proje/Google/Extension/rrskit/node_modules/bwip-js/dist'
```

I only downgraded bwip-js to 1.7.4 and keep all other packages updated. now it works fine. so I think it's about bwip-js. any ideas?

**Comment by metafloor** [comment]
Looks like some debug/test code snuck past my checks.  But I am concern with that error as it is in the `toBuffer()` method which is nodejs only.  Is there a well to tell webpack not to include certain exports?

**Comment by ulvido** [comment]
> Looks like some debug/test code snuck past my checks. But I am concern with that error as it is in the `toBuffer()` method which is nodejs only. Is there a way to tell webpack not to include certain exports?

you are definitely right. my webpack target is web. 

#### webpack.config.js
```
...
 target: "web",
...
```

for now the version 1.7.4 does just fine for me. sorry, I don't know how to exclude exports.

**Comment by metafloor** [comment]
No worries.  I do not use webpack so was not aware of how it works.  Reading the docs on webpack, it looks like one cannot mix nodejs and browser code in the same module.  Makes the build scripts a bit more complicated but the easiest solution (for the end user) is separate modules for node and the browser.  And differentiating in `package.json` using `main` vs `browser` as targets.  Will release that later after regression testing.

**Comment by metafloor** [comment]
2.0.4 was published earlier today.  It creates separate modules for the browser and node, differentiated in `package.json`.  Please let me know if that works with your webpack config.

**Comment by ulvido** [comment]
worked with some tweaks. I must say I am not a pro. this is my test case.

1. updated myproject bwip-js to 2.0.2.
2. deleted the myproject/node_modules/bwip-js inner files
3. downloaded 2.0.4 from github and copied into project node_modules revelent folder.

I am using bwip-js with react hooks.
### v1.7.4 code
```
// CUSTOM HOOK - QR CODE CREATOR
const useQrCode = (type, data, isLoading) => {
  const [qr, setQr] = useState();
  useEffect(() => {
    let canvas = document.createElement("canvas");
    bwipjs(canvas, {
      bcid: type,
      text: data,
      scale: 2,
    }, (err, cvs) => { // eslint-disable-line no-unused-vars
      if (err) {
        // Decide how to handle the error
        // `err` may be a string or Error object
      } else {
        isLoading(false);
        setQr(<img className={style["qr"]} src={canvas.toDataURL("image/png")}></img>);
      }
    });
  }, [type, data]);
  return qr;
};
```

#### v2.0.4 tweaked code
```
// CUSTOM HOOK - QR CODE CREATOR
const useQrCode = (type, data, isLoading) => {
  const [qr, setQr] = useState();
  useEffect(() => {
    let canvas = document.createElement("canvas");
    bwipjs.toCanvas(canvas, {
      bcid: type,
      text: data,
      scale: 2,
    })
    isLoading(false);
    setQr(<img className={style["qr"]} src={canvas.toDataURL("image/png")}></img>);
  }, [type, data]);
  return qr;
};
```
the main tweak is bwipjs() -> bwipjs.toCanvas()
 the code works but I'm not sure. without callback  but I think there is a race condition there. I wish toCanvas was thenable like toBuffer. is such thing possible?

**Comment by metafloor** [comment]
As is said on the project README, 2.0 has some breaking changes.  Please see:

https://github.com/metafloor/bwip-js/wiki/Upgrading-to-2.0

**Comment by ka1izer** [comment]
Hi, just came to this project today, and ran into this problem straight away (using it with Angular). Replacing dist folder with dist folder from 2.0.4 works. Now, if only the npm version could update to 2.0.4... :-)

**Comment by metafloor** [comment]
npm was updated to 2.0.4 yesterday.  You should be good to go:

```
$ npm install bwip-js

+ bwip-js@2.0.4
$ ll node_modules/bwip-js/dist/*
-rw-r--r-- 1 Mark None  790711 Oct 26  1985 node_modules/bwip-js/dist/bwip-js-min.js
-rw-r--r-- 1 Mark None 1424165 Oct 26  1985 node_modules/bwip-js/dist/bwip-js.js
-rw-r--r-- 1 Mark None 1428395 Oct 26  1985 node_modules/bwip-js/dist/node-bwipjs.js
```

**Comment by metafloor** [comment]
@ka1izer: When you get 2.0 working with angular, would you mind providing a simple example that I can add to the main README?

**Comment by ka1izer** [comment]
A very simple component with a bwip-js barcode in Angular 8:

`import { Component, ViewChild, ElementRef, OnChanges } from '@angular/core';
import bwipjs from 'bwip-js';

@Component({
	selector: 'example-bwip',
	template: '<canvas #barcodeElement></canvas>',
	styleUrls: []
})
export class ExampleComponent implements OnChanges {

	@ViewChild('barcodeElement', { static: true }) barcodeElement: ElementRef;

	ngOnChanges() {
		try {
			// The return value is the canvas element
			const canvas = bwipjs.toCanvas(this.barcodeElement.nativeElement, {
				bcid: 'code128',       // Barcode type
				text: '0123456789',    // Text to encode
				scale: 3,               // 3x scaling factor
				height: 10,              // Bar height, in millimeters
				includetext: true,            // Show human-readable text
				textxalign: 'center',        // Always good to set this
			});
		}
		catch (e) {
			// 'e' may be a string or Error object
		}
	}
}`

**Comment by metafloor** [comment]
Thanks @ka1izer!  Much appreciated.

**Comment by ulvido** [comment]
this code worked. case closed for me.

### v2.0.5
```
// CUSTOM HOOK - QR CODE CREATOR
const useQrCode = (type, data, isLoading) => {
  const [qr, setQr] = useState();
  useEffect(() => {
    let canvas = document.createElement("canvas");
    try {
      bwipjs.toCanvas(canvas, {
        bcid: type,       // Barcode type
        text: data,    // Text to encode
        scale: 2,
      });
      setQr(<img className={style["qr"]} src={canvas.toDataURL("image/png")}></img>);
      isLoading(false);
    } catch (e) {
      console.error("createQrCode error:", e);
    }
  }, [type, data]);
  return qr;
};
```
