### ISSUE TITLE
QRCode Newlines vs. CRLF

### ISSUE THREAD

**Issue by semireg** [metafloor/bwip-js#149]
Version: 2.0.6

I'm getting inconsistent CRLF results when using the npm module (in browser) vs. the metafloor API URL.

Consider this payload:
```
A\r\nB\r\nC
```

7 bytes. http://bwipjs-api.metafloor.com/?bcid=qrcode&text=A%0D%0AB%0D%0AC&eclevel=M&scale=2 (`%0D%0A` is \r\n)

![2020-01-31 at 11 40 AM](https://user-images.githubusercontent.com/1819762/73561613-e6328680-441e-11ea-8955-581052bcc8aa.png)

Running the resulting QRCode through https://online-barcode-reader.inliteresearch.com results in Length: 7 as expected.

![2020-01-31 at 11 44 AM](https://user-images.githubusercontent.com/1819762/73561706-18dc7f00-441f-11ea-8033-db2dc93cf4f3.png)

However, when I use bwip-js locally I lose 2 bytes (presumably the \r characters).

This image only has 5 bytes encoded:
![2020-01-31 at 11 42 AM](https://user-images.githubusercontent.com/1819762/73561584-db77f180-441e-11ea-8b8c-c4e12ceb5459.png)

Moreover, some QR code readers (notably on Windows into Notepad.exe) end up showing the output text as a single line of text `ABC` instead of 
```
A
B
C
```

![2020-01-31 at 11 44 AM](https://user-images.githubusercontent.com/1819762/73561671-02cebe80-441f-11ea-9c3f-7921200f155f.png)

Thank you for all your hard work!

**Comment by metafloor** [comment]
I need to see code that shows how you are using it locally, otherwise there is no way to understand the issue.

**Comment by semireg** [comment]
In reviewing my code to provide code here I've embarrassedly determined that this is my error 😄
