### ISSUE TITLE
"includetext" parameter is not working on the rhcloud.com API

### ISSUE THREAD

**Issue by v15h** [metafloor/bwip-js#15]
Example:

https://api-bwipjs.rhcloud.com/?bcid=upca&text=01123456789&includetext

Renders the barcode, but not the text underneath

**Comment by metafloor** [comment]
Discovered the same issue last night, by coincidence.  I have updated the deployment to bwip-js v0.14.2 and it looks to be working again.

**Comment by v15h** [comment]
Awesome!

Thanks.
