### ISSUE TITLE
HTTPS Calls Fail

### ISSUE THREAD

**Issue by ifamvd** [metafloor/bwip-js#152]
I am wondering if I am still having certificates issue. All of my HTTPS calls always fail.

![image](https://user-images.githubusercontent.com/36249453/75578734-fe9bbe00-5a29-11ea-812d-7ddcb0ed006b.png)

And I am using the URL that is supposedly not having any certificate issues.

![image](https://user-images.githubusercontent.com/36249453/75578788-20954080-5a2a-11ea-9773-24af363c9dcc.png)

**Comment by metafloor** [comment]
Afraid the service has gotten too popular and is getting overwhelmed by requests.  It is running on a micro-aws instance with one cpu and very little RAM....  

When I first checked, node was at 100% CPU.  After restarting a few times, it appears to be running normally again.

**Comment by ifamvd** [comment]
Thank you for the response, and thank you for the reboot! This is such a useful service, so glad that it is back up and running.
