### ISSUE TITLE
Cannot generate PDF with QR codes on 1.7.4 and up

### ISSUE THREAD

**Issue by jaworek** [metafloor/bwip-js#153]
I want to update `bwip-js` in my project from 1.7.3 to newest version. Everything seemed to go fine until I tested my PDF QR codes generator. I noticed that bwip-js instead of generating them, creates black boxes. This problem occurs on every version after 1.7.3. It seems that this bug occurs when I try generate JPG image from canvas using .toDataUrl() function as I did not notice any issues when displaying QR codes in a web browser.

To fix it I tried setting `backgroundcolor` to '#ffffff', but it did not make any change.

Is it a bug or intentional change in newer versions? Is there a better way to implement such behaviour?

Generated PDF on 1.7.3:
![image](https://user-images.githubusercontent.com/22678765/75808031-b6accc00-5d86-11ea-9ce1-865ee7fd29dc.png)

Generated PDF on 1.7.4 and up:
![image](https://user-images.githubusercontent.com/22678765/75808042-b9a7bc80-5d86-11ea-864e-dc0cdaaa2815.png)

Working reproduction with 1.7.3:
https://codesandbox.io/s/currying-darkness-xlfbc

Reproduction with 1.7.4:
https://codesandbox.io/s/angry-darkness-ukk8v

Reproduction with 2.0:
https://codesandbox.io/s/nervous-zhukovsky-qs6zj

**Comment by metafloor** [comment]
It looks like transparent background.  BWIPP uses `rrggbb` rather than the css `#rrggbb` syntax.  Please try without the hash-sign e.g. `backgroundcolor=ffffff`

**Comment by jaworek** [comment]
Great! Thank you!
