### ISSUE TITLE
\n\r in GS1 datamatrix

### ISSUE THREAD

**Issue by tam1111574** [metafloor/bwip-js#155]
Hi all,
Bwip-js is a good library for javasript. I use this library for my product
I have a problem with data of GS1 datamatrix.
When data of GS1 datamatrix have character "\r" or "\n". 
Example:  (01)34567890123457103456789Ê(21)345611089012(93)3\n345 
When I use the barcode scanning software to read barcode, the result will have a break line in text data
So how to remove the break line in barcode data and remain character "\r" and \n".
Thank your very much.

**Comment by metafloor** [comment]
I am not sure I understand your question:

> So how to remove the break line in barcode data and remain character "\r" and \n".

Do you want to remove the `\n` from the barcode data but have the barcode scanner (keyboard wedge) send an `[Enter]` keypress?
