### ISSUE TITLE
Same barcode image for different width and height

### ISSUE THREAD

**Issue by neilpalima** [metafloor/bwip-js#158]
I'm using the library on node.js to create images.

Why does the library generates the same image but using with different `size` values (using size 1-8 resulted to the same barcode image);

```
await bwip.toBuffer({
      bcid: 'datamatrix',
      text: 'test code,
      scale: 1,
      width: size,
      height: size
    });
```

**Comment by metafloor** [comment]
The width and height parameters have been normalized to millimeters.  I suspect you want to change the size values to 25, 50, etc.  

And to answer why, 1-8 mm is so small that the image size is getting rounded up to the same dimension so the symbol can be rendered accurately.

**Comment by neilpalima** [comment]
No, I were only using 1-20 as values of `size`. Why 1-8 mm is so small? Those where already in mm right or it needs to be converted in mm? Your [demo](http://bwip-js.metafloor.com/demo/demo.html)  is working fine though I am using the library in a node backend. Can you give the parameters used in your demo?

**Comment by metafloor** [comment]
I tested against node with width/height set to 1-20. 

For width/height set to 1-9, the image was 14px square.
For width/height set to 10-14, the image was 28px square.
For width/height set to 15-19, the image was 42px square.
For width/height of 20, the image was 56px square.

This is the expected behavior.  A "module" can only be a whole number of pixels.  And all modules in the symbol must be the same size.  So barcodes, linear and 2d, grow in quantums and bwip-js calculates the largest symbol that won't exceed the requested size.

**Comment by neilpalima** [comment]
I thought the value to be supplied for width and height is already treated in millimeters? If it's in millimeters, it should already be changing depending on the value supplied.

This sample doc belows says height is in millimeters

```
const bwipjs = require('bwip-js');
 
bwipjs.toBuffer({
        bcid:        'code128',       // Barcode type
        text:        '0123456789',    // Text to encode
        scale:       3,               // 3x scaling factor
        height:      10,              // Bar height, in millimeters
        includetext: true,            // Show human-readable text
        textxalign:  'center',        // Always good to set this
    }, function (err, png) {
        if (err) {
            // `err` may be a string or Error object
        } else {
            // `png` is a Buffer
            // png.length           : PNG file length
            // png.readUInt32BE(16) : PNG image width
            // png.readUInt32BE(20) : PNG image height
        }
    });
```

On your demo, the image generated is changing on different scaleX/scaleY.

**Comment by sharekim93** [comment]
Is this solved?
