### ISSUE TITLE
Uncaught TypeError: Cannot set property 'bwipjs_name' of null

### ISSUE THREAD

**Issue by spuky** [metafloor/bwip-js#160]
trying to use in a vue.js component...

iporteded with:

import bwipjs from 'bwip-js';

even when just using the sample i get:

Uncaught TypeError: Cannot set property 'bwipjs_name' of null as console output... 

barcode works...

when trying to load a custom font...

` client.open('GET', '/DINPro.otf');
  client.onload = function() {
      if (this.status == 200) {
          // Create a binary string from the returned data, then encode it as a data URL.
          let fontfile = new Uint8Array(this.response);
          bwipjs.loadFont("DINPro", 100, 100, fontfile);
      }
  }
  client.send();`

console has an error: 
Uncaught TypeError: Cannot set property 'bwipjs_name' of null
    at Object.loadFont (bwip-js.js?2582:34191)
    at XMLHttpRequest.client.onload (Scanntool.vue?e58f:139)

am I doing anything wrong using version  2.0.6

**Comment by metafloor** [comment]
I found the issue.  The font lib is looking for a string and converting to Uint8Array but it failed to test for the data already being a Uint8Array.  I will have a new release out later today.

**Comment by spuky** [comment]
Also happens when I provide the Font as Base64 string in a variable... 

<img width="694" alt="Bildschirmfoto 2020-06-03 um 17 36 41" src="https://user-images.githubusercontent.com/271187/83657184-cecbfb80-a5c0-11ea-8660-af94d90cdccc.png">

results in...

<img width="449" alt="Bildschirmfoto 2020-06-03 um 17 38 18" src="https://user-images.githubusercontent.com/271187/83657423-21a5b300-a5c1-11ea-9422-780441738473.png">

not shure it is the array....

**Comment by metafloor** [comment]
Looks like there are two issues.  The one I found and probably an incompatible font file.  The font lib cannot handle modern fonts with ligatures or the use of hinting to properly render glyphs (a lot of CJK fonts).  I will try doing some tests on the DINpro font and see why it is going on.  Are you using the medium weight version of the font?

**Comment by spuky** [comment]
Using Regular  also just tried Base64 encoding Inconsolata.otf with:

 openssl base64 -in public/Inconsolata.otf -out public/Iconos.txt 

and using that in my fontfile variable... fails with the same error....

**Comment by spuky** [comment]
Just reduced it to just the minified version and... pure js...

https://spuky.de/metafloordemo/index.html

**Comment by metafloor** [comment]
Got it figured out:

![image](https://user-images.githubusercontent.com/385436/83665123-3fa2f180-a588-11ea-8ad1-3a3cab5d3895.png)

The test for base64 was assuming no whitespace in the first 75 characters, which was a really bad assumption....  Will have the patch out later today.

**Comment by spuky** [comment]
Thanks it is working now...

**Comment by CharlieJ0hn** [comment]
@spuky can you help me, icant run it in vue. i need a demo about it.
