### ISSUE TITLE
Online Generator Usage Considerations

### ISSUE THREAD

**Issue by ogomezba** [metafloor/bwip-js#162]
Hi everyone!

First, thank you for sharing this great project. I've been recently using the bwip generator js pure version and worked flawlessly.
However, now I need to use the online generator (for technical reasons) to generate the barcodes. I wanted to ask if there is any usage considerations of the Online API (number of requests, any legal considerations).

Thank you so much!

**Comment by metafloor** [comment]
The API is currently hosted by a micro AWS instance and it is pretty much at its limit.  So I would not expect great response from it.  No logging of the content of barcodes is done - just tracking of what types, sizes, etc.

**Comment by ogomezba** [comment]
Okay, thank you so much!
