### ISSUE TITLE
[Question] How to make text ignore the scale option?

### ISSUE THREAD

**Issue by dinfer** [metafloor/bwip-js#163]
I want to scale the bar code image without affecting the text. Using the API, I got the correct result. but with the same options, I cannot get the image like API returns

url: http://bwipjs-api.metafloor.com/?bcid=code128&includetext&scaleX=10&scaleY=1&text=0123456789

image:
![image](https://user-images.githubusercontent.com/11496403/84881971-2b4f1080-b0c1-11ea-940e-5b1707bb9d29.png)

Using the cli or lib(with svg renderer from official example folder), I got the same result. the font is scaled.

cmd: 
```
.\node_modules\.bin\bwip-js --bcid=code128 --includetext --scaleX=10 --scaleY=1 --text=0123456789 t.png
```

image:
![image](https://user-images.githubusercontent.com/11496403/84882397-c811ae00-b0c1-11ea-903d-5a738716448b.png)

The bwip version is 2.0.7, I tried in cli, node, and browser. and some other options like textsize can not generate the image like API returns. Can anyone tell me how to scale bar code image & text seperately?

**Comment by metafloor** [comment]
Due to technical reasons, the API is still running version 1.7, and its font handling is based on bitmaps that do not asymmetrically scale.  For your example, where you want the font and image width to be 10x, but symbol height to be something less, just set `height` to a smaller value.   For example, `scale=10` and `height=3`:

![image](https://user-images.githubusercontent.com/385436/84905494-f6fe3480-b06d-11ea-9463-41db26a8f06e.png)

**Comment by dinfer** [comment]
Thanks for reply! 

I found a way to avoid text scaling by using `textsize` options to fix font size. But when using svg renderer provided in example folder, the render result is different with the result rendered by canvas.

using svg.html
![image](https://user-images.githubusercontent.com/11496403/84969070-837e2500-b14a-11ea-8f1d-d3da246063ba.png)

using example.html
![image](https://user-images.githubusercontent.com/11496403/84969082-8a0c9c80-b14a-11ea-9d1d-7bb7fa71a80a.png)

And I found another problem. the barcode generated by svg is not aligned, while the result canvas rendered is perfect.

using example.html, perfectly aligned
![image](https://user-images.githubusercontent.com/11496403/84969531-7b72b500-b14b-11ea-9e10-6cc1a8824b7c.png)

using svg.html, slightly bug in layout the bars
![image](https://user-images.githubusercontent.com/11496403/84969461-5a11c900-b14b-11ea-8c45-37b2d58fd4d7.png)

In some case, `textsize` works in canvas, but for svg, it seems not work, the to render result below are the same.

svg.html with textsize=7
![image](https://user-images.githubusercontent.com/11496403/84970431-41a2ae00-b14d-11ea-9831-608a160d40e1.png)

textsize=8
![image](https://user-images.githubusercontent.com/11496403/84970456-4ebf9d00-b14d-11ea-99da-d61057f38d74.png)


Because the render result will be scaled, I have to use svg renderer. Is there another svg renderer that I can have a try?

**Comment by metafloor** [comment]
Closing this out as the most recent releases have resolved the issues discussed.
