### ISSUE TITLE
Generating barcodes of specified dimension

### ISSUE THREAD

**Issue by lameventanas** [metafloor/bwip-js#166]
I'm using node, and I've been trying to generate barcodes of a specific dimension, but no matter what bcid, width, height, scale, scaleX and scaleY values I use, nothing seems to work.
I have verified that the desired dimensions are enough for the text.
Surely it should be easier to generate barcodes of a desired size (be it pixels or mm).

**Comment by metafloor** [comment]
At low resolution (as used with HTML), it is not possible to generate barcodes to a specific size.  The widths of the bars and spaces (or squares/rects in 2d symbols) must be fixed size.  Take a qrcode with 20 "modules" width and height.  If a module is 2px, then the symbol size is 40px x 40px.  If the module is 3px, symbol size is 60px x 60px.  And it can't be any size in between.  

Similar logic for linear barcodes, although there is more variability, especially with narrow/wide symbols like code39.  But the bars and spaces must be fixed for the entire image, and the images still grow in quantums.

**Comment by jeppsson** [comment]
I think scaling stopped working in last release.
https://bwipjs-api.metafloor.com/?bcid=ean13&text=982903050010&includetext=true&scaleX=4&scaleY=3
When removing `scaleX` and `scaleY` parameters, it works.

This this worked yesterday. I guess before latest release ([v2.0.8](https://github.com/metafloor/bwip-js/releases/tag/v2.0.8)) was deployed.

**Comment by metafloor** [comment]
No response from the OP, so closing this issue.
