### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by koenm** [metafloor/bwip-js#167]
Hi guys,

using the API i'm getting a TypeError:
TypeError: Cannot set property 'prev' of null

The problem is occurring since this morning. Before it always worked like a charm.

Anyone has a clue?
Thanks

**Comment by metafloor** [comment]
Please provide an example that reproduces the error.

**Comment by koenm** [comment]
Hi,

it's also in the example on your webpage:

http://bwipjs-api.metafloor.com/?bcid=code128&text=AB1234567890&scale=3&rotate=I&includetext

**Comment by metafloor** [comment]
It's a problem with the glyph cache.  I have restarted the api server, which clears the cache, and it is working again. 

Will continue to look into it.

**Comment by metafloor** [comment]
The API server has been updated with the fix and restarted.

**Comment by metafloor** [comment]
Since no new complaints, closing this issue.
