### ISSUE TITLE
How to move barcode text to the top?

### ISSUE THREAD

**Issue by tiger1016** [metafloor/bwip-js#171]
Thanks for your code.

But while working, l am not sure how to move barcode text to the top.
Right now, textAlign config is set 'center', l changed it into 'top' or 'bottom', but it doesn't work, during, text shows always at the bottom of barcode.
please help me with this.
Looking forward to hearing back.
Best Regards.

**Comment by metafloor** [comment]
You need to look at the BWIPP documentation to understand the possibilities:

https://github.com/bwipp/postscriptbarcode/wiki

Text positioning is covered under the "Options Reference" section.  You want the `textyalign` property:

https://github.com/bwipp/postscriptbarcode/wiki/Text-Positioning#textyalign

**Comment by tiger1016** [comment]
Thanks for your reply.
It works !
