### ISSUE TITLE
RGB Bar Color Not Parsing Correctly

### ISSUE THREAD

**Issue by semireg** [metafloor/bwip-js#173]
I can't get barcolor to work properly.

https://bwipjs-api.metafloor.com/?bcid=qrcode&text=http%3A%2F%2Fgoo.gl%2F0bis&eclevel=M&barcolor=0000FF&backgroundcolor=666666&scale=4

Only barcolor=FF0000 (red) renders correctly. Things like barcolor=00FF00 (green) and 0000FF (blue) render incorrectly. For what it's worth, it seems like backgroundcolor works as expected.

**Comment by metafloor** [comment]
Simple copy/paste bug.  Thanks for the report.  Fixed in 2.0.10.

**Comment by metafloor** [comment]
Closing this as fixed.

**Comment by semireg** [comment]
Confirmed. Thank you.
