### ISSUE TITLE
api not working

### ISSUE THREAD

**Issue by satyasandeep007** [metafloor/bwip-js#177]
I have implemented your api in a html file in my project. But suddenly today the app crashed and when i try to hit the sample api you provided in documentation 

https://bwipjs-api.metafloor.com/?bcid=code128&text=1234567890

the page is not working. Please check why its happening.

**Comment by grgurimoreno** [comment]
Same here, API is not responding. :(

**Comment by satyasandeep007** [comment]
ha, i am trying to implement their npm package. If developer responds quickly, that will help us.

**Comment by grgurimoreno** [comment]
works again, thx 👍

**Comment by satyasandeep007** [comment]
Great. I have implemented their npm package and its working great. It's better than API call. Because if their server goes down again then we will be in trouble.

**Comment by satyasandeep007** [comment]
Finally the API started working.
