### ISSUE TITLE
metafloor bwip-js pdfkit example colors options not working

### ISSUE THREAD

**Issue by rutonesha** [metafloor/bwip-js#179]
I have recently use dawing-pdfkit example and pdfkit to generate barcodes as pdf, with all opts provided in examples are working fine but if I add other options like backgroundcolor opts doesn't change anything,

`const fs = require('fs');
const PDFDocument = require('pdfkit');
const bwipjs = require('bwip-js');
const drawing = require('bwip-js/examples/drawing-pdfkit');

const doc = new PDFDocument; 

        doc.pipe(fs.createWriteStream('bwip-js.pdf'));

        at(0, 0, {
                bcid: 'qrcode',
                text: 'bwip-js.metafloor.com',
                padding: 2,
                backgroundcolor: '077a56',
                scale: 1,
        });

        at(100, 20, {
                bcid: 'qrcode',
                text: 'bwip-js.metafloor.com',
                scale: '1',
                padding: '8',
                backgroundcolor: "AFB364",
                bordercolor: "000000"
        });

        doc.end();
        console.log('saved as bwip-js.pdf');

        function at(x, y, opts, scale) {
            doc.save();
            doc.translate(x, y);
            doc.scale(scale || .5);
            
            bwipjs.fixupOptions(opts);
            bwipjs.render(opts, drawing(doc, opts, bwipjs.FontLib));
        
            doc.restore();
        }

    }

}`

**Comment by metafloor** [comment]
Please try the following replacement for `drawing-pdfkit.js` and let me know if that solves the issue.

[drawing-pdfkit.zip](https://github.com/metafloor/bwip-js/files/5263827/drawing-pdfkit.zip)

**Comment by rutonesha** [comment]
My issue is solved!! Thank you
