### ISSUE TITLE
[Gatsby/React] Barcode displayed on a smartphone not scannable by a barcode scanner in the real world.

### ISSUE THREAD

**Issue by neelkarma** [metafloor/bwip-js#183]
Hi there,
I am making a Gatsby website that generates a code128 barcode from a number inputted by the user. I've gotten the barcode to show. However, I want to make it so that if you visit the website on a phone you can scan the barcode displayed on the phone with a barcode scanner in the real world.

BWIPP Configuration:
```javascript
{
  bcid: "code128",
  text: "440805299" // An example input from the user
  scale: 10,
  includetext: true,
  textxalign: "center"
}
```
I've tried setting my phone's brightness to max, adjusting the displayed barcode size, playing around with the `scale` parameter, but I can't seem to get the scanner to recognize the barcode on the phone.

Is there something I'm missing here or does it really just depend on the specs of the phone or barcode scanner?

P.S. Gatsby is a static site generator made from React. Basically, anything that works in React also works in Gatsby.

**Comment by metafloor** [comment]
Barcode scanners (laser based) use reflection and absorption of light to "see" the barcode.  A glass surface like a computer/phone screen reflects uniformly regardless of what is being displayed behind the glass.

You can use camera based scanners (dedicated barcode scanners or a phone's camera) to scan barcodes displayed on a screen but even that can be hit or miss.  Cameras see differently than the human eye and things like pixel density and brightness/contrast  settings affect the camera.  For best results make sure to have lots of whitespace around the barcode.  And a 2d symbol like qrcode often works better than a linear symbol like code128 as they have built in alignment and finder "marks".

**Comment by neelkarma** [comment]
Ok, thanks for the explanation! I'll try your suggestion about adding whitespace around the barcode, but I think that it's most likely the scanner that's not registering the barcode.

Closing this since I've gotten the answer I needed.
