### ISSUE TITLE
Is there any setting for me to use ECC 200 in datamatrix type?

### ISSUE THREAD

**Issue by a9293340** [metafloor/bwip-js#185]
Hi all,
Bwip-js is a good library for javasript.  In my project I want to achieve  Reader Programming( 0xea ).This is data example:
`Buffer.from([0xea,0x7e,0x7e,0x70,0x63,0x77,0x63,0x69,0x6e,0x6f,0x7e,0x7e,0x80,0x29,0x69,0x21,0x42,0x00,0x24,0x00,0x14,0x00,0x00,0x01,0x46,0x55,0x5a,0x5a,0x59,0x53,0x43,0x41,0x4e,0x20,0x41,0x37,0x37,0x30,0x2d,0x32,0x00,0x01,0x00,0x06,0x02,0x02,0x04,0x03,0x80,0x06,0x02,0x00,0x02,0xff,0xff]).toString('latin1')`

How can I use this correctly?

**Comment by metafloor** [comment]
You will likely want to use the `^parsefnc` option with the `^PROG` codeword at the start.  For more information:

https://github.com/bwipp/postscriptbarcode/wiki/Data-Matrix

**Comment by a9293340** [comment]
Thanks for your answer. This is really useful. But how can  I use bwipp's option in bwip-js?
This is my source code:
`
      bwipjs.toBuffer({
        bcid:'datamatrix',
        text:Buffer.from([0xea,0x7e,0x7e,0x70,0x63,0x77,0x63,0x69,0x6e,0x6f,0x7e,0x7e,0x80,0x29,0x69,0x21,0x42,0x00,0x24,0x00,0x14,0x00,0x00,0x01,0x46,0x55,0x5a,0x5a,0x59,0x53,0x43,0x41,0x4e,0x20,0x41,0x37,0x37,0x30,0x2d,0x32,0x00,0x01,0x00,0x06,0x02,0x02,0x04,0x03,0x80,0x06,0x02,0x00,0x02,0xff,0xff]).toString('latin1'),
        rows:48,
        columns:48,
        scale:1
      }, (err, png) => {
        if (err) {
          document.getElementById('output').textContent = err;
        } else {
          let blx = new Blob([png],{type:'image/png'})
          document.getElementById('myimg').src = window.URL.createObjectURL(blx);
        }
      });
`

How to use parsefnc option?

**Comment by metafloor** [comment]
Assuming this topic is closed...
