### ISSUE TITLE
Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by yudy-chen** [metafloor/bwip-js#193]
First time using it. When trying the example of [Node.js Image Generator](https://www.npmjs.com/package/bwip-js#nodejs-image-generator) then it shows following error

```

TypeError: Right-hand side of 'instanceof' is not an object
    at Deflate.Readable (internal/streams/readable.js:193:25)
    at Deflate.Duplex (internal/streams/duplex.js:56:12)
    at Deflate.Transform (internal/streams/transform.js:117:10)
    at Deflate.ZlibBase (zlib.js:271:13)
    at Deflate.Zlib (zlib.js:669:12)
    at new Deflate (zlib.js:708:8)
    at Object.value [as createDeflate] (zlib.js:849:14)
    at makePNG (D:\Work\testBarcode\node_modules\bwip-js\dist\node-bwipjs.js:34210:27)
    at Object.end (D:\Work\testBarcode\node_modules\bwip-js\dist\node-bwipjs.js:34202:4)
    at BWIPJS.render (D:\Work\testBarcode\node_modules\bwip-js\dist\node-bwipjs.js:33685:22)

```

**The fix is that to put add line** `require('stream')`  on application script so it will be like below. Hope this help others

```
const bwipjs = require('bwip-js');
require('stream')
bwipjs.toBuffer({ ... })
```

**Comment by metafloor** [comment]
What version of nodejs are you using?

**Comment by yudy-chen** [comment]
v14.15.4

**Comment by metafloor** [comment]
Cannot reproduce with v14 or v15.  Most likely something in your code that is modifying the streams module.  Can you reproduce the issue with just a simple `toBuffer()` example?

**Comment by yudy-chen** [comment]
I was using the code from your example. No any modification

```
const bwipjs = require('bwip-js');
 
bwipjs.toBuffer({
        bcid:        'code128',       // Barcode type
        text:        '0123456789',    // Text to encode
        scale:       3,               // 3x scaling factor
        height:      10,              // Bar height, in millimeters
        includetext: true,            // Show human-readable text
        textxalign:  'center',        // Always good to set this
    }, function (err, png) {
        if (err) {
            // `err` may be a string or Error object
        } else {
            // `png` is a Buffer
            // png.length           : PNG file length
            // png.readUInt32BE(16) : PNG image width
            // png.readUInt32BE(20) : PNG image height
        }
    });
```

I was reading this link to know the fix [Stream](https://github.com/nodejs/node/issues/37021#issuecomment-765652644). Not sure either the real problem, but seems related with zlib library itself

**Comment by metafloor** [comment]
I tried exactly the same code against newly installed versions of node 14 and 15.  No problem found on windows (64bit) and ubuntu (64bit).  It appears to be something local to your PC or OS.

**Comment by metafloor** [comment]
Just tried on a windows 7 machine (which modern nodejs is specifically _not_ supported on).  I can reproduce the issue on that OS.  I will put out a patch tomorrow that simply includes the stream module in the zlibpng builtin drawing interface.

**Comment by yudy-chen** [comment]
Just info, I am using Win 10 pro 64 bit.
Do you know what is impacting this issue specifically?

**Comment by metafloor** [comment]
It appears to be a regression in nodejs: https://github.com/nodejs/node/issues/37021
