### ISSUE TITLE
Pro Service Request

### ISSUE THREAD

**Issue by selvajo1990** [metafloor/bwip-js#194]
Hi,

We used your API Service for printing barcode label

Do you have `https://bwipjs-api.metafloor.com/?bcid=code128&text=AB1234567890&scaleY=1&includetext` subscription for this service?

**Comment by metafloor** [comment]
There is no commercial license required.  Currently the service is hosted on a micro AWS instance but the costs have been escalating (the service has become a bit too popular ;-).  I am currently testing a deployment on the heroku free tier and will likely roll that out officially in the next month or so.  No change in API but be prepared to update the URL.

For those who would like to get  a head start on the migration, the service is currently available on heroku at: 

  https://bwip-js.herokuapp.com/

If you encounter any issues, please let me know.

**Comment by selvajo1990** [comment]
thank you for the information. we will wait :)
