### ISSUE TITLE
Web API stopped working

### ISSUE THREAD

**Issue by schrofl1** [metafloor/bwip-js#196]
Web API stopped working

Try to check statistics on the page https://bwipjs-api.metafloor.com/ but the browser told me the following
ERR_CONNECTION_TIMED_OUT

Tried to check this issue via Demo app http://bwip-js.metafloor.com/demo/demo.html
By clicking on "goto URL" same error ERR_CONNECTION_TIMED_OUT

Can you please check why?

Kind Regards

**Comment by ucastanedaBcode** [comment]
since yesterday is down

**Comment by metafloor** [comment]
Unfortunately, it appears someone is attacking the service.  Please try the following as an alternate:

  https://bwip-js.herokuapp.com/

Same API.

The plan is to transition permanently to that new URL as it gives more control over deployment and reduces ongoing costs and development tasks.

**Comment by schrofl1** [comment]
Thanks for your help
