### ISSUE TITLE
Chinese characters does not work in javascript version but it works in postscript version

### ISSUE THREAD

**Issue by Pylipala** [metafloor/bwip-js#2]
To encode Chinese characters in barcode, I choose the popular QR barcode.

First I visit http://www.terryburton.co.uk/barcodewriter/generator/

I choose "QR Code" for "Barcode" option, input "中文" for "Contents", and leave "Options" as it is. Then I press "Make Barcode" button. After a while, a QR barcode appears, I scan it with my phone and it says "中文", which is correct.

Then I visit http://metafloor.github.io/bwip-js/demo/demo.html

I do the same thing as above, but when I click the button "Show Barcode", a message pops up saying "length: invalid: integertype".

I think the terryburton.co.uk site should be using postscript while the metafloor.github.io is using javascript. So there might be something wrong converting postscript into javascript.

**Comment by metafloor** [comment]
Thanks for the bug report. 

The file bwip.js has been updated so it converts any string that is not 8-bit clean to UTF-8.

I have verified against Terry's demo and they now match.  Tested both 中文 which does not contain a surrogate pair and several characters that require surrogates.
