### ISSUE TITLE
Custom number of rows & columns (module width and height) when generating 'dotcode'

### ISSUE THREAD

**Issue by javierjrueda** [metafloor/bwip-js#201]
I can access the raw data using `bwipjs.raw`, but I've noticed `pixx`, `pixy` are automatically calculated.

I'd like to be able to edit the number of columns and rows of the generated Dotcode.

Would that be possible? We'd be happy to pay if someone could implement this behavior.

Thank you very much.

**Comment by terryburton** [comment]
The `rows` and `columns` options allow you to restrict these parameters.

See: https://github.com/bwipp/postscriptbarcode/wiki/DotCode

**Comment by javierjrueda** [comment]
> The `rows` and `columns` options allow you to restrict these parameters.
> 
> See: https://github.com/bwipp/postscriptbarcode/wiki/DotCode

Thanks, this works perfectly! Closing the issue.
