### ISSUE TITLE
Code128 generated barcodes overlap and cannot be recognized by code scanning tool.

### ISSUE THREAD

**Issue by zwt97** [metafloor/bwip-js#202]
In the current version, when the barcode type is Code128, it is scaled to 1, and the generated barcodes are overlapped, which leads to that the code scanning tool cannot scan the correct barcode number.

**Comment by metafloor** [comment]
bwip-js ensures that all bar and space widths are uniform.  My guess is you are displaying the generated image with a scaling factor (by setting width/height on the image, for example).

**Comment by zwt97** [comment]
The bar code lines overlap in the following two cases: 1. When the values of scaleX and scaleY are set to 1 respectively; 2. only when scale:1 is set. The test barcode number is 1594724286155, and the barcode type is selected as Code128, which can reproduce the problems I mentioned.

**Comment by metafloor** [comment]
Pls show the code you are using to generate the image.

**Comment by zwt97** [comment]
The following is the code related to my image generation, because it is a Vue project. If it is not easy to debug, I found the demo link (http://bwip-js.metafloor.com/demo/demo.html) about bwip.js, which also reflects the problem I said.
   
   HTML：   <canvas type="2d" :canvas-id="`code_1594724286155`" :id="`code_1594724286155`" width=1 height=1 style="border:1px solid rgb(255,255,255);" v-else></canvas>
   JS：
   import bwipjs from 'bwip-js';
   
   mounted() {
     this.handleBornCode();
   },
   methods: {
      handleBornCode() {
        setTimeout(() => {
          try {
            bwipjs.toCanvas('code_1594724286155', {
              bcid: 'code128',
              text: "1594724286155",
              scaleX: 1,
              scaleY: 1,
              // scale: 1,
              includetext: false,
              textxalign: 'center',
              backgroundcolor: "FFFFFF"
            });
         } catch (e) {
          
        }
      }, 300);
    },
   }

**Comment by zwt97** [comment]
HTML：<canvas type="2d" :canvas-id="`code_1594724286155`" :id="`code_1594724286155`" width=1 height=1 style="border:1px solid rgb(255,255,255);"></canvas>

**Comment by zwt97** [comment]
HTML：“<canvas type="2d" canvas-id="code_1594724286155" id="code_1594724286155" width=1 height=1 style="border:1px solid rgb(255,255,255);"></canvas>”

**Comment by zwt97** [comment]
HTML： `<canvas type="2d" canvas-id="code_1594724286155" id="code_1594724286155" width=1 height=1 style="border:1px solid rgb(255,255,255);"></canvas>`

**Comment by zwt97** [comment]
Will the situation I mentioned above be used as a problem to repair and improve the code?

**Comment by metafloor** [comment]
New version 2.1.2 should resolve this issue.

**Comment by zwt97** [comment]
I reset npm install bwip-js to get the latest installation package version 2.1.2.In the project of npm install bwip-js, scaleX and scaleY are both set to 1, and the bar code generated by adjusting bwipjs.toCanvas still has the phenomenon of overlapping bar code lines. But the barcode generated by the demo link (http://bwip-js.metafloor.com/demo/demo.html) is normal and has no problem.

**Comment by zwt97** [comment]
I reset npm install bwip-js to get the latest installation package version 2.1.2.In the project of npm install bwip-js, scaleX and scaleY are both set to 1, and the bar code generated by adjusting bwipjs.toCanvas still has the phenomenon of overlapping bar code lines. But the barcode generated by the demo link (http://bwip-js.metafloor.com/demo/demo.html) is normal and has no problem.

**Comment by metafloor** [comment]
Inspect `bwipjs.VERSION` in your browser code.  The browser may be caching the javascript or maybe the script packer you are using didn't get updated.

**Comment by zwt97** [comment]
You're right. It's really the browser cache. Now I have no problem generating bar codes here. Give you a big compliment, you are great.

**Comment by zwt97** [comment]
I'm going to close the problem, thank you for your forceful solution.
