### ISSUE TITLE
200 dpi and 300 dpi

### ISSUE THREAD

**Issue by manojjonam10** [metafloor/bwip-js#203]
what scaling would you recommend trying for the smallest Code 128 auto to print to both 200 dpi and 300 dpi versions. Would really appreciate your opinion

**Comment by metafloor** [comment]
Need to understand your use-case better.  Are you printing to a print driver (windows/unix) that then prints to a 200/300 dpi printer?  Please provide more details.

**Comment by manojjonam10** [comment]
Yes we print via pdf to the windows/unix driver that then prints to 200.400 dpi printers
we also print via a Mac driver on occasions

**Comment by manojjonam10** [comment]
Yes we print via pdf to the windows/unix driver that then prints to 200 and 300 dpi printers

**Comment by metafloor** [comment]
The PDF will make it really difficult.  Image quality is can be changed when added to a pdf.  Can you post some example prints at 200 and 300 dpi to show where the issues are?

**Comment by manojjonam10** [comment]
Thank you, we got it figured out. :)
