### ISSUE TITLE
API Connection Error

### ISSUE THREAD

**Issue by kkarabiber-s** [metafloor/bwip-js#204]
We've been using the online API for some time and a few minutes ago it started to return connection errors. 

When we try to connect to http://bwipjs-api.metafloor.com/?bcid=code128&text=PGR-V-1998 says the site cannot be reached.

**Comment by mxgr59** [comment]
Hello, I have the same problem, the site cannot be reached

**Comment by koenm** [comment]
Please transition your use of the API to the new URL:

https://bwip-js.herokuapp.com/

**Comment by metafloor** [comment]
Currently cannot debug what is going wrong with the AWS version of the API.  Server starts up and immediately goes to 100% CPU.   It appears something has gone wrong with the certificate handling module (greenlock).  Trying to investigate but that is a complex set of dependencies....

For now, use the backup bwip-js.herokuapp.com link.

**Comment by metafloor** [comment]
Server appears to be back to normal.  The logs show the certificate renewal was encountering network timeouts that now appear to be resolved.
