### ISSUE TITLE
NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by trisghosh** [metafloor/bwip-js#206]
Hi Team,

I was using your API to show the BARCODE, suddenly it stops working, and found that the certificate is invalid at your server. I tested with your sample URL i.e. https://bwipjs-api.metafloor.com in it shows that issue too. 

**This server could not prove that it is bwipjs-api.metafloor.com; its security certificate expired 2 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Sunday, May 9, 2021. Does that look right? If not, you should correct your system's clock and then refresh this page.**

Thanks

**Comment by metafloor** [comment]
Looks like the greenlock module is having trouble with one of the certs.  Switch over to one of the alternates until I can get it reset:

https://api-bwipjs.metafloor.com/
https://bwip-js.herokuapp.com/

**Comment by metafloor** [comment]
The bwipjs-api cert has been re-established.
