### ISSUE TITLE
support styled qrcode with logo?

### ISSUE THREAD

**Issue by bluelovers** [metafloor/bwip-js#207]
support styled qrcode with logo?

**Comment by metafloor** [comment]
This project is primarily a translation of postscript to javascript, so it only implements the symbol generation that BWIPP supports.

Adding a logo to a qrcode would be better implemented as a package that uses bwip-js to generate the symbol and then overwrites the center area with the logo.  That will require a significant bit of custom logic.  The symbol must be constructed with sufficient size and eclevel to support the loss of data; and then there is the scaling factor of the symbol to account for.
