### ISSUE TITLE
BWIP-JS ERROR: array: underflow

### ISSUE THREAD

**Issue by danielflippance** [metafloor/bwip-js#21]
Hi there,

I'm seeing an array underflow error occasionally when rendering code128 barcodes: 
BWIP-JS ERROR: array: underflow

My barcode is a 9 digit number and after the error occurs, if I run the code again it success so the problem appears to not be related to the code I'm using. Bwip-js is version 0.14.2. The code is:

```
var bwipjs = require('bwip-js');
...
this.generateBarCode(390223713, function(buffer){ ...});
...  
exports.generateBarCode = function(codeInt, callback) {
    console.log("+ pdfController.generateBarCode(%d)", codeInt);
    var codeString = (""+codeInt).trim();
    bwipjs.toBuffer({
            bcid:           'code128',  // Barcode type 
            text:           codeString, // Text to encode 
            scale:          2,          // 3x scaling factor 
            height:         5,          // Bar height, in millimeters 
            includetext:    false,      // Show human-readable text 
    }, function (err, buffer) {
        if (err) {
            handleErr(err);
            callback(null);
        } else { 
            callback(buffer);
        }
    });
}
```

Stack trace:

```
at /app/node_modules/bwip-js/node-bwipjs:151:4 
at BWIPJS.call (bwip.js:416:4) 
at Function.module.exports.toBuffer (/app/node_modules/bwip-js/node-bwipjs:149:5) 
```

My server memory is running at about 60% availability so plenty of that.

**Comment by metafloor** [comment]
The array underflow error should be impossible to trip into.  So congratulations are in order, I guess.  In postscript, arrays can be built on the stack, then copied into an array structure.  A special marker is placed on the stack to indicate the end of the array data and when not found, an underflow error occurs.  I cannot begin to fathom how your particular code is hitting this.

Below is a new `code128.js`, which wraps the `"array: underflow"` message with `new Error("array: underflow")`.  That should add the line number where the error is actually occurring to the stack dump you are showing. 

[code128.txt](https://github.com/metafloor/bwip-js/files/41903/code128.txt)

github does not allow uploading .js files so the file has been renamed to `code128.txt`.  Copy the file to the `bwipp/code128.js` under the main `bwip-js`

Please respond with the new stack dump when the error next occurs.  Thanks.

**Comment by danielflippance** [comment]
Thanks for the fast response @metafloor. I've added the code to my site and am monitoring for a repetition of the issue. It does seem to be related to periods of heavy use on the system, so I'll look into getting finer grained details about system resources at the time the error occurs.

**Comment by danielflippance** [comment]
We had a flood of these errors today, however I'm no longer seeing an exception. I see that the stack trace I noted previously was actually caused by an exception thrown due to not handling the empty buffer returned so it looks like the error doesn't throw an exception but returns "BWIP-JS ERROR: array: underflow" in err in the callback. 

I've added some more logging to see if I can get the more info and perhaps the stack trace. I also added a retry if bwipjs.toBuffer fails but that seems to not really help. 

The issue is definitely related to resources as today I saw about 50 of these errors within 15 minutes so I restarted my 2 dynos and after that the problem disappeared (I'm running on Heroku, 2 dynos at 1Gb RAM each). Memory still seemed to be available, but I've added some settings to run the garbage collector more often in case that's causing the issue and the memory peak is too short to show up in my reports.

**Comment by danielflippance** [comment]
I changed the Node runtime to run the garbage collector more often but I'm still seeing the underflow errors.

    node --optimize_for_size --max_old_space_size=920 --gc_interval=100 server.js

There is definitely no exception thrown, just "BWIP-JS ERROR: array: underflow" in err in the callback

**Comment by danielflippance** [comment]
I added some debug comments to every instance of the underflow error in code128.js and recorded the name of the function it came from like this:  `throw new Error("Array: underflow - $f37")`. For those instances in the main body of that rather than in a child function I wrote `Main.1`, `Main.2`  etc 

The error seems to always be coming out on line `2385` of code128.js:

	2375    var t = this.stk.splice(i+1, this.ptr-1-i);
	2376    this.ptr = i;
	2377    this.stk[this.ptr++]=BWIPJS.psarray(t);
	2378    this.stk[this.ptr++]=Infinity;
	2379    var t=this.dstk.get("fn2");
	2380    if (t instanceof Function) t.call(this); else this.stk[this.ptr++]=t;
	2381    var t=this.dstk.get("fn2");
	2382    if (t instanceof Function) t.call(this); else this.stk[this.ptr++]=t;
	2383    this.stk[this.ptr++]=BWIPJS.psstring("97");
	2384    for (var i = this.ptr-1; i >= 0 && this.stk[i] !== Infinity; i--) ;
	2385    if (i < 0) throw new Error("array: underflow - Main.2");      //This is the error I see
	2386    var t = this.stk.splice(i+1, this.ptr-1-i);
	2387    this.ptr = i;
	2388    this.stk[this.ptr++]=BWIPJS.psarray(t);
	2389    this.stk[this.ptr++]=Infinity;
	2390    var t=this.dstk.get("sft");
	2391    if (t instanceof Function) t.call(this); else this.stk[this.ptr++]=t;

**Comment by metafloor** [comment]
Please download the new version 1.0 release.  The cross-compiled code structure is completely changed.  Please let me know if you still see this issue.

**Comment by metafloor** [comment]
Closing this as the issue appears inactive.
