### ISSUE TITLE
demo website GS1 datamatrix fails to create barcode

### ISSUE THREAD

**Issue by Masber** [metafloor/bwip-js#211]
I am testing bwip-js web demo (http://bwip-js.metafloor.com/demo/demo.html) with he following text:

(01)99312650999998(91)111JD585283001000931507(420)2217(8008)210431221345

and I am getting the error below:

Error: bwipp.GS1badDay: AI 8008: Invalid day of month

and funny enough this one works:

(01)99312650999998(91)111JD585283001000931507(420)2217(8008)210430221345

The only difference is the date from 31-04-2021 to 30-04-2021

The original date is correct but I don't understand why the demo website gives me an error?

thank you

**Comment by metafloor** [comment]
There are only 30 days in April so the error message is correct.
