### ISSUE TITLE
Using NPM to install bwip-js only installs version 2.1.3

### ISSUE THREAD

**Issue by barrett316** [metafloor/bwip-js#216]
I have tried removing bwip-js, and it reinstalls 2.1.3. Is there something I'm doing wrong to get it updated to the latest release?

**Comment by metafloor** [comment]
I suspect you have something like `"bwip-js" : "^2.x.x"` in the dependencies in your `package.json`.  The caret `^` means maintain compatibility with the specified major version.  Just change it to `"^3.0.1"` and then `npm update`.

**Comment by barrett316** [comment]
That wasn't the resolution to the issue. There wasn't a dependency. I'm not sure if this matters or not, but it's running on macOS.

**Comment by barrett316** [comment]
I resolved the issue by using the "@3.0.1" tag at the end of "npm install bwip-js"
