### ISSUE TITLE
toBuffer is not a function

### ISSUE THREAD

**Issue by kvalium** [metafloor/bwip-js#221]
I want to retrieve base64 barcode image from a string, here is the code I'm using: 

```ts
import bwipjs from "bwip-js";

export const textToBarCodeBase64 = async (text: string): Promise<Buffer> =>
  bwipjs.toBuffer({ text, bcid: "code128" });

(async () => {
  const b64 = await textToBarCodeBase64("code me");
  console.log({ b64 });
})();
```

And the related Code Sandbox: https://codesandbox.io/s/objective-sinoussi-v2i96?file=/src/index.ts

I've the following error: `bwip_js_1.default.toBuffer is not a function`

What's wrong?

Thanks

**Comment by metafloor** [comment]
`toBuffer()` is a node-js method.  You need to use `toCanvas()` on the browser.  The project readme provides the following code to get a base64 string:

```
let canvas = document.createElement('canvas');
try {
    bwipjs.toCanvas(canvas, options);
    document.getElementById('my-img').src = canvas.toDataURL('image/png');
} catch (e) {
    // `e` may be a string or Error object
}
```
