### ISSUE TITLE
margins between barcode & barcode text

### ISSUE THREAD

**Issue by willyou** [metafloor/bwip-js#225]
Hi there, 
I checked the docs but couldn't find information on margins between barcode & barcode text.
Are there any options or workaround that I can use?
is it because of some standards or guidelines for barcodes?

I want to adjust the redline space.
thanks.
<img width="1547" alt="Screen Shot 2021-11-01 at 10 04 52 PM" src="https://user-images.githubusercontent.com/3471779/139684980-1414110c-ad3f-4ca0-8255-173f88f4f243.png">

**Comment by metafloor** [comment]
Use `textyoffset`, e.g.  https://api-bwipjs.metafloor.com/?bcid=code128&text=1234567890&includetext&textyoffset=10

**Comment by willyou** [comment]
thanks for getting me back so quickly!
