### ISSUE TITLE
Scanning with alphanumeric

### ISSUE THREAD

**Issue by manojjonam10** [metafloor/bwip-js#226]
I am having  issue with scanning barcode generated from bwipjs. Numeric or character only values scan good. But alphanumeric values are not scanning well all the time. Is there anyway to force the bwipjs to print as code128 A instead of auto when using alphanumeric values

**Comment by metafloor** [comment]
Please provide an example of the barcode text and resulting image that is not scanning correctly.

**Comment by manojjonam10** [comment]
Sorry the issue with scanner. New scanner scans perfect
