### ISSUE TITLE
How to use 'https' instead of 'http' server

### ISSUE THREAD

**Issue by barrett316** [metafloor/bwip-js#227]
This is probably just lack of skill on my side, but I can't figure out how to host the node server as https instead of its default http. Any guidance would be greatly appreciated. 

Thanks

**Comment by metafloor** [comment]
Take a look at [greenlock](https://www.npmjs.com/package/greenlock).  It provides a plug-and-play platform for using [let's encrypt](https://letsencrypt.org/) issued certificates, including auto-renewal.  Your server must be public facing for greenlock/letsencrypt to work.
