### ISSUE TITLE
Problem scanning code128

### ISSUE THREAD

**Issue by pogrever** [metafloor/bwip-js#229]
I've been using bwip to generate barcodes for a while.  Noticed that my version was old (2.0.12) and updated to 3.0.4.  Started having trouble scanning some barcodes.  Comparing some test output between old and new versions I noticed the following:

1. Some of the gaps between bars is much smaller (especially at the end of the code)
2. I color the background area and now some of the barcodes extend out a little past the end of the area specified (old version did not).

Note:  Backround color and rotation are done separately using PDF library - not asking bwip to do it.

See attached PDF's for test output differences between old and new.

The spacing issue is making it difficult (and often impossible) for some scanners to read the new barcodes (they are able to read the ones produced by the earlier version easily).

[old-2.0.12.pdf](https://github.com/metafloor/bwip-js/files/8092178/old-2.0.12.pdf)
[new-3.0.4.pdf](https://github.com/metafloor/bwip-js/files/8092194/new-3.0.4.pdf)

.

**Comment by metafloor** [comment]
I am currently traveling (on holiday) for the next 2 weeks but will try to help.  First, please post the code you use to generate the bar codes.  That is critical to understanding what might have changed.

**Comment by metafloor** [comment]
Did you get this figured out? From your logs, it looks like a simple `floor()` would have fixed it in your drawing object.
