### ISSUE TITLE
Generate barcode code128

### ISSUE THREAD

**Issue by dannyto** [metafloor/bwip-js#23]
Hi there!

When I use your code to generate barcode code128 it take about 300ms, but when i use 'bwip' module it take about 40ms. Can you make it generate faster?

Thankz for help!

**Comment by metafloor** [comment]
If the old bwip module is something based on an old version of bwip-js, then I suspect it will be the PNG image compression that is adding overhead.  The original bwip-js used a pure-javascript PNG encoder without compression.  The latest versions use node's zlib module to compress the PNG image data.  The actual bar code rendering logic has not changed.

The above is just a guess. You would need to time the rendering and png-encoding phases to be sure. 

If you would like to add a nul-compression option to bwip-js, I would be happy to take the pull request.

**Comment by dannyto** [comment]
Yes, please!

**Comment by metafloor** [comment]
Adding nul-compression to the PNG images is not a priority.  We use bwip-js in very demanding production environments without any performance issues, including code128 for warehousing data sheets containing many dozens of serial numbers.  

If you would like to add nul-compression to the code, than I will accept the pull request.  Otherwise, I consider the PNG image generation to be sufficient as is.

**Comment by dannyto** [comment]
Yes, please! Because I want to generate a lot of barcode with less time.

Thankz for help!

**Comment by metafloor** [comment]
You are not reading my comments very carefully.  I am not interested in adding nul-compression to the PNG images as I do not see the need.  I consider 300ms to be acceptable performance.  Not great, but acceptable.  On the rhcloud public API service, average response time for all bar code types is around 160ms.

You have also provided no information on how you are using bwip-js, so there is no way for me to determine whether the compression or some other functionality is to blame for the overhead.  The extra time could be coming from:

- The postscript-emulated bar code rendering.
- The font rendering using freetype.  This is harder to profile as it is part of the bar code rendering.
- The PNG image generation.

If you want my help on this issue (and I am willing to help), you need to do some more work.  

- Tell me in detail how you are using bwip-js, including examples of the bar code parameters and text.  

- Go into node-bwipjs and time the different phases of the bar code image generation.  Below is the replacement code that will give the times:

```javascript
    var ts0 = Date.now();
    bw.call(bcid, function(e) {
        if (e) {
            callback('BWIP-JS ERROR: ' + e);
        } else {
            var ts1 = Date.now();
            //bw.bitmap().getPNG(rot, callback);
            bw.bitmap().getPNG(rot, function(e,v) { 
                     var ts2 = Date.now();
                     console.log('postscript: ' + (ts1-ts0) + ' msec, ' +
                                        'image: ' + (ts2-ts1) + ' msec, ' +
                                        'total: ' + (ts2-ts0) + ' msec');
                     callback(e,v);
                });
        }
    });
```

- Profile the requests with and without human readable text (BWIPP option `includetext`).  That will tell us if the font rendering is part of the problem.  Make at least 20 requests with and without the `includetext` option.

Let me know the results.

**Comment by dannyto** [comment]
I have to make a printer to print barcode, data will increase (1 - 1000000), so i need to generate barcode a bit faster to improve the printer.
I have tested bwip-js.

Result test:
with includetext
postscript: 523 msec, image: 159 msec, total: 682 msec
postscript: 467 msec, image: 163 msec, total: 630 msec
postscript: 401 msec, image: 128 msec, total: 529 msec
postscript: 301 msec, image: 101 msec, total: 402 msec
postscript: 432 msec, image: 149 msec, total: 581 msec
postscript: 436 msec, image: 149 msec, total: 585 msec
postscript: 396 msec, image: 130 msec, total: 526 msec
postscript: 504 msec, image: 118 msec, total: 622 msec
postscript: 595 msec, image: 104 msec, total: 699 msec
postscript: 522 msec, image: 129 msec, total: 651 msec

without includetext
postscript: 216 msec, image: 106 msec, total: 322 msec
postscript: 204 msec, image: 106 msec, total: 310 msec
postscript: 210 msec, image: 128 msec, total: 338 msec
postscript: 182 msec, image: 113 msec, total: 295 msec
postscript: 176 msec, image: 95 msec, total: 271 msec
postscript: 221 msec, image: 117 msec, total: 338 msec
postscript: 233 msec, image: 128 msec, total: 361 msec
postscript: 179 msec, image: 143 msec, total: 322 msec
postscript: 188 msec, image: 114 msec, total: 302 msec
postscript: 212 msec, image: 90 msec, total: 302 msec

**Comment by metafloor** [comment]
Those results are fairly unequivocal.  It appears the freetype module is adding significant overhead to the bar code generation.  That is not something that can be easily fixed.  freetype has built-in cache functionality that was disabled for the emscripten build.  I may have time next week to enable the caching but that is not certain.

For now, you can either use an old version of bwip-js or live with the current performance.

Let's keep this issue open until the freetype caching has been added to bwip-js.

One additional item:  You never showed me the bar code parameters being passed to bwip-js.  Please add a couple of example URLs to this issue.

**Comment by metafloor** [comment]
Version 1.0 is now out with big gains in performance.  Please download and let me know if the times are better.  There are still some caching improvements to be made, so I am curious how the new code will fare.

**Comment by metafloor** [comment]
Closing this as the issue is inactive.
