### ISSUE TITLE
QRCode, DataMatrix, Aztec barcodes changing aspect ratio

### ISSUE THREAD

**Issue by Jack-Gitter** [metafloor/bwip-js#230]
Hi I'm attempting to use the library for web development as described here: 

```
let canvas = document.createElement('canvas');

try {
    bwipjs.toCanvas(canvas, options);
    document.getElementById('my-img').src = canvas.toDataURL('image/png');
} catch (e) {
    // `e` may be a string or Error object
}
```
my options are as follows: 

```
bcid: barcodeType, // Barcode type
        text: text, // Text to encode
        scale: 5, // 1.5x scaling factor
        height: 10, // Bar height, in millimeters
        includetext: true, // Show human-readable text'
        textxalign: "center" // Always good to set this
```

the text is a variable that corresponds to a string, and as that string grows the aspect ratio of the aforementioned barcodes changes from square to rectangular. Is there any way to constrain this to keep it rectangular?

**Comment by metafloor** [comment]
I suspect that how you are displaying the barcode images on the web page is causing the distortion (scaling). Please post some text strings that demonstrate this behavior.

**Comment by Jack-Gitter** [comment]
really any string that’s longer than 16 characters is seeming to cause the issue, the y axis shrinks and the x axis grows

**Comment by metafloor** [comment]
Remove the `height` parameter from your options.  That is primarily for setting bar height in 1d symbols.  Using it with 2D symbols is causing the distortion.
