### ISSUE TITLE
Usage of bwip-js in Typescript

### ISSUE THREAD

**Issue by manjari09** [metafloor/bwip-js#231]
Hello Team,

I am trying to use bwip-js in my Typescript code (Angular) whose main purpose is to generate PDF file and place dynamically generated data-matrix into PDF.  
I am getting below error - 
`ERROR Error: Uncaught (in promise): TypeError: bwip_js__WEBPACK_IMPORTED_MODULE_5___default.a.toBuffer is not a function
TypeError: bwip_js__WEBPACK_IMPORTED_MODULE_5___default.a.toBuffer is not a function`

Could you please help me in getting this resolved.

**Comment by metafloor** [comment]
webpack is importing the browser module - `toBuffer()` is only available in nodejs.  Use the `toCanvas()` browser method instead.  From the readme:

```
let canvas = document.createElement('canvas');
try {
    bwipjs.toCanvas(canvas, options);
    document.getElementById('my-img').src = canvas.toDataURL('image/png');
} catch (e) {
    // `e` may be a string or Error object
}
```

That gives you a data-url that can either be set to an image (as shown above) or converted to a `Uint8Array` if that is more useful for generating a pdf.

**Comment by manjari09** [comment]
Thank you so much. Issue got resolved. :)
