### ISSUE TITLE
Characters not showing up as themselves with includetext:true

### ISSUE THREAD

**Issue by Jack-Gitter** [metafloor/bwip-js#232]
I'm trying to display the text that corresponds to the barcode generation using includetext:true, although when the user types characters such as ? or < or even a space, the values come up as %3F, %3C ect. Is there any option to easily fix this?

**Comment by metafloor** [comment]
How about some sample source code or other example that shows how you are using bwip-js?  Sounds like you might be using the public API giving the url-encoded characters, but no way to tell....
