### ISSUE TITLE
Generating a UPC-A barcode seems to allow 7 digits

### ISSUE THREAD

**Issue by Jack-Gitter** [metafloor/bwip-js#234]
Hi I'm using Bwip-js in the browser as follows: 

```
const c = document.createElement("canvas");
let canvas = bwipjs.toCanvas(c, {
     bcid: barcodeType, // Barcode type
     text: text, // Text to encode
     scale: 7, // 7x scaling factor
     includetext: true, // Show human-readable text'
     textxalign: "center",// Always good to set this
     backgroundcolor: 'ffffff'
       });
const img = document.getElementById("..."); 
const imgurl = canvas.toDataURL("image/png");
img.src = imgurl;
```
If using the barcodeType of upca and entering in a 7 digit number, it seems to generate a barcode despite upca barcodes needing 11 digits. Is it possibly converting it into a upce barcode? Additionally is there a way to lock this so it only generates upca?

**Comment by terryburton** [comment]
It is generating a UPC-A barcode, however it is accepting the input as a zero-compressed GTIN-12 and making the necessary conversions.

UPC-As are a carrier for GTIN-12s. GTIN-12s have a zero-compressed representation, which is intended to allow certain numbers to fit into an UPC-E, as you've determined. So what the library is doing is correct and "flexible", albeit surprising.
