### ISSUE TITLE
Using control characters in barcode

### ISSUE THREAD

**Issue by Jack-Gitter** [metafloor/bwip-js#235]
Hi I'm currently using bwipjs as follows: 

```
const c = document.createElement("canvas");
        let canvas = bwipjs.toCanvas(c, {
            bcid: type, 
            text: text, 
            scale: size,
            includetext: true, 
            textxalign: "center", 
            backgroundcolor: 'ffffff', 
        });

    img = document.getElementById('hello');
    const uri = canvas.toDataURL("image/png");
     img.src = uri;
```
I want to include support for control characters in the text field in my barcode. Is there an option for this? I couldn't seem to find anything in the docs

**Comment by Jack-Gitter** [comment]
more specifically, control characters that would implement functionality such as these: https://www.activebarcode.com/barcode/control-characters.html

**Comment by terryburton** [comment]
We're such characters are supported by the symbology they can be access via the `parse` option: https://github.com/bwipp/postscriptbarcode/wiki/Input-Processing#parse

Note well: https://stackoverflow.com/a/30904203/2568535

**Comment by Jack-Gitter** [comment]
> 

Thanks for the quick response, where do I include this parse option though in my use case?

**Comment by terryburton** [comment]
Maybe adding `parse: true` to the options array.

I'll leave @metafloor to answer authoritatively for the BWIP-JS API.

**Comment by Jack-Gitter** [comment]
thanks, that did the trick. Closing the thread
