### ISSUE TITLE
Text Parsing with Null Control Character exhibits strange behavior

### ISSUE THREAD

**Issue by Jack-Gitter** [metafloor/bwip-js#236]
Hi I am using bwipjs as follows: 

```
const c = document.createElement("canvas");
        let canvas = bwipjs.toCanvas(c, {
            parse: true,
            bcid: type, 
            text: text, 
            scale: size,
            includetext: true, 
            textxalign: "center", 
            backgroundcolor: 'ffffff', 
        });

    img = document.getElementById('hello');
    const uri = canvas.toDataURL("image/png");
    img.src = uri;
```

When the text input has a null character and then any text proceeding afterwards, the displayed text gets cut off and only displays what is before the null character. For example, when text = hi^000hello, the displayed text is only rendered as "hi" , although the barcode itself seems to change based on characters entered in after ^000 (For example, barcodes where text = hi^000hi and text = hi^000hello are different) My confusion stems from the fact that if the text is being processed to change the barcode, then why is it not being displayed as well?

**Comment by metafloor** [comment]
v3.0.5 fixes this issue.
