### ISSUE TITLE
Certain ^NNN byte patterns cause encoding to fail

### ISSUE THREAD

**Issue by Spatchy** [metafloor/bwip-js#237]
I have some code that is supposed to encode 15 bytes of hexadecimal data as a microQR code:

```javascript
function hexToNNN(data) { // converts each hex byte to ^NNN notation
  return data.match(/.{1,2}/g).map(i => "^" + parseInt(i, 16).toString(10).padStart(3, "0")).join("")
}

function doEncode(data) {
  bwipjs.toBuffer({
    bcid: "microqrcode",
    text: hexToNNN(data),
    scale: 1,
    eclevel: "L",
    parse: true // Tell bwip to parse NNN escape codes
    }, function (err, png) {
      if (err) {
        throw err
      } else {
        fs.writeFileSync("out/" + data + ".png", png)
        console.log("success")
      }
    });
}
```
This code works perfectly for some data but will fail for others.

Take for example the hex string `doEncode("4b3900000000000000000000000000")`
This evaluates to the NNN string `^075^057^000^000^000^000^000^000^000^000^000^000^000^000^000`
or simply the text 'K9' followed by 13 `NULL` bytes.
This will fail and throw `Error: bwipp.qrcodeNoValidSymbol: No valid symbol available`

However `doEncode("3b3900000000000000000000000000")` and `doEncode("4b3a00000000000000000000000000")` both work fine and generate valid microQR codes, showing that neither byte is causing issues on its own, but the combination of the two is causing issues.

What's causing this?

Also, is there a better way to encode raw bytes than this? I don't see any reference to a binary mode in the docs.

**Comment by terryburton** [comment]
In the case of a Micro QR Code starting Alphanumeric before Numeric before Byte, the codeword optimisation isn't optimal and results in a starting mode selection of Alphanumeric rather than Byte:

https://github.com/bwipp/postscriptbarcode/blob/7b9ec9818232032958e82d75b818b19f4b44c627/src/qrcode.ps#L468

It will likely be a while before I can address this.

**Comment by Spatchy** [comment]
> In the case of a Micro QR Code starting Alphanumeric before Numeric before Byte, the codeword optimisation isn't optimal and results in a starting mode selection of Alphanumeric rather than Byte:
> 
> https://github.com/bwipp/postscriptbarcode/blob/7b9ec9818232032958e82d75b818b19f4b44c627/src/qrcode.ps#L468
> 
> It will likely be a while before I can address this.

Thanks very much for your quick response! In the mean time, is there any trick or workaround to be able to force byte mode, or any other technique to store those 15 bytes you could recommend? Since I'm also designing the system that needs to read the micro QR code, I don't require any specific format or data-structure (as long as the micro QR code itself is valid and in-spec), simply a way of storing 15 bytes such that I can retrieve them.

**Comment by semireg** [comment]
I just had a user report "No valid symbol available" and I had to dig to find that it was basically "maximum length exceeded." Perhaps the error message can be made a bit clearer, too? Cheers, all.

**Comment by terryburton** [comment]
Messages updated: https://github.com/bwipp/postscriptbarcode/commit/b24f56125158d0c79b14d63cf6dd1ec738e53c1c

They'll be included in a future release.

**Comment by metafloor** [comment]
I am going to close this out as v3.2.0 has the most recent BWIPP enhancements.
