### ISSUE TITLE
rectangular micro qr code generation issue

### ISSUE THREAD

**Issue by DavidePlessi** [metafloor/bwip-js#239]
I have some issue generating a rectangularmicroqrcode:

```js
const getBarcodeBuffer = async (code, type, args) => {
  return await bwipJs.toBuffer({
    bcid: 'rectangularmicroqrcode',
    text: '0012075542420220309',
    scale: 3,
    backgroundcolor: "ffffff",
    padding: 5
  })
}
```

It returns me this error:
```
TypeError: Cannot read properties of undefined (reading 'length')
    at bwipp_qrcode (C:\Progetti\Attractive\barcode-generator\node_modules\bwip-js\dist\bwip-js-node.js:21373:33)
    at bwipp_rectangularmicroqrcode (C:\Progetti\Attractive\barcode-generator\node_modules\bwip-js\dist\bwip-js-node.js:22920:5)
    at bwipp_encode (C:\Progetti\Attractive\barcode-generator\node_modules\bwip-js\dist\bwip-js-node.js:35158:5)
    at _Render (C:\Progetti\Attractive\barcode-generator\node_modules\bwip-js\dist\bwip-js-node.js:231:5)
    at Object.ToBuffer [as toBuffer] (C:\Progetti\Attractive\barcode-generator\node_modules\bwip-js\dist\bwip-js-node.js:90:10)
    at getBarcodeBuffer (C:\Progetti\Attractive\barcode-generator\app.js:22:23)
```

What's causing this?
Thanks

**Comment by DavidePlessi** [comment]
I think the problem is caused by an unset property `$1.verset`.
Looking at the function bwipp_qrcode called by bwipp_rectangularmicroqrcode, this property is set when $1.format value is "full" or "micro" but in this case it's value is 'rmqr':
bwip-js-node.js:21358
```
...
    } else { //#18599
        if ($eq($1.format, "full")) { //#18598
            $1.verset = $a([$1.v1to9, $1.v10to26, $1.v27to40]); //#18598
        } //#18598
        if ($eq($1.format, "micro")) { //#18599
            $1.verset = $a([$1.vM1, $1.vM2, $1.vM3, $1.vM4]); //#18599
        } //#18599
    } //#18599
    $k[$j++] = Infinity; //#18604
    for (var _8e = 0, _8f = 39; _8e < _8f; _8e++) { //#18604
        $k[$j++] = -1; //#18604
    } //#18604
    $1.msgbits = $a(); //#18604
    $1.e = 10000; //#18605
    var _8h = $1.verset; //#18606
    for (var _8i = 0, _8j = _8h.length; _8i < _8j; _8i++) { //#18741
...
```

**Comment by terryburton** [comment]
> I just checked this against the BWIPP online demo and it throws an error as well. I think you need to manually specify the version in the options. For example, `version:'R17x139'`.

Correct. The symbol capacities for the different rMQR versions overlap and there is currently no guidance in the draft specification for what the default aspect ratio should be.

In practise, for the rectangular symbologies (such as rMQR and DMRE) the user is looking to render an image within a predetermined space for which specifying the symbol version is a practical necessity.

**Comment by metafloor** [comment]
I think this issue is resolved as "functions as expected".
