### ISSUE TITLE
Help understanding codabar standards

### ISSUE THREAD

**Issue by Jack-Gitter** [metafloor/bwip-js#240]
Hi, I'm currently trying to mimic the codabar functionality that can be found here: 

https://barcodeapi.org/index.html#auto

Right now I'm using codabar in a web environment like so : 

```
const c = document.createElement("canvas");
        let canvas = bwipjs.toCanvas(c, {
            bcid: type, 
            text: text, 
            scale: size,
            includetext: true, 
            textxalign: "center", 
            backgroundcolor: 'ffffff', 
        });

    img = document.getElementById('hello');
    const uri = canvas.toDataURL("image/png");
    img.src = uri;
```

The codabar barcodes generated by the webpage linked above seem to differ from the ones generated by bwipjs regardless of what combination of  start and stop characters that I use. I also noticed that the codabar generated by the website linked above has less bars than the one generated by bwipjs. I've been doing some research about the variations of codabar and understand that bwipjs uses rationalized codabar, and was wondering if this rationalized codabar could be converted to the standard of the other barcode. (and maybe what standard that barcode is following)

**Comment by metafloor** [comment]
Check the BWIPP documentation.  That is the source for all symbologies and options supported by bwip-js.
