### ISSUE TITLE
importing single formats into angular

### ISSUE THREAD

**Issue by wiemax1093** [metafloor/bwip-js#241]
Hey, just upgraded to >3.0 and read that there is now the possibility to import single codes, to reduce application size. Using Angular 13 and just tried it out: 
Old code part: 
` 
import bwip from 'bwip-js';

let canvas = bwip.toCanvas('QR', {
              bcid:        'datamatrix',       // Barcode type
              text:        pn,    // Text to encode
              scale:       1,               // 3x scaling factor
              height:      50,              // Bar height, in millimeters
              width:       50,
              includetext: false,            // Show human-readable text
              textxalign:  'center',        // Always good to set this
              barcolor: '000000'
            });`

As far as I understood from the docs i "just" changed it into:
`import datamatrix from 'bwip-js';

let canvas = datamatrix('QR', {
              bcid:        'datamatrix',       // Barcode type
              text:        pn,    // Text to encode
              scale:       1,               // 3x scaling factor
              height:      50,              // Bar height, in millimeters
              width:       50,
              includetext: false,            // Show human-readable text
              textxalign:  'center',        // Always good to set this
              barcolor: '000000'
            });`

Brackets in the import do not work (...not a exportet member...). When looking for the expected input vars it shows me:
`(alias) datamatrix(req: IncomingMessage, res: ServerResponse, opts?: datamatrix.ToBufferOptions | undefined): void (+1 overload)` which tbh does not look right to me. Am I overlooking something or does it just not work in angular? If I load them all and use the "toCanvas" it works flawless.

**Comment by metafloor** [comment]
If you look in `dist/bwip-js.mjs` (the ES6 module for the browser), you will see the export:

```
export function datamatrix(opts,cvs) { return _ToCanvas(bwipp_datamatrix,opts,cvs); };
```

So I suspect the typescript compiler is using the wrong type definitions, or bringing in the wrong module.

**Comment by wiemax1093** [comment]
Thx for the answer, thats also my suspicion but i was not able to load the proper one yet (maybe i have time to check on how to use the proper one)
