### ISSUE TITLE
why qrcode parameter version not valid?

### ISSUE THREAD

**Issue by yingfengchen** [metafloor/bwip-js#246]
![image](https://user-images.githubusercontent.com/20177121/160127048-8156e7d9-c43e-4492-b8a7-209cb0fb5826.png)

**Comment by metafloor** [comment]
Please provide the text that you used for the barcode - it is not fully visible in the image.

**Comment by yingfengchen** [comment]
![image](https://user-images.githubusercontent.com/20177121/160131352-98343dad-2942-45cf-9532-f1e314d77150.png)
parameter version cause error!
if any other params I should set?

**Comment by yingfengchen** [comment]
my bwip.js is 3.0.4 the newest version, please give me some help
no whether the text, the version parameter is always not valid

**Comment by metafloor** [comment]
I am not able to reproduce the issue.  Please provide the source code for the call into bwip-js, including all of the parameter values (not an image - the actual text).

**Comment by metafloor** [comment]
Wait, I think I have an idea.  Pass the version as a string:  `version:'8'`.  The BWIPP code expects all of its options to be strings, mostly.

**Comment by yingfengchen** [comment]
ok thanks a log
