### ISSUE TITLE
why bwipjs.toCanvas(canvas, config); takes a lot time   may be 3second more?  but http://bwip-js.metafloor.com/demo/demo.html the same text is so fast. what's the difference?

### ISSUE THREAD

**Issue by yingfengchen** [metafloor/bwip-js#247]
text = '231311164258\n231311177794\n231311173451\n231311179916\n231311179815\n231311180927\n231311181937\n231311180523\n231311182139\n231311184563\n231311182543\n231311185876\n231311185573\n231311186078\n231311187593\n231311187997\n231311187896\n231311187795\n231311188098\n231311187694\n231311164359\n231311167793\n231311179209\n231311173653\n231311186381\n231311189008\n231311189412\n231311189816\n231311190625\n231311191130\n231311191332\n231311191231\n231311191433\n231311190726\n231311188604\n231311192140\n231311192645\n231311191837\n231311191736\n231311192039\n231311193049\n231311193352\n231311193453\n231311194160\n231311194564\n231311194261\n231311194766\n231311194867\n231311164258\n231311177794\n231311173451\n231311179916\n231311179815\n231311180927\n231311181937\n231311180523\n231311182139\n231311184563\n231311182543\n231311185876\n231311185573\n231311186078\n231311187593\n231311187997\n231311187896\n231311187795\n231311188098\n231311187694\n231311164359\n231311167793\n231311179209\n231311173653\n231311186381\n231311189008\n231311189412\n231311189816\n231311190625\n231311191130\n231311191332\n231311191231\n231311191433\n231311190726\n231311188604\n231311192140\n231311192645\n231311191837\n231311191736\n231311192039\n231311193049\n231311193352\n231311193453\n231311194160\n231311194564\n231311194261\n231311194766\n231311194867'

**Comment by yingfengchen** [comment]
![image](https://user-images.githubusercontent.com/20177121/160266461-43a61edc-b893-4614-b970-d0d759072d4c.png)

**Comment by yingfengchen** [comment]
in bwip 
![image](https://user-images.githubusercontent.com/20177121/160266488-d9fdafc7-d013-42d0-954f-14a80155ba57.png)

**Comment by metafloor** [comment]
Please post _code_ that reproduces the problem.

**Comment by yingfengchen** [comment]
let canvas = document.createElement('canvas');
const config = {
	  backgroundcolor: "ffffff"
	  barcolor: "000000"
	  bcid: "qrcode"
	  eclevel: "M"
	  format: "full"
	  paddingbottom: 0
	  paddingleft: 0
	  paddingright: 0
	  paddingtop: 0
	  rotate: "N"
	  scaleX: 1
	  scaleY: 1
	  text: "231311164258\n231311177794\n231311173451\n231311179916\n231311179815\n231311180927\n231311181937\n231311180523\n231311182139\n231311184563\n231311182543\n231311185876\n231311185573\n231311186078\n231311187593\n231311187997\n231311187896\n231311187795\n231311188098\n231311187694\n231311164359\n231311167793\n231311179209\n231311173653\n231311186381\n231311189008\n231311189412\n231311189816\n231311190625\n231311191130\n231311191332\n231311191231\n231311191433\n231311190726\n231311188604\n231311192140\n231311192645\n231311191837\n231311191736\n231311192039\n231311193049\n231311193352\n231311193453\n231311194160\n231311194564\n231311194261\n231311194766\n231311194867\n231311164258\n231311177794\n231311173451\n231311179916\n231311179815\n231311180927\n231311181937\n231311180523\n231311182139\n231311184563\n231311182543\n231311185876\n231311185573\n231311186078\n231311187593\n231311187997\n231311187896\n231311187795\n231311188098\n231311187694\n231311164359\n231311167793\n231311179209\n231311173653\n231311186381\n231311189008\n231311189412\n231311189816\n231311190625\n231311191130\n231311191332\n231311191231\n231311191433\n231311190726\n231311188604\n231311192140\n231311192645\n231311191837\n231311191736\n231311192039\n231311193049\n231311193352\n231311193453\n231311194160\n231311194564\n231311194261\n231311194766\n231311194867"
}
bwipjs.toCanvas(canvas, config);  // this process is very slowly

**Comment by yingfengchen** [comment]
let canvas = document.createElement('canvas');
const config = {
	  backgroundcolor: "ffffff"
	  barcolor: "000000"
	  bcid: "qrcode"
	  eclevel: "M"
	  format: "full"
	  paddingbottom: 0
	  paddingleft: 0
	  paddingright: 0
	  paddingtop: 0
	  rotate: "N"
	  scaleX: 1
	  scaleY: 1
	  text: "231311164258\n231311177794\n231311173451\n231311179916\n231311179815\n231311180927\n231311181937\n231311180523\n231311182139\n231311184563\n231311182543\n231311185876\n231311185573\n231311186078\n231311187593\n231311187997\n231311187896\n231311187795\n231311188098\n231311187694\n231311164359\n231311167793\n231311179209\n231311173653\n231311186381\n231311189008\n231311189412\n231311189816\n231311190625\n231311191130\n231311191332\n231311191231\n231311191433\n231311190726\n231311188604\n231311192140\n231311192645\n231311191837\n231311191736\n231311192039\n231311193049\n231311193352\n231311193453\n231311194160\n231311194564\n231311194261\n231311194766\n231311194867\n231311164258\n231311177794\n231311173451\n231311179916\n231311179815\n231311180927\n231311181937\n231311180523\n231311182139\n231311184563\n231311182543\n231311185876\n231311185573\n231311186078\n231311187593\n231311187997\n231311187896\n231311187795\n231311188098\n231311187694\n231311164359\n231311167793\n231311179209\n231311173653\n231311186381\n231311189008\n231311189412\n231311189816\n231311190625\n231311191130\n231311191332\n231311191231\n231311191433\n231311190726\n231311188604\n231311192140\n231311192645\n231311191837\n231311191736\n231311192039\n231311193049\n231311193352\n231311193453\n231311194160\n231311194564\n231311194261\n231311194766\n231311194867"
}
bwipjs.toCanvas(canvas, config);  // this process is very slowly

**Comment by yingfengchen** [comment]
I have no idea how to improve performance.

**Comment by yingfengchen** [comment]
but in http://bwip-js.metafloor.com/demo/demo.html 
same text performs different.
http://bwip-js.metafloor.com/demo/demo.html  is so fast

**Comment by metafloor** [comment]
Not able to reproduce the problem:

```
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>qrcode test</title>
<script type="text/javascript" src="../bwip-js/master/dist/bwip-js-min.js"></script>
<script type="text/javascript">
function go() {
    let canvas = document.createElement('canvas');
    const config = {
        backgroundcolor: "ffffff",
        barcolor: "000000",
        bcid: "qrcode",
        eclevel: "M",
        format: "full",
        paddingbottom: 0,
        paddingleft: 0,
        paddingright: 0,
        paddingtop: 0,
        rotate: "N",
        scaleX: 1,
        scaleY: 1,
        text: "231311164258\n231311177794\n231311173451\n231311179916\n231311179815\n231311180927\n231311181937\n231311180523\n231311182139\n231311184563\n231311182543\n231311185876\n231311185573\n231311186078\n231311187593\n231311187997\n231311187896\n231311187795\n231311188098\n231311187694\n231311164359\n231311167793\n231311179209\n231311173653\n231311186381\n231311189008\n231311189412\n231311189816\n231311190625\n231311191130\n231311191332\n231311191231\n231311191433\n231311190726\n231311188604\n231311192140\n231311192645\n231311191837\n231311191736\n231311192039\n231311193049\n231311193352\n231311193453\n231311194160\n231311194564\n231311194261\n231311194766\n231311194867\n231311164258\n231311177794\n231311173451\n231311179916\n231311179815\n231311180927\n231311181937\n231311180523\n231311182139\n231311184563\n231311182543\n231311185876\n231311185573\n231311186078\n231311187593\n231311187997\n231311187896\n231311187795\n231311188098\n231311187694\n231311164359\n231311167793\n231311179209\n231311173653\n231311186381\n231311189008\n231311189412\n231311189816\n231311190625\n231311191130\n231311191332\n231311191231\n231311191433\n231311190726\n231311188604\n231311192140\n231311192645\n231311191837\n231311191736\n231311192039\n231311193049\n231311193352\n231311193453\n231311194160\n231311194564\n231311194261\n231311194766\n231311194867",
    };
    let ts0 = Date.now();
    bwipjs.toCanvas(canvas, config); 
    let ts1 = Date.now();
    document.getElementById('mydiv').innerHTML += 'rendered in ' + (ts1-ts0) + 'ms<br>';
}
</script>
</head>
<body>
<button onclick="go()">Click Me</button>
<div id="mydiv"></div>
</body>
</html>
```
![image](https://user-images.githubusercontent.com/385436/160318109-43cb43fa-f63e-4430-9f75-db0be67031c9.png)

That test was run on Chrome Version 98.0.4758.81 (Official Build) (64-bit) on a 10 year old Win7 laptop.

**Comment by yingfengchen** [comment]
![image](https://user-images.githubusercontent.com/20177121/173343237-b3c716e6-df0f-4020-a1ff-85edbfe5634c.png)
you see it takes 607ms. the first time it always take a lot time. but in http://bwip-js.metafloor.com/demo/demo.html the same text is so fast. what's the difference
