### ISSUE TITLE
UPC_E, UPC_A, EAN_8, EAN_13 Barcode text not appearing to follow standard

### ISSUE THREAD

**Issue by Jack-Gitter** [metafloor/bwip-js#249]
Hi, I'm generating the aforementioned barcode types using BWIPJS like so: 

```
const c = document.createElement("canvas");
        let canvas = bwipjs.toCanvas(c, {
            bcid: type, 
            text: text, 
            scale: size,
            includetext: true, 
            textxalign: "center", 
            backgroundcolor: 'ffffff', 
        });

    img = document.getElementById('hello');
    const uri = canvas.toDataURL("image/png");
    img.src = uri;
```
The EAN_13 barcode generated looks like so (note the text): 

![000000000000 (1)](https://user-images.githubusercontent.com/64998723/160919967-842abcbe-b35b-46af-92f3-bce9587fdcb1.png)

Although I'm trying to get it to look like this:

![ean13format](https://user-images.githubusercontent.com/64998723/160919769-1b948bf1-9ba8-4761-b0b6-eee97c5b388f.png)

Is there an option to format the text for the respective barcodes like so?

**Comment by metafloor** [comment]
Why are you specifying `textxalign`?  You are specifically asking for the text to not use the default layout.
