### ISSUE TITLE
Question: Provide single barcode type releated js.min versions?

### ISSUE THREAD

**Issue by ArgV04** [metafloor/bwip-js#251]
Is it possible to provide single barcode generator js-min versions dependant on a specific barcode type? We need to generate the barcode only for one type of barcode. The would reduce the min.js bundle size because other types are not needed. Is it possible?

**Comment by metafloor** [comment]
The ES6 modules (browser and nodejs) are specifically designed for tree shaking via a packaging tool.  That will give you the minimal size you are looking for.
