### ISSUE TITLE
Problem with generating DataMatrix on specific string

### ISSUE THREAD

**Issue by abdulgafur24** [metafloor/bwip-js#253]
I am trying to generate DataMatrix for this string in file below 
And unfortunately it freezes and does not respond
[5.txt](https://github.com/metafloor/bwip-js/files/8598640/5.txt)

can u check?

**Comment by metafloor** [comment]
Hi @terryburton, bwip-js goes into an infinite loop on this, and the BWIPP online demo generates an error.  Used the following with BWIPP:

```
text: 0104871119000030213GTho;iggBqdq^02991KZF0^02992ypq2vBUV2pAEGd1RK3+Bm6uIDsA=ypq2vBUV2pAEGd1RK3+Bm6uIDsA=ypq2vBUV2pAEGd1RK3+Bm6uIDsA=ypq2
options: parse
```

**Comment by terryburton** [comment]
Thanks. Will take a look but will be a while since I'm traveling.

**Comment by terryburton** [comment]
Fixed by https://github.com/bwipp/postscriptbarcode/commit/b9c243b04d3e097bd44d19417070dcafff44b7c3 which will be release in due course.

**Comment by metafloor** [comment]
Can confirm that today's bwip-js release v3.1.0 fixes this issue.  Thanks Terry!
