### ISSUE TITLE
Force encode with code 128 A or B

### ISSUE THREAD

**Issue by ale8193** [metafloor/bwip-js#256]
Is there a way to force the barcode type `code128` to encode using either `code 128 B` or `code 128 A`? At the moment it is automatically selected, but for some scanner it is required a specific version.

**Comment by metafloor** [comment]
The only way to force use of a single subset would be to manually encode the data and use the `raw` option.  Looking at the BWIPP code, the binary text string should include the start codeword and the codewords for the data.  The BWIPP code calculates the checkdigit and adds the stop codeword.  As long as the characters you are encoding are entirely in subset A or B, it is not difficult to map the characters to codewords.

**Comment by ale8193** [comment]
> The only way to force use of a single subset would be to manually encode the data and use the `raw` option. Looking at the BWIPP code, the binary text string should include the start codeword and the codewords for the characters. The BWIPP code calculates the checkdigit and adds the stop codeword. As long as the characters you are encoding are entirely in subset A or B, it is not difficult to map the characters to codewords.

Thank you for your reply, is there any example of how to perform the manual encoding?

**Comment by metafloor** [comment]
Subset-B is straightforward to encode as it is just the printable ASCII characters, space through tilde, indexed from zero.  `Space` is ASCII 32, so we just subtract 32 to get the zero offset:

```
// subset-B : printable ascii
if (/[^\x20-\x7f]/.test(text)) {
    throw new RangeError("subset-B: text out of range");
}
// 0x68/104 is the subset-B start codeword
let cws = '\x68' + text.replace(/./g, ($0) => String.fromCharCode($0.charCodeAt(0)-32));

bwips.toBuffer({ bcid:'code128', text:cws, raw:true, alttext:text, textxalign:'center', includetext:true })
    .then((png) => {
       // `png is a Buffer
    })
```

The example above assumes node-js and uses `toBuffer()`.  Replace with `toCanvas()` if on the browser.

**Comment by metafloor** [comment]
Meant to post something about this yesterday but forgot.  This has turned into the mother of all bugs.  I have a test case that is currently crashing nodejs (core dump).  Planning to port the test case to the browser today to see if it can be reproduced there.

**Comment by terryburton** [comment]
Fixed with https://github.com/bwipp/postscriptbarcode/commit/bb648248c08049687987c74e25fa29fdfc566f9a
