### ISSUE TITLE
DataMatrix barcode text off center/not in alignment

### ISSUE THREAD

**Issue by Izzmo** [metafloor/bwip-js#257]
There is a bug with the data matrix code where it will not place text correctly if it is longer. I would expect it to be left aligned or center, but it's neither.

![image](https://user-images.githubusercontent.com/229083/174125448-9c257b01-040f-43b1-bee1-a482c4639f9b.png)

**Comment by metafloor** [comment]
Hi @terryburton, this is an interesting one.  Can confirm this behavior is in both BWIPP and bwip-js.  It is the presence of the pipe character in the barcode text (not `alttext`) that is causing the alignment issue.  Remove the pipe from the bar text and the text properly centers.  Here's output from BWIPP (left) and bwip-js (right) with the pipe `(22019|293821-000)`:

![image](https://user-images.githubusercontent.com/385436/174157277-ba955207-bbd4-4f58-8c8d-2cb0ba057ba1.png) ![image](https://user-images.githubusercontent.com/385436/174157343-75224a8b-3845-41cd-a455-45f4cdf650d6.png)

And here they are with the pipe replaced by space in the bar text `(22019 293821-000)`:

![image](https://user-images.githubusercontent.com/385436/174157556-3bf6490c-0732-4d82-8489-1abc169c92fd.png) ![image](https://user-images.githubusercontent.com/385436/174157606-9dd1ec1e-3f0a-447e-9da3-17762b002e71.png)

These were the options used to generate both sets of images:

```
(alttext=22019|293821-000 includetext textsize=2 textxalign=center)
```

Does `|` have any special meaning in the barcode text that might be causing this?

**Comment by terryburton** [comment]
It was using the wrong variable to determine the width of the image.

Fixed with https://github.com/bwipp/postscriptbarcode/commit/3a36140822ae97763dedeffef68d2d358de21d3a

**Comment by Izzmo** [comment]
@metafloor thanks for moving on this so quickly, really appreciate it! When could we expect this to get into the npm package release?

**Comment by metafloor** [comment]
@terryburton: Thanks for that quick fix.  Looks good on this end.

**Comment by Izzmo** [comment]
Got this integrated, looks much better! Thanks @metafloor and @terryburton
