### ISSUE TITLE
Bump  postscriptbarcode for new parse capabilities

### ISSUE THREAD

**Issue by semireg** [metafloor/bwip-js#259]
The [2022-07-01 release](https://github.com/bwipp/postscriptbarcode/releases/tag/2022-07-01) of postscriptbarcode has new parse functionality that would be beneficial to bwip-js users. Are there any concerns getting this updated in a new release?

More information at https://github.com/bwipp/postscriptbarcode/wiki/Input-Processing#parse

**Comment by metafloor** [comment]
I have already tried to integrate the new release but it breaks the cross compiler.  It will be a while before I have time to look closely at the issue.
