### ISSUE TITLE
URL API Calls Limits

### ISSUE THREAD

**Issue by eligio** [metafloor/bwip-js#260]
Hi @metafloor,
I would like to use this API URL for my project on Salesforce.
The service must be used by multiple stores around the world.
I tried to research the limits of this service but I only found the limit of 100 calls / second.
Is it for any ip address?
Are there any other limits?

Thanks
Eligio

**Comment by metafloor** [comment]
The service is now hosted on heroku and the limiter has been removed.  Please let me know if you see any issues with number of requests.
