### ISSUE TITLE
"Default" PS fill is not even-odd

### ISSUE THREAD

**Issue by softhorizons** [metafloor/bwip-js#261]
A small niggle and it doesn't cause user-visible errors, but no point in spreading untruths:

drawing-builtin.js #253 says "// PostScript's default fill rule is even-odd." Nope, the PS 'fill' operator is always non-zero winding. It's not a mode; there's a distinct 'eofill' operator. See Red Book 4.5.2.

Likewise, #266 also says even-odd. Again, 'clip' is always non-zero winding. E-o clipping would be 'eoclip'. Again, Red Book 4.5.2

**Comment by metafloor** [comment]
Updated in v3.2.0.
