### ISSUE TITLE
Generated barcode image doesn't match the original barcode 

### ISSUE THREAD

**Issue by philhk** [metafloor/bwip-js#266]
I'm using AZTEC for the barcodes but for some reason the barcode doesn't look the same as the original one. I tried using another library called Symbology and with using Symbol Size 11 I got the correct result but with bwip-js and layers: 7 I get the right amount of pixels but the barcode itself looks different. I used the string REWEDTP#2081164573423#23130234639754460553. I also attached the original barcode.
![Original Barcode](https://user-images.githubusercontent.com/66958695/191388049-40277c92-97ad-4846-9a11-437890428daa.png)
And the wrong one.
![test](https://user-images.githubusercontent.com/66958695/191388522-3cf889b0-bb7f-4cca-84d6-44ed04d957c5.png)

```
const binary = await bwip.toBuffer({
    bcid: 'azteccode',
    text: 'REWEDTP#2081164573423#23130234639754460553',
    //@ts-ignore
    layers: 7
})

if (binary)
    fs.writeFile('./test.png', binary, "binary", (err) => {
        if (!err) console.log(`test.png created successfully!`)
    })
```

**Comment by terryburton** [comment]
Refer to the following which applies equally to Aztec Code: https://github.com/bwipp/postscriptbarcode/discussions/99

**Comment by philhk** [comment]
Thank you for your quick response! So unfortunately it sounds like there's no way to change this. I just hope the changed look will still scan. Anyway you saved me a lot of time thanks for that!
