### ISSUE TITLE
willReadFrequently attribute

### ISSUE THREAD

**Issue by 500Foods** [metafloor/bwip-js#268]
Just happened to notice this message in the console...

Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
s.image @ bwip-js.js:36905

Wondering if this is something that should be set in code somewhere, or if it was deliberately not set for some reason?

**Comment by metafloor** [comment]
Curious.  Which browser generated that message?  I will add it to the next release.

**Comment by metafloor** [comment]
Added to v3.2.0.  Please let me know if this resolves the console message you were seeing.  I was not able to reproduce.
