### ISSUE TITLE
fnt4-desc.js 404 (Not Found)

### ISSUE THREAD

**Issue by delciopolanco** [metafloor/bwip-js#269]
Hi,

after solving the fnt3.desc.js 404 error by seeing this: https://github.com/metafloor/bwip-js/issues/98

now I'm having fnt4-desc.js 404 (Not Found) error on the console.

I've looked at the code and I don't see this reference on the browser-fonts.js.

Library version:

**Comment by metafloor** [comment]
Why are you using such an old version of bwip-js?
