### ISSUE TITLE
Using bwip-js in a library component, having to install bwip-js twice?

### ISSUE THREAD

**Issue by Cohaven** [metafloor/bwip-js#271]
I'm using Angular 12 and `bwip-js` 3.1.0. I have a component library repo with a barcode component that uses `bwip-js` to render barcodes. When I install the library into my webapp project as a package, `@cohaven/angular-components`, the barcode component doesn't seem to work. It only starts working if I also install `bwip-js` on the webapp, even though it's already installed in `@cohaven/angular-components`. Is this intentional? Is there a way to not have to install `bwip-js` on the consumer of the `@cohaven/angular-components` package?

**Comment by metafloor** [comment]
There is nothing angular-specific with bwip-js.  It simply installs as a standard npm package. This sounds more like a packaging/bundling bug in the angular framework.  Possibly the bwip-js `package.json` needs to have an explicit or different export to target angular? 

I don't use angular and so you will need to determine how best to resolve this bug.  If there is something that needs to change in `package.json`, please let me know.
