### ISSUE TITLE
Upgraded to 3.1.0, canvas dimensions changed

### ISSUE THREAD

**Issue by Cohaven** [metafloor/bwip-js#273]
I upgraded from 2.0.11 to 3.1.0 and noticed that the canvas dimensions changed. Discovered this after running my unit tests that check canvas size after changing `scaleY` option. The unit tests failed. Below are the barcodes and their canvas sizes, which were generated with the following options:
```
{
    "bcid": "ean8",
    "text": "1234567",
    "scaleX": 1,
    "scaleY": 2,
    "includetext": true,
    "height": 5,
    "paddingleft": 0,
    "paddingright": 0,
    "paddingtop": 0,
    "paddingbottom": 0
}
```

Version 2.0.11
![Screen Shot 2022-10-20 at 4 53 23 PM](https://user-images.githubusercontent.com/8715482/197056782-dcca363f-db51-4e39-b430-839879d7b1df.png)

Version 3.1.0
![Screen Shot 2022-10-20 at 4 35 29 PM](https://user-images.githubusercontent.com/8715482/197057198-94bf85ca-36b1-4a8a-a9d6-8bc9ad1c2867.png)

Is this expected? Are there any other things I should expect to work differently? I didn't really find a changelog or upgrade guide for v2-v3. I know about the ES6 named exports, which was the main reason for the upgrade.

**Comment by metafloor** [comment]
Release 3.0 introduced new pure-javascript font rendering, based on sbt_truetype.h.  So font metrics have changes slightly.
