### ISSUE TITLE
GS1 Data Matrix code generation is not implemented

### ISSUE THREAD

**Issue by dkhizhniak** [metafloor/bwip-js#274]
Dear developers,

I would like to generate GS1 Data Matrix code. 
There is no such an option on the website: https://data-manager.qrcode.macherel.fr/. 
I am not able to hardcode the value found in the list: https://github.com/metafloor/bwip-js/wiki/BWIPP-Barcode-Types.

When I put the code manually I get the following error: 
`dict-marker-not-found`

It can be also checked from here: http://bwipjs-api.metafloor.com/?bcid=gs1datamatrix&text=12345

I think there is no implementation for the particular code. Please fix.

**Comment by mgh128** [comment]
Dear @dkhizhniak , all

GS1 DataMatrix is supported but the text string needs to be a valid element string in which GS1 Application Identifiers are expressed in round brackets, preceding their values.

For example, 
http://bwipjs-api.metafloor.com/?bcid=gs1datamatrix&text=(01)79521141123453(17)221117(10)ABC123(21)987XYZ
generates a GS1 DataMatrix symbol for element string (01)79521141123453(17)221117(10)ABC123(21)987XYZ where:

- (01) indicates the Global Trade Item Number (GTIN) and 79521141123453 is an example value with a correct check digit.
- (17) indicates an expiration date and 221117 indicates 17th November 2022 (YYMMDD format)
- (10) indicates a batch/lot number within that GTIN - with an example value of 'ABC123'
- (21) indicates a serial number that is unique within the GTIN - with an example value of '987XYZ'.

Further information about GS1 Application Identifiers can be found in the [GS1 General Specifications](https://www.gs1.org/docs/barcodes/GS1_General_Specifications.pdf) and also at https://www.gs1.org/standards/barcodes/application-identifiers?lang=en

**Comment by dkhizhniak** [comment]
Thank you @mgh128, that works for me.
