### ISSUE TITLE
Support for bold, italic for Text Properties

### ISSUE THREAD

**Issue by alvintheodora** [metafloor/bwip-js#275]
Hi, does it support bold, italic for Text Properties?

**Comment by alvintheodora** [comment]
Hi, @metafloor , thank you for your response. Then, lets say I already have the .ttf file. How do I `loadFont` with PHP as the backend?
Will it work to just with:
```
 <style>
        @font-face {
            font-family: 'SimplyMono';
            src: url('/style/font/bwip-js/SimplyMono-Bold.ttf');
        }
</style>
```

If not, how do I do it with PHP as the backend?

**Comment by metafloor** [comment]
There are two basic ways to download file data to use in javascript. Encode it as a javascript string and embed it in `<script>` tags.  Or use XMLHttpRequest to download asynchronously.  The first approach has the advantage that the font data is available immediately, but is dependent on backend code (in your case, you need to write some php to embed the font).  The second approach is server agnostic - it will work with any http server.

I do not use php but this approach is along the lines of what you need to do:
```
<script type="text/javascript">
var myfont= "<?php echo base64_encode(fontdata); ?>";
bwipjs.loadFont('MyFont', myfont);
</script>
```

Not shown is the php code to read the font file into the `fontdata` variable.
