### ISSUE TITLE
This would be a nice addition...

### ISSUE THREAD

**Issue by Zibri** [metafloor/bwip-js#278]
https://www.xeraina.ch/publications/stamm_annularbarcodes15.pdf
![image](https://user-images.githubusercontent.com/855176/210140511-47bde602-d7b3-46b6-a02e-ee5bb7f4d9df.png)

**Comment by terryburton** [comment]
If this technology P.o.C. were ever to be developed into a fully fledged symbology then I would certainly consider it for inclusion within BWIPP. From this paper alone it appears to be very early days.

The internal data encoding needs to be developed with conformance to industry norms, e.g. FNC flags characters (GS1 AI syntax, reader programming), ECI, etc., with the chosen scheme including error detection and correction. There's some indication that their actual implementation may include this but the details are not presented in the paper. (I haven't gone hunting for the details.)

This generic implementation hogs the design space that might be shared by later symbologies of a similar type, making auto-discrimination unnecessarily difficult in future. It would likely need some further symbology-specific indicators to facilitate rapid identification and candidate discard on the basis of graphical features, prior to attempting data extraction.

It may still need to solve any remaining structural defects. At the very least it must not be possible to generate symbols with one input that might be legitimately decoded by the reference decode algorithm as multiple possible data string depending for example upon the orientation of the symbol.

**Comment by metafloor** [comment]
I am closing this issue out as not applicable, for now....
