### ISSUE TITLE
Undeclared ‘Module' dependency. What JS library?

### ISSUE THREAD

**Issue by stvnmntjy** [metafloor/bwip-js#28]
[bwip.js (L189)](https://github.com/metafloor/bwip-js/blob/ba924e2e6354f0c87b732c347919d549bb064ad3/bwip.js#L189).

I don’t see any declared dependencies in the [package.json](https://github.com/metafloor/bwip-js/blob/88fcc177efb45fe615bfaa014c99cbc172e6d5d1/package.json).

I’m just globally including `bwip.js` from an `$ npm install` (as [directed](https://github.com/metafloor/bwip-js/blob/88fcc177efb45fe615bfaa014c99cbc172e6d5d1/README.md#installation)) and I get the undefined error.

**Comment by metafloor** [comment]
Without any information on platform and installation, I really cannot debug this.  I suspect a directory structure issue with your application.  

Is the bwip-js root directory under the node_modules subdirectory of your main application?

Please provide more information on how you are using/deploying your application and its dependencies.

**Comment by stvnmntjy** [comment]
I've opted for a different route. 

You may close this issue. 

Thanks.
