### ISSUE TITLE
Trouble Reproducing Barcode - Need Assistance

### ISSUE THREAD

**Issue by aoliveiraf** [metafloor/bwip-js#284]
Hello bwip-js developers,

I am trying to reproduce the barcode attached to this message. I am having trouble getting this to work. Would you be able to provide me with some guidance on how to properly reproduce the barcode?

Thank you.[
![febraban-barcode](https://user-images.githubusercontent.com/23416647/220188882-fd25ffc2-580e-47e3-b4c5-6b0f8cd22fd3.png)
](url)

**Comment by metafloor** [comment]
I do not recognize it and my best scanners don't either.  Do you have a crisper, larger image of it?  There is too much anti-aliasing and scaling distortion.

**Comment by terryburton** [comment]
I suspect it's a demonstration code with empty contents since it's simply a repeating bar width pattern: 1 1 2 1 1 2 1 1 2 ...

Squint really hard, and it's similar to a horizontally-flipped Matrix 2 of 5 containing "88888888888888888888", but that's just a red herring.

**Comment by aoliveiraf** [comment]
I'm trying to reproduce the barcode described in the rules below, however I'm having difficulty formatting the numbers as shown in the image: four groups with the check digit highlighted in each of the groups, there may be a hyphen character as well.

A) The Bar Code to be used is the "2 of 5 interleaved" type. Note 1: "2 of 5" means that 5 bars define 1 character, with two of them being wide bars; Note 2: "Interleaved" means that the spaces between the bars also have meaning, similar to the bars; Note 3: This type of barcode only works with numeric characters. 
B) The field size of the Bar Code is 46 positions, 44 for data content plus 2 Bits, 1 for Start and the other for Stop. 
C) The Bar Code should be on the back and preferably on the front of the document. On the back, it should be on the lower part (center), and the front should be on the upper right, with 12 mm from the center of the Bar Code to the edge of the paper, and with 5 mm, at the beginning before the Start and 5 mm at least, after the Stop with blank space. 
D) To guarantee the integrity of the Bar Code reading, whenever possible, a horizontal line should be printed above and below the field, with the numerical representation, inside boxes, below the code, if printed on the upper part of the document and with the numerical representation, inside boxes, above the code, if printed on the lower part of the document. We suggest including a message on the collection documents so that customers avoid crumpling, folding, or punching the accounts so as not to damage the bar code. 
E) There should be a numerical representation of the content just above the Bar Code, it should be distributed in fields of 11 positions within boxes, plus 1 check digit, modulo-10 or modulo 11 according to the chosen currency code, for each group, this will allow the fields to be typed, in case of rejection by Bar Code reading. The check digits will not be represented in the Bar Code.

**Comment by metafloor** [comment]
bwip-js supports interleaved2of5, so generating the barcode is not an issue.

This package is a barcode generator that provides for some text rendering.  It is not a general purpose graphics interface, and only supports whatever text layout the BWIPP up-stream package supports.   

Are these barcodes to be printed on the browser or server-side?  If on the browser, than you can use HTML to handle the text formatting.  If on the server, it gets more complicated.  For example, if nodejs, you could bring in a graphics module to do the text formatting.

**Comment by metafloor** [comment]
Closing this as not relevant to the project.
