### ISSUE TITLE
Problems using includecheck

### ISSUE THREAD

**Issue by RBNDRT** [metafloor/bwip-js#292]
I'm currently developing a mobile app using React Native, and I'm having troubles using the includecheck to generate check digits for Code 39.

Code 39 does not require a check digit or checksum, so if I generate a barcode "CODE39", it's valid and it generates the barcode. If I pass "includecheck" as _true_ (and "includecheckintext" _true_ as well), it still generates as "CODE39" and not as "CODE39W", with "W" being the check digit.

Is includecheck deprecated or useless at this point? Any help is welcomed.

**Comment by metafloor** [comment]
Have you verified the generated barcode with a scanner?  The checkdigit is not displayed in the human-readable text unless you add the `includecheckintext` option. This is what the demo shows for your example:
![image](https://user-images.githubusercontent.com/385436/235936092-0d754c23-21bf-4207-9e4a-00000c6fc454.png)

**Comment by RBNDRT** [comment]
Yes, I've done that and the demo displayed what I wanted, but not in the app. Basically the condition I have for includecheck is the same for includecheckintext, so if one is true, the other is true as well...
