### ISSUE TITLE
Allow use of hex color codes with #

### ISSUE THREAD

**Issue by JavanPoirier** [metafloor/bwip-js#293]
Extensions for IDE's recognize color codes with a #. It is a simple mistake to include it and then require an investigation as to why it does not work with this library. To eliminate potential confusion, offer support for this convention.

**Comment by metafloor** [comment]
That can be added to the next release.  Will recognize both #rgb and #rrggbb formats.

**Comment by metafloor** [comment]
The new css-style color codes are now supported in version 3.4.4.

**Comment by metafloor** [comment]
Closing this as implemented.
