### ISSUE TITLE
Swiss QR Code invalid for special characters

### ISSUE THREAD

**Issue by baumschubser** [metafloor/bwip-js#294]
Encoding Swiss QR Code format generates invalid QR codes if the value contains characters like `ç`. Fails in bwip-js, works in BWIPP.

This is the value:
```
SPC
0200
1
CH4431999123000889012
S
Verein ""Zum Beispiel""
Musterstrasse
123
8000
Seldwyla
CH







123.45
CHF
S
Prototype SA
Place de l'Exemple
2
25000
Besançon
FR
QRR
210000000003139471430009017
Gönnerbeitrag
EPD



```
[Here is the QR code generated by bwip-js](http://bwipjs-api.metafloor.com/?bcid=swissqrcode&text=SPC%5ECR%5ELF0200%5ECR%5ELF1%5ECR%5ELFCH5800791123000889012%5ECR%5ELFS%5ECR%5ELFVerein%20%22%22Zum%20Beispiel%22%22%5ECR%5ELFMusterstrasse%5ECR%5ELF123%5ECR%5ELF8000%5ECR%5ELFSeldwyla%5ECR%5ELFCH%5ECR%5ELF%5ECR%5ELF%5ECR%5ELF%5ECR%5ELF%5ECR%5ELF%5ECR%5ELF%5ECR%5ELF%5ECR%5ELF200.00%5ECR%5ELFEUR%5ECR%5ELFS%5ECR%5ELFModell%20Stiftung%5ECR%5ELFPostfach%5ECR%5ELF%5ECR%5ELF78462%5ECR%5ELFKonstanz%5ECR%5ELFDE%5ECR%5ELFSCOR%5ECR%5ELFRF18539007547034%5ECR%5ELFBesan%C3%A7on%5ECR%5ELFEPD%5ECR%5ELF%5ECR%5ELF%5ECR%5ELF&parse&scale=2)

In BWIPP:
```
(SPC^CR^LF0200^CR^LF1^CR^LFCH5800791123000889012^CR^LFS^CR^LFVerein ""Zum Beispiel""^CR^LFMusterstrasse^CR^LF123^CR^LF8000^CR^LFSeldwyla^CR^LFCH^CR^LF^CR^LF^CR^LF^CR^LF^CR^LF^CR^LF^CR^LF^CR^LF200.00^CR^LFEUR^CR^LFS^CR^LFModell Stiftung^CR^LFPostfach^CR^LF^CR^LF78462^CR^LFKonstanz^CR^LFDE^CR^LFSCOR^CR^LFRF18539007547034^CR^LFBesançon^CR^LFEPD^CR^LF^CR^LF^CR^LF) (mode=2 parse) /swissqrcode /uk.co.terryburton.bwipp findresource exec
```

[Validate both QR codes here](https://www.swiss-qr-invoice.org/validator/?lang=de) and you will find that bwip-js creates an error, saying it is not UTF-8, while the code from BWIPP is valid.

**Comment by metafloor** [comment]
Patch 3.4.1 has been released to fix the issue.  The new version generates the same code words as BWIPP for your example.

**Comment by baumschubser** [comment]
Amazing response time, thank you very much for the quick fix and the very fast deployment.
