### ISSUE TITLE
Safary: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by sergeu90** [metafloor/bwip-js#295]
Hello everyone after update from 3.4.0 to 3.4.2 i get error in safary browser
![image](https://github.com/metafloor/bwip-js/assets/7217517/dfbd7894-646d-4a66-bf95-20f4c16355e1)

**Comment by metafloor** [comment]
Will have a patch for it later today.  Used a too modern RE and broke backward compatibility.

**Comment by metafloor** [comment]
v3.4.3 was released last night.  Should resolve the issue.

**Comment by metafloor** [comment]
Closing this out as v3.4.4 and #297 are related to this issue and are the final fix.
