### ISSUE TITLE
React Native: Error: While trying to resolve module bwip-js/ from file ...xxx/directory 

### ISSUE THREAD

**Issue by gesangseto** [metafloor/bwip-js#296]
After install bwip-js on react-native refer to tutorial https://bwip-js.metafloor.com/#react-native-usage.
My screen got the following error message:
```
error: Error: While trying to resolve module `bwip-js/` from file `D:\DATA GESANG\app-warehouse-merindo\V1.0.0\Android\src\screen\tab_screen\Scanner.js`, 
the package `D:\DATA GESANG\app-warehouse-merindo\V1.0.0\Android\node_modules\bwip-js\package.json` was successfully found. 
However, this package itself specifies a `main` module field that could not be resolved (`D:\DATA GESANG\app-warehouse-merindo\V1.0.0\Android\node_modules\bwip-js\dist\bwip-js-rn.mjs`. 
Indeed, none of these files exist:

  * D:\DATA GESANG\app-warehouse-merindo\V1.0.0\Android\node_modules\bwip-js\dist\bwip-js-rn.mjs(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * D:\DATA GESANG\app-warehouse-merindo\V1.0.0\Android\node_modules\bwip-js\dist\bwip-js-rn.mjs\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
    at DependencyGraph.resolveDependency (D:\DATA GESANG\app-warehouse-merindo\V1.0.0\Android\node_modules\metro\src\node-haste\DependencyGraph.js:311:17)
    at Object.resolve (D:\DATA GESANG\app-warehouse-merindo\V1.0.0\Android\node_modules\metro\src\lib\transformHelpers.js:129:24)
    at resolve (D:\DATA GESANG\app-warehouse-merindo\V1.0.0\Android\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:33)
    at D:\DATA GESANG\app-warehouse-merindo\V1.0.0\Android\node_modules\metro\src\DeltaBundler\traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (D:\DATA GESANG\app-warehouse-merindo\V1.0.0\Android\node_modules\metro\src\DeltaBundler\traverseDependencies.js:411:33)
    at processModule (D:\DATA GESANG\app-warehouse-merindo\V1.0.0\Android\node_modules\metro\src\DeltaBundler\traverseDependencies.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async addDependency (D:\DATA GESANG\app-warehouse-merindo\V1.0.0\Android\node_modules\metro\src\DeltaBundler\traverseDependencies.js:230:18)
    at async Promise.all (index 7)
```
```

  "dependencies": {
    "bwip-js": "^3.4.3",
    "react": "17.0.2",
    "react-native": "0.66.3",
    "react-zlib-js": "^1.0.5",
  },
```

```
ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"
        kotlinVersion = "1.5.31"
    }
```

**Comment by gh-user-7** [comment]
> If you look at the two starred error message lines, they are showing what file paths are being tested. Significantly, none of the possibilities are an mjs file. My guess is you need to use babel to cross-compile to a plain js file. I cannot help you more than that as I do not use react-native and do not know its tool chain.
> 
> If you discover something in the `bwip-js/package.json` file that needs to change for react-native, please let me know.

Hey there @metafloor  - I just wanted to re-visit this as this is still an issue and something I observed.

I upgraded to the react-native version of this library for V4.5.0.

I received the same error as above and after looking into the node-modules, the "main" entry in the `package.json` looks like this:

  "main": "./dist/bwip-js-rn.js",
  "module": "./dist/bwip-js-rn.mjs",
  "react-native": "./dist/bwip-js-rn.mjs",
  "types": "./dist/bwip-js-rn.d.ts",

the issue is that the `bwip-js-rn.js` file does not exist in the `dist` directory. When I overwrote this line in the file to reference `"./dist/bwip-js-rn.mjs"` instead, re-ran `yarn start` for my react-native project, the error went away. Any recommendations on a path forward for this?

**Comment by metafloor** [comment]
Yep, that's a typo.  Thanks for reporting it.  Will release a new version later today.  The fix is to use the mjs file extension as the platform-specific packages are esm-only.

**Comment by metafloor** [comment]
Version 4.5.1 should have the correct paths in `package.json` for `@bwip-js/react-native`.

**Comment by gh-user-7** [comment]
Amazing - thanks for resolving that!
