### ISSUE TITLE
Issue with ISBN

### ISSUE THREAD

**Issue by softwebtuts** [metafloor/bwip-js#300]
I want to remove the **validation** check from the **ISBN** type, how is it possible?

**Comment by terryburton** [comment]
If the check doesn't pass then the symbol would be not be an ISBN.

**Comment by softwebtuts** [comment]
Yes, I know but I don't want that, and also is their any builtin function to add hyphens to the ISBN?

**Comment by softwebtuts** [comment]
Please help me to remove the validation, I want to generate ISBN from any given 13-digit number, no matter whether it is valid or not

**Comment by terryburton** [comment]
> Please help me to remove the validation, I want to generate ISBN from any given 13-digit number, no matter whether it is valid or not

The backend PostScript library provides no means to bypass validation.

**Comment by terryburton** [comment]
> Yes, I know but I don't want that, and also is their any builtin function to add hyphens to the ISBN?

There is no programmatic way to know where hyphens must be placed in an ISBN.
