### ISSUE TITLE
suggest toSVG use viewBox instead width and height attributes

### ISSUE THREAD

**Issue by xinglie** [metafloor/bwip-js#302]
now `toSVG` METHOD return like `<svg version="1.1" width="84" height="84">` 

if allow `svg` to fit parent node,  maybe `<svg version="1.1" viewBox="0 0 84 84">`  is better

if allow pass `class` to `svg` like `<svg class="custom-class" version="1.1" viewBox="0 0 84 84">`  is best

**Comment by metafloor** [comment]
Seems like a good improvement.  Breaks compatibility but since this feature is only a couple of weeks old, not too concerned about it.  Unless there are others that disagree with this change, I will release it later this week as a patch-level release.
