### ISSUE TITLE
how to new line text

### ISSUE THREAD

**Issue by syahrul90888** [metafloor/bwip-js#303]
alttext: `${couponCode}\n${couponLabel}`,
 
 doesn't work using \n, the text is still concatenated

**Comment by metafloor** [comment]
That functionality is not supported by BWIPP, the upstream postscript code.

**Comment by syahrul90888** [comment]
then how to add text in new line?

**Comment by metafloor** [comment]
Closing this issue since it requires functionality that BWIPP does not support.
