### ISSUE TITLE
when i use this to create an dataMatrix code, how can i set my code correct level, i set by this, but looks not useful

### ISSUE THREAD

**Issue by daisy908** [metafloor/bwip-js#312]
const svg = (bwipjs as any).toSVG({
      bcid: 'datamatrix', // Barcode type
      text: codeValue, // Text to encode
      includetext: true, // Show human-readable text
      textxalign: 'center', // Always good to set this
      eclevel: qrcodeLevel || 'H',
    });

**Comment by metafloor** [comment]
The upstream BWIPP code does not support an explicit user-specified error correction level.  See [DataMatrix](https://github.com/bwipp/postscriptbarcode/wiki/Data-Matrix).

@terryburton:  Is it possible to increase EC level by specifying a larger symbol size?

**Comment by terryburton** [comment]
No. Unlike QR, the DM symbology does not allow user-defined ECC levels.
