### ISSUE TITLE
Compatibility with IE11

### ISSUE THREAD

**Issue by PacManPk** [metafloor/bwip-js#313]
Hello,

I was looking for a barcode generator library and found this library. It seems nice (I didn't use it till now). I want to use it to generate barcodes in MS Access (in web browser control which is based on IE11). Can you please tell me how can it work in IE11 as I don't see it in the list of supported browsers. I see that that current version isn't compatible with ie11. If current version isn't compatible then can you please tell me which older version is compatible with ie11?

I'll be thankful.

Best Regards

**Comment by metafloor** [comment]
You would likely have to go back to version 1 to get IE11 compatibility, but I would not recommend that.  There have been a lot of bug fixes in the cross-compiled code, plus the BWIPP postscript source code has progressed considerably since then.

A better approach would be to use webpack to translate/polyfill the current release to ES5 - `[ "web", "es5" ]` target - with `bwip-js/dist/bwip-js.js` as the source.

**Comment by PacManPk** [comment]
Hi, thanks for reply. I am almost unaware of HTML/Js programming. Do you mean by useing webpack to translate/polyfill the current release to ES5, it will work in ie11?

**Comment by metafloor** [comment]
Yes. My understanding is that IE11 was mostly ES5 compliant, and implemented some ES6 features.  For example, `Uint8Array`.  Downgrading the latest bwip-js release to ES5 will incur runtime cost, but you're working with such an ancient javascript engine that performance is likely the least of your worries....

**Comment by PacManPk** [comment]
Hi, thanks for help. I will be thankful if you could guide me a little how to convert latest release to ES5.

**Comment by metafloor** [comment]
I am not proficient with webpack - just use a minimal config of it to test tree shaking with this project.  There are tons of websites that show how to use it.  Plus its reference and user manuals are pretty good.  Good luck!

**Comment by PacManPk** [comment]
Thanks a lot.
