### ISSUE TITLE
Property 'toCanvas' does not exist on type 'typeof BwipJs'.

### ISSUE THREAD

**Issue by imamnghr** [metafloor/bwip-js#314]
use react js v 18.2.0, please help

**Comment by james-yeoman** [comment]
v4.1.2 should fix this

**Comment by james-yeoman** [comment]
Reproduction repo? It's working perfectly fine for me, so there's a difference between my config and yours

**Comment by metafloor** [comment]
@james-yeoman : I agree with your assessment.  It appears that this is a configuration issue with the bundler being used.  It would be great if we could figure out what settings are needed to make it work reliably.

@ntubrian : Can you try using a qualified import:

```
import bwipjs from 'bwip-js/browser';
```
