### ISSUE TITLE
QrCode to zpl

### ISSUE THREAD

**Issue by manuelbosi** [metafloor/bwip-js#315]
Hi,
I'm using this awesome library to render barcodes in my zebra printer labels web designer.
The user can configure dpi, label width, label height etc...
When the user saves the label my backend build the zpl output for printing.

On the zpl side the qr code only supports a magnification factor value from 1 to 10, but I see the library accepts only scale, width and height options.
Is it possible to emulate the zpl magnification factor using the library and get render qr code of the correct pixels size?

**Comment by metafloor** [comment]
I recommend you experiment with `scale` to see how it correlates with the magnification factor used by `^BQ`.  The `height` and `width` options simply change `scaleY` and `scaleX`, sometimes unpredictably.

**Comment by manuelbosi** [comment]
@metafloor thanks for your reply.
Is it also possibile to render the qr code by handling custom dpi value manually?
For example I need to render the qrcode using a 600dpi value

**Comment by metafloor** [comment]
Just multiply scale by a factor predefined for each dpi.  For example, 2 for 200dpi, 3 for 300dpi, and 6 for 600dpi.

**Comment by manuelbosi** [comment]
@metafloor So the value I set in the `RenderOptions` object is scale: myScale * myDpiScale, right?

**Comment by metafloor** [comment]
Have you worked with different dpi zpl printers?  Typically, the zpl rendering engine does not scale for dpi.  The scaling for dpi is done in the ZPL code - by the developer.  Specifically, using `^BY` to control module width and for qrcode, the magnification factor in the `^BQ` command (which does have its defaults based on dpi).
