### ISSUE TITLE
nodejs 20.10.0 generate a different barcode compare when I use nodejs 20.9.0

### ISSUE THREAD

**Issue by SSANSH** [metafloor/bwip-js#317]
Hello 

I ran following code using nodejs20.10.0 and nodejs 20.9.0

`
const bwipjs =require('bwip-js');

async function convert() {
console.log((await bwipjs.toBuffer({
      bcid: 'code128',
      text: '1234',
      height: 40,
      width: 109,
    })).toString('base64'));
};

convert();
`
Value of base64 is diff, do you know why?

**Comment by metafloor** [comment]
Show the console output.  Hard to understand what you are asking without it...

**Comment by SSANSH** [comment]
you can try on your side code provided: if you run code with nodejs20.9 and then nodejs20.10 you will see base64 output is not the same.

**Comment by metafloor** [comment]
Most likely a bug fix in zlib was brought into the v20.10 release: https://www.zlib.net/ChangeLog.txt

Image output is identical - only the compression has changed.
