### ISSUE TITLE
Windows 64 bit machine - shasum check failed

### ISSUE THREAD

**Issue by svlungade** [metafloor/bwip-js#32]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bwip-js"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for C:\Users\mac\AppData\Local\Temp\npm-14248-087bfa03\vossbasmgdd2oss01.ad.infosys.com_4873\bwip-js\-\bwip-js-0.15.1.tgz
npm ERR! Expected: dfdd79361f48429a5019228f1a726c845dd74d2b
npm ERR! Actual:   c6423acfcc980c7b55d06e4377439109510b26f3
npm ERR! From:     http://vossbasmgdd2oss01.ad.infosys.com:4873/bwip-js/-/bwip-js-0.15.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\mac\GITRepo\project\npm-debug.log

**Comment by metafloor** [comment]
I do not think this is an error with bwip-js.  More likely, a file corruption problem within the npm CDN.

I just tested from a windows 7 x64 machine and the install is working for me.

The error text suggests reporting the problem to npm.

**Comment by metafloor** [comment]
Closing this as no response from submitter.
