### ISSUE TITLE
4.2.0 will not generate the same barcode as 3.0.1

### ISSUE THREAD

**Issue by ianbale** [metafloor/bwip-js#320]
This works with version 3.0.1 (and 2.0.11) and produces a 7 layer barcode.

Barcode.toBuffer({
      bcid: 'azteccode',    text:"06CMQ5TCDFG00R1LZUNVVMCUOPHWIPZXEUNKRXTLBAENQDOWOPQMBNFHMVOAXPKFAFYKXVXJPNKKNXIUSFUWRLHTERVPKFDXLQGDJIAUPATBVAZWJMPMJIDGJXPLRHMBNYAWEXWWLZHUNFESWXTSWQWOJPSLMDVNRHBMCINGIRQICIYTOVGVVRXHUJCKWHQSAEWDSRDNTXLJYBWOZAWQYACCIPMZRIXRFGINWXRWN",
      scale: 3,
      includetext: false,
      eclevel: 23,
      ecaddchars: 0,
      layers: 7,
      width: 28,
      height: 28,
    })

Trying the same thing with 4.2.0 results in an error:
bwipp.aztecInvalidECaddChars#21838: The number of additional EC codewords must be 3 or more

If I remove the ecaddchars property, then I get another error:
bwipp.qrcodeNoValidSymbol#22330: Maximum length exceeded

Removing layers property or increasing it to 8 does result in a barcode.

Why does v4 require more layers and v3 for the same payload?

**Comment by terryburton** [comment]
From the Aztec Code specification:

> 4.1.e. Selectable error correction:
>  1. User-selectable, from 5% to 95% of the data region, with a minimum of 3 codewords.

...

> 11.2 User selection of minimum error correction level
>
> Users, judging their applications to be especially benign or critical, may choose to specify an alternate minimum
error correction percentage, ranging from below 10% to above 50% plus **always**, for data security, 3 additional
checkwords.

In BWIPP version 2023-03-20 we started to enforce this lower limit.

Regarding:

> @terryburton: This is beyond my paygrade. Do you remember what changed with azteccode? (And do you see the errant qrcode reference in the raiseerror? Checked with latest and it's still there.)

I've just pushed a fix.

**Comment by ianbale** [comment]
Thanks @terryburton 
Much appreciated!
