### ISSUE TITLE
Uncaught ReferenceError: BwipJs is not defined - Runtime error

### ISSUE THREAD

**Issue by kjell-van-straaten** [metafloor/bwip-js#322]
hi, I am trying to use your package to render a data matrix svg. Looks pretty useful, but unfortunately I am getting a runtime error in my console, which my editor doesn't flag.

Code:
`import bwipjs from 'bwip-js';`

Browser Console:

> Uncaught ReferenceError: BwipJs is not defined.

Terminal:

> no issues found

Using:
React 18.2 (typescript, vite)
bwip-js: 4.2.0

Any clue how to proceed? I haven't managed to solve this with the help of the web unfortunately.

**Comment by metafloor** [comment]
Without seeing the code, I would suspect you have a typo on `BwipJs`.  Your import name is `bwipjs`.

**Comment by kjell-van-straaten** [comment]
i deleted my .vite/dep folder and now it works. Somehow the dependency broke
