### ISSUE TITLE
Error on long "texts"

### ISSUE THREAD

**Issue by dagalufh** [metafloor/bwip-js#34]
Hi

Doing some tests on this, and for instance with aztec codes, they can be rather long.. And when i'm trying one very long i get:

BWIP-JS ERROR: Error: dict: seq: --undefined--

**Comment by metafloor** [comment]
You need to provide a test case so I can understand what you are trying to do.

**Comment by dagalufh** [comment]
Alright, i'll create on tomorrow. It's a xml based on exm for Honeywell
7800 devices.

They cause the above error. That is when calling the buffer function with
an entire xml as text.
Den 26 apr. 2016 17:34 skrev "metafloor" <notifications@github.com>:

**Comment by dagalufh** [comment]
Here you go, an example xml that sets the volume, powersettings and some other things.
When running this with azteccode, i get this error: BWIP-JS ERROR: Error: dict: seq: --undefined--


`<?xml version="1.0"?>
<ConfigDoc desc="" flags="2" name="Registry">
  <HHPReserved>
    <Key name="EXMVersion">1.0.1</Key>
    <Key name="RegistryData">1</Key>
    <Key name="RunAppName">EZConfig</Key>
  </HHPReserved>
  <Section flags="5" desc="Registry Key: HKCR" name="HKEY_CLASSES_ROOT" />
  <Section flags="4" desc="Registry Key: HKCU" name="HKEY_CURRENT_USER">
    <Section flags="6" name="ControlPanel">
      <Section flags="6" name="BackLight">
        <Key flags="6" type="4" name="ACTimeout">0x00000258</Key>
        <Key flags="6" type="4" name="ACTimeoutUnchecked">0x00000000</Key>
        <Key flags="6" type="4" name="BatteryTimeout">0x0000012c</Key>
        <Key flags="6" type="4" name="BatteryTimeoutUnchecked">0x00000000</Key>
        <Key flags="6" type="4" name="BacklightLevel">0x00000008</Key>
        <Key flags="6" type="4" name="ACBacklightOnTap">0x00000001</Key>
        <Key flags="6" type="4" name="BacklightOnTap">0x00000001</Key>
        <Key flags="6" type="4" name="BacklightAutoAdjust">0x00000000</Key>
      </Section>
      <Section flags="6" name="Notifications">
        <Section flags="6" name="ShellOverrides">
          <Key flags="6" type="4" name="SavedVolume">4294967295</Key>
        </Section>
      </Section>
      <Section flags="6" name="Volume">
        <Key flags="6" type="4" name="Volume">4294967295</Key>
      </Section>
    </Section>
  </Section>
  <Section flags="4" desc="Registry Key: HKLM" name="HKEY_LOCAL_MACHINE">
    <Section flags="6" name="System">
      <Section flags="6" name="CurrentControlSet">
        <Section flags="6" name="Control">
          <Section flags="6" name="Power">
            <Section flags="6" name="Timeouts">
              <Key flags="6" type="4" name="BattSuspendTimeout">0x00000000</Key>
              <Key flags="6" type="4" name="ACSuspendTimeout">0x00000000</Key>
            </Section>
          </Section>
        </Section>
      </Section>
      <Section flags="6" name="ErrorReporting">
        <Section flags="6" name="DumpSettings">
          <Key flags="6" type="4" name="DumpEnabled">0x00000000</Key>
        </Section>
      </Section>
    </Section>
    <Section flags="6" name="Comm">
      <Section flags="6" name="ConnMgr">
        <Section flags="6" name="Providers">
          <Section desc="" flags="6" name="{EF097F4C-DC4B-4c98-8FF6-AEF805DC0E8E}">
            <Section flags="6" name="HTTP-{ADB0B001-10B5-3F39-27C6-9742E785FCD4}">
              <Key flags="6" type="1" name="ConnectionGUID">
              </Key>
              <Key flags="6" type="1" name="DestId">
              </Key>
              <Key flags="6" type="4" name="Enable">
              </Key>
              <Key flags="6" type="1" name="ExtraInfo">
              </Key>
              <Key flags="6" type="1" name="Override">
              </Key>
              <Key flags="6" type="1" name="Proxy">
              </Key>
              <Key flags="6" type="4" name="ReadOnly">
              </Key>
              <Key flags="6" type="1" name="SrcId">
              </Key>
              <Key flags="6" type="4" name="Type">
              </Key>
              <Key flags="6" type="1" name="Username">
              </Key>
            </Section>
            <Section flags="6" name="HTTP-{18AD9FBD-F716-ACB6-FD8A-1965DB95B814}">
              <Key flags="6" type="1" name="ConnectionGUID">{C942FD57-CAF5-0CB4-7511-CA0B00652759}</Key>
              <Key flags="6" type="1" name="DestId">{436EF144-B4FB-4863-A041-8F905A62C572}</Key>
              <Key flags="6" type="4" name="Enable">0x00000001</Key>
              <Key flags="6" type="1" name="ExtraInfo">
              </Key>
              <Key flags="6" type="1" name="Override">
              </Key>
              <Key flags="6" type="1" name="Proxy">new-inet:1159</Key>
              <Key flags="6" type="4" name="ReadOnly">0x00000000</Key>
              <Key flags="6" type="1" name="SrcId">{18AD9FBD-F716-ACB6-FD8A-1965DB95B814}</Key>
              <Key flags="6" type="4" name="Type">0x00000000</Key>
              <Key flags="6" type="1" name="Username">
              </Key>
            </Section>
          </Section>
        </Section>
      </Section>
    </Section>
  </Section>
</ConfigDoc>`

**Comment by metafloor** [comment]
Is the bar code text that entire string of XML?  By my cut-and-paste-into-vi estimate, that text is 3353 characters, including \n eols.  Aztec's maximum data capacity is 3067, and that is only achievable when using purely alphanumeric data.  All those non-alphanumeric characters cause shifts to alternate character sets, which further reduces the maximum capacity.

The reason bwip-js is is giving the `seq: --undefined--` error is because the PostScript loop that selects the optimal encoding can't find one that fits.

Just for comparison, I entered that text into the BWIPP online demo, and while it produced a bar code, it only encoded the first ~300 characters.

**Comment by dagalufh** [comment]
Hmm okey, strange. I'll have to generate a barcode from the EzConfig and see if i can find some other application that can read the barcode and say exactly what's in it. See if EzConfig changes the xml into something else.

**Comment by terryburton** [comment]
I'm aware that I really need to add friendly error handling to the optimised encoders of 2D barcodes, etc. It's on the BWIPP TODO list :-)

**Comment by dagalufh** [comment]
I can't find one that can decode the barcodes generated by EZConfig, so i guess we'll close this as it seems to be limited to Honeywell devices...

**Comment by terryburton** [comment]
Aztec Code symbols have a dedicated flag for reader initialisation purposes, enabled in BWIP-JS using the "readerinit" option.

If the symbols generated by EZConfig have this flag set then the standards forbid the reader for relaying the remaining content to the host during a normal scan which would explain your difficulty with reading them.
