### ISSUE TITLE
unsafe asynchronous execution

### ISSUE THREAD

**Issue by clshortfuse** [metafloor/bwip-js#342]
Hi, I've been using the library to generate QR codes and it seems that when batching multiple requests at the same time, the library will generate corrupted QR strings.

I've only used the QR and SVG options in NodeJS, but glancing at the code, the culprit seems to be the heavy use of global variables (`var`) and paused execution with `Promise` (`async`/`await`).

That means when one process is starting while another one is in process is already running, it will overwrite the work that hasn't completed.

I'm not sure what platform the library targets, but either asynchronous execution has to be removed or the variable scoping has to be upgraded to ES2015 (ES6).

**Comment by clshortfuse** [comment]
It may be because DrawingContext is being shared in my code. I'm assumed it can't be and you would need a new instance per draw. That's the more likely scenario, though I'd still suggest against global variables.

**Comment by metafloor** [comment]
In theory you are correct, but the code is structured so it is not a problem.  The postscript global state is only modified during synchronous execution.  It is only after the postscript code has exited/returned that asynchronous operations are initiated for drawing (e.g. zlib for png creation).

**Comment by metafloor** [comment]
You should be creating a new drawing context per render.  They are not designed to be shared.  The built-in drawing contexts are always created new for each render.
