### ISSUE TITLE
Error: bwipp.GS1unknownAI#3497: AI GdU<gs>(91: Unrecognised AI

### ISSUE THREAD

**Issue by v0-v0-git** [metafloor/bwip-js#343]
Service throws error when you try to use parentheses  in any position between AI 21 и 91

Example when "(" in string
Error: bwipp.GS1unknownAI#3497: AI GdU<gs>(91: Unrecognised AI

Here's a full url with parameters(url encoded) :
https://bwipjs-api.metafloor.com/?bcid=gs1datamatrix&text=(01)04620757979006(21)5btHYnjVq(GdU%3Cgs%3E(91)EE10%3Cgs%3E(92)LFDU/cef0RnXBlMCXRhYp5nJAoFyJOxzQbFuMpFYOO8=&parse&parsefnc

or

If I run it in pycharm with: 0104620757979006215btHYnjVq(GdU<gs>91EE10<gs>92LFDU/cef0RnXBlMCXRhYp5nJAoFyJOxzQbFuMpFYOO8=

Error creating DataMatrix: bwipp.GS1unknownAI AI GdU(91: Unrecognised AI

If I remove the character "("  from the string everything starts working correctly.

BWIPJS_VERSION=4.4.0 (2024-06-18)
BWIPP_VERSION=2024-06-18

STEPS TO REPRODUCE

1 Use gs1 datamatrix encoder in bwip-js
2 Use &parse and &parsefnc parameters
3 Add text with "(" or ")" 
4 Try to obtain gs1 datamatrix on bwipjs-api

**Comment by metafloor** [comment]
With the GS1 text, extraneous parentheses must be encoded using `^040` (left paren) and `^041` (right paren).  Along with the `parse` option, which you are already settting.

**Comment by terryburton** [comment]
Issue was also raised here: https://github.com/bwipp/postscriptbarcode/issues/269

**Comment by metafloor** [comment]
Closing this as solved.
