### ISSUE TITLE
[Data Matrix] '+' character rendered as whitespace

### ISSUE THREAD

**Issue by fedenevis** [metafloor/bwip-js#35]
I'm trying to render this text I01.00057-2+110316 using this url:

http://api-bwipjs.rhcloud.com/?bcid=datamatrix&text=I01.00057-2+110316&monochrome=true&backgroundcolor=fdf6f6&includetext&guardwhitespace

but reading the png datamatrix code the result is always I01.00057-2 110316

It seems to replace '+' character with white space. 

Thank you for any help. 
Federico

**Comment by metafloor** [comment]
The plus sign is special to URL encoding.  As you discovered, it maps to space.  If you are manually creating a URL for bwip-js, you need to replace `+ % # &` with their `%xx` escapes:

```
+ == %2B
% == %25
# == %23
& == %26
```

For example, this is the correctly encoded URL you gave above:

http://api-bwipjs.rhcloud.com/?bcid=datamatrix&text=I01.00057-2%2b110316&monochrome=true&backgroundcolor=fdf6f6&includetext&guardwhitespace

If you are using bwip-js from withing javascript (node, browser, etc), use the `encodeURIComponent()` global function on - at minimum - the `text` and `alttext` parameters.  E.g.

```
img.src = 'http://api-bwipjs.rhcloud.com/?bcid=datamatrix&text=' + 
    encodeURIComponent(text) +
    '&monochrome=true&backgroundcolor=fdf6f6&includetext&guardwhitespace';
```

**Comment by fedenevis** [comment]
It works. Thanks a lot for your help!
