### ISSUE TITLE
height option is not working with GS1 DataBar Truncated

### ISSUE THREAD

**Issue by GitHubUserDots02** [metafloor/bwip-js#350]
The barcode height is not changing, when setting a height in the options for a "GS1 DataBar Truncated" code.
All other GS1 DataBar codes seem to work fine with a height option.
![GS1_databar_truncated](https://github.com/user-attachments/assets/4fa9426f-4301-47cd-9c6e-ccb5f7213d4a)

**Comment by metafloor** [comment]
Looking at the upstream postscript source, it appears the truncated format uses a fixed height of 13px/13pt:

```
 format (truncated) eq {/height 13.0 72 div def} if
```

So the behavior you are seeing is by design.

**Comment by terryburton** [comment]
> So the behavior you are seeing is by design.

That's correct. By definition, the truncated varuant is a DataBar Omnidirectional with a fixed size.

**Comment by GitHubUserDots02** [comment]
Thank you for your quick response. This issue can be closed.
