### ISSUE TITLE
How do you convert bwipp to bwip-js?

### ISSUE THREAD

**Issue by brikou** [metafloor/bwip-js#36]
Can you provide your script to convert original code in postscript to your javascript?
Thank you!

**Comment by metafloor** [comment]
Very timely question.  The original cross-compiler was a quick-and-dirty affair that got the job done for a business requirement, but was not something I was willing to show the public ;-)

I have been working on a new version of the cross-compiler that produces significantly better code (faster, smaller, less memory intensive, no async loading, and is human-readable to boot).  The compiler is mostly complete and passing all tests.  For most barcode types, the generated code executes from 5x to 10x faster.  

The current plan is to release the new version by the end of the month (June 2016).  This release will include the cross-compiler and the test framework used for validating it.  There is a lot of new documentation needed before this can be released, hence the end of month estimate.

**Comment by terryburton** [comment]
Very exciting! I'll look forward to this.

**Comment by brikou** [comment]
Thank you for your answer and can't wait for this release 😉 Let me know if I can help in any way (I'm thinking in particular about bundler support like webpack for frontend usage/demo). I have few jours free tomorrow...

**Comment by metafloor** [comment]
@brikou: Thanks for the offer.  I am mostly a back-end developer using proprietary web UIs and do not keep track of the latest front-end trends.  Next week I plan to finalize the directory structure for the new release and will publish on a wiki page.  At that point, if you could chime in on what needs to be done for front-end deployment, that would be fantastic.

**Comment by brikou** [comment]
Great! Just ping me on this thread (or brikou2 on twitter) once cross compiler is available so I can give you my feedback and start working on the new frontend bundled with webpack...

**Comment by metafloor** [comment]
Version 1.0 was quietly released yesterday.  Had a small panic when the update broke the openshift/rhcloud hosted public api.  With that and immediately finding a bug with IE10 (why do bugs always appear after releasing?!? - must be some law of nature), we are currently sitting at version 1.0.4.

**Comment by brikou** [comment]
@metafloor very nice... I'll take a look on it this next week
