### ISSUE TITLE
Node-js Issue: options not an object

### ISSUE THREAD

**Issue by neme5i5** [metafloor/bwip-js#38]
Great library by the way, but I'm getting an error with the node.js version. I have used the javascript browser addition fine.

Request: http://example.com/?bcid=ean13&text=0024600010030&includetext
Error: bwipp.typeError: options not an object

This seems to work fine against your service URL.

**Comment by metafloor** [comment]
Please show how to reproduce this issue.  And make sure you are working with release 1.0.4.  There were some problems in the initial commits for 1.0.

From the master branch, I launch as `node server` and everything works.  Likewise, the online api pulls from npm to sync with the code base, and it is working.
