### ISSUE TITLE
Unable to access API

### ISSUE THREAD

**Issue by CraigRosenbaum** [metafloor/bwip-js#39]
http://api-bwipjs.rhcloud.com/ is returning a 503 Service Temporarily Unavailable error.
![error](https://cloud.githubusercontent.com/assets/20070876/16237249/2e9141b6-37a1-11e6-95d8-1fd958de2744.png)

**Comment by metafloor** [comment]
Thanks for the heads up.  The service is running again.

I was forced to upgrade the node cartridge used by the api, and it had problems with tripwire, which I used to automatically restart node applications.  I will look for an alternative.

**Comment by CraigRosenbaum** [comment]
Great, confirmed it is working now.
