### ISSUE TITLE
Thank you, thank you, thank you.

### ISSUE THREAD

**Issue by Siyfion** [metafloor/bwip-js#4]
This isn't an issue, just merely a thank you, you cannot begin to comprehend how much work, time & effort you have just saved me by creating this brilliant library. The Node.js server example was ***perfect*** for what I needed to achieve.

Thank you again from me, and from all my users that will benefit directly as a result of your hard work! :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by metafloor** [comment]
You are entirely welcome.  And thanks for the feedback.  I see the download statistics but have very little idea how people are actually using the code!

**Comment by terrancesnyder** [comment]
+1

**Comment by terrancesnyder** [comment]
+1 million actually
