### ISSUE TITLE
gs1 expanded barcode is blurry with IE

### ISSUE THREAD

**Issue by steve1bi** [metafloor/bwip-js#45]
With IE, the generated barcode print-out is blurry and not scannable. With firefox and chrome, it is working fine

**Comment by metafloor** [comment]
A lot more details are needed before I can help.

**Comment by steve1bi** [comment]
(1) use IE, browse to http://bwip-js.metafloor.com/demo/demo.html
(2) Chose type as: gs1 databar extended, scalex and scaley as 1, 1
(3) Click "Show barcode" button, and then print the page.

Facts:
(1) the printed barcode looks blurry, and not scannable 
(2) if use other browser with the same steps, the printed barcode are sharp and scannable

**Comment by metafloor** [comment]
What version of IE are you using?  I have tested with both 10 and 11 and do not see this issue.

Can you provide screen capture of the barcode?

**Comment by steve1bi** [comment]
IE 11, screen looks good, but if send to printers, you can see the results. We have tested multiple computers with multiple printers: HP Laserjet 1300, Konica Minota Bizhub c20, Zebra GK420D etc.

**Comment by metafloor** [comment]
This is not a bwip-js issue but more inherent to the browser.  Here are some tips I have used to get around IE's odd scaling behavior (that is what is causing the bluriness).

Do not specify any dimensions for the <img> tags used with barcode images generated by bwip-js.  Let the browser size them to their native dimensions.  Also make sure there is no padding, margin, or border on the img's.  If you need those, wrap the image in a span or div and apply to the wrapper.

In an `onload` handler for the page (or `$(document).ready()` if using jquery), iterate through each image, getting the `offsetWidth` and `offsetHeight` and setting them as the element's `style.width` and `style.height` in `px` units.

That usually fixes the scaling issue, although I have seen situations where there is still some bluriness.

Another trick I have found to work is to create an image 2x or 3x larger than needed, and down-scale it to size.

Hope that helps.
