### ISSUE TITLE
Online Barcode API. Service Temporarily Unavailable

### ISSUE THREAD

**Issue by efrainx3** [metafloor/bwip-js#48]
Good day, 
I'm trying to use the API, but the site responds with an error 503 Service Temporarily Unavailable. The site will be enabled again ?.
Exaplme: http://api-bwipjs.rhcloud.com/?bcid=code128&text=1234567890
Thank you very much.

**Comment by metafloor** [comment]
Thanks for the heads up.  The project was updated yesterday and it looked like the api had restarted correctly, but I guess not....

Need to figure out how to monitor that service better.

All should be running again.
