### ISSUE TITLE
Bwip js blocks the stack trace when node crashes

### ISSUE THREAD

**Issue by pravincar** [metafloor/bwip-js#49]
While running node js if bwip js is included, if there is a crash instead of the stack trace the contents of /private/var/www/konnect/node/node_modules/bwip-js/freetype.js are printed.

````
/private/var/www/konnect/node/node_modules/bwip-js/freetype.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(typeof Module==="undefined")Module={};if(!Module.expectedDataFileDownloads){Module.expectedDataFileDownloads=0;Module.finishedDataFileDownloads=0}Module.expectedDataFileDownloads++;((function(){var loadPackage=(function(metadata){function runWithFS(){var fileData0=[];fileData0.push.apply(fileData0,[79,84,84,79,0,13,0,128,0,3,0,80,67,70,70,32,137,224,82,238,0,0,7,132,0,0,45,223,70,70,84,77,101,130,23,249,0,0,55,12,0,0,0,28,71,68,69,70,0,160,0,4,0,0,53,100,0,0,0,32,71,80,79,83,184,255,184,254,0,0,54,220,0,0,0,48,71,83,85,66,234,147,151,221,0,0,53,132,0,0,1,88,79,83,47,50,131,156,137,79,0,0,1,64,0,0,0,96,99,109,97,112,146,230,183,142,0,0,5,184,0,0,1,170,104,101,97,100,251,7,171,9,0,0,0,220,0,0,0,54,104,104,101,97,7,42,2,2,0,0,1,20,0,0,0,36,104,109,116,120,33,252,29,155,0,0,55,40,0,0,0,234,109,97,120,112,0,115,80,0,0,0,1,Pravins-MacBook:node pravin$
````

Any idea what is leading to this? I have to remove the module to make debugging possible currently. 

Using node 6.0.0 on OS X 10.11.6

**Comment by metafloor** [comment]
This may be related to issue #44.  The emscripten framework uses `process.on('uncaughtException')` to implement the POSIX `exit()` interface.  But, as you have discovered, it has unintended side effects.

As an experiment, go into freetype.js and search for `uncaughtException` and comment out the text:

```
process["on"]("uncaughtException",(function(ex){if(!(ex instanceof ExitStatus)){throw ex}}));
```

by placing `/* ... */` comments around it.  The minified code is hard to visually parse so be careful you get the right text into the comments. Then see if your problem still exists.

Please let me know if that solves the issue.  If so, I will make it a higher priority to permanently fix freetype.js as bwip-js does not use emscripten's `exit()` interface.

**Comment by pravincar** [comment]
Thanks, @metafloor. Tried commenting the uncaughtException handler and it sorts out the issue. 
Any reason why you chose to not use the native freetype library?

**Comment by metafloor** [comment]
freetype is not available in browsers and trying to use a canvas replacement while loading custom fonts is far too complex.  Plus, one of the principal design factors of this project was to create a pure javascript solution.  (What the p in bwip-js stands for ;-)
