### ISSUE TITLE
FNC1 Use in GS1-128 Barcodes

### ISSUE THREAD

**Issue by rogerkirkness** [metafloor/bwip-js#50]
I am having trouble getting my barcode to scan because it appears I am not using  FNC1 characters correctly. When I use the bwip-js PNG generator to create a GS1-128, it works unless I have a variable length field. It works if I type the text into the online generator, but not when I use the API, so it must have to do with the text string I am feeding the encoder being missing something it needs.

If I have a variable length field that I would like to parse properly but there is nothing in the GS1-128 documentation (that I could find) that says what character(s) to use to indicate the end of the field. Assuming I have an (21) field with x number of characters like so: (21)523451234. How do I tell it to end the barcode after the 4? I saw some with ^FNC1 online but that did not work when I placed it at the beginning of the barcode, end of the barcode, beginning of the AI and end of the AI.

**Comment by metafloor** [comment]
Can you please respond with the exact barcode text and options that you are using.  GS1 uses some complex encoding, so we will probably need @terryburton's help here.

**Comment by terryburton** [comment]
The library takes care of inserting FNC1 field separators in GS1-type symbols:

https://github.com/bwipp/postscriptbarcode/wiki/GS1-Application-Identifier-Standard-Format

Can you provide an example of a symbol that doesn't scan.

**Comment by rogerkirkness** [comment]
Yes:

        bcid:           'gs1-128',
        text:           (01)0845678956780(11)160922(3102)000100(21)160922163709,
        includetext:    true,
        parsefnc:       true,
        height:         8,
        width:          3

Process:
- Generate that text from data on the client
- Pass it to a node.js method with bwip-js and use those options
- Take the output png, base64 encode it
- Publich the encoded base64 string to the client in a dataurl

It appears on screen but cannot be scanned. The same input string works on the online generator, but not with the API and not using bwip-js 1.1.1.

**Comment by terryburton** [comment]
`parsefnc` is unnecessary but not harmful.

I can confirm that the output of the bwip-js online demo matches BWIPP and scans correctly so this looks specific to BWIP-JS.

Over to @metafloor.

**Comment by metafloor** [comment]
Yep.  It's the `width` option.  I removed the option, and it generates a scannable symbol.

The `width` option causes some odd scaling to occur on the bar/space widths.  I will try to see where that is going wrong.

**Comment by rogerkirkness** [comment]
Confirmed: I removed the width option and it scans. Thank you for your help. I am not sure I have much to add in terms of doing a PR and trying to update it. But at least we figured it out. Thanks again.

**Comment by metafloor** [comment]
I should have some time tomorrow to investigate this.  I also don't like that the demo and the node interfaces are treating `height` differently.  That was a regression in the 1.0 release.
