### ISSUE TITLE
Unable to access API For barcode 

### ISSUE THREAD

**Issue by amishranjit** [metafloor/bwip-js#51]
Hello,
     I am having an issue while trying to generate bar-code.
![capture](https://cloud.githubusercontent.com/assets/22897557/19455875/7536a314-9484-11e6-95b4-1cc96f051847.PNG)

**Comment by learntofly83** [comment]
This works fine for me:

From: https://github.com/metafloor/bwip-js/wiki/Online-Barcode-API

>>

http://api-bwipjs.rhcloud.com/?bcid=code128&text=1234567890

>>

Possible server downtime from the 503 message?

**Comment by metafloor** [comment]
On holiday right now, so a little slow to respond.  I have restarted the api.  Looks like it is running now.

**Comment by amishranjit** [comment]
@ metafloor,  Thank you for restarting the api. It is working fine.
