### ISSUE TITLE
Possibility to have more than one check digit module

### ISSUE THREAD

**Issue by rptpaulino** [metafloor/bwip-js#52]
Hello,

First of all, I would like to thank for this library and to the effort to make it better and better,

At the moment, I'm struggling with have more than one check digit module available, from what I could understand the barcodes that have checkdigit, they only have the formula to do the mod10.

For example barcode 128 has available Module 10, Module 43 and Mod103.

Can you please let me know if I'm missing something or if this could be a future implementation?

Thank you in advance.

**Comment by terryburton** [comment]
Modern generalised barcode standards only have one "intrinsic" check digit method. E.g. In Code 128 the check digit is based on a mod103 sum.

Application standards of some general standard to a specific industry often introduce an additional "in-data" check digit. E.g. In HIBC Code 128 there is a mod43 check digit include in the payload in addition to the mod103 check digit that is intrinsic to the symbol construction. GS1 standards that represent a GTIN-14 (e.g. EAN-14) include its mod10 check digit in the data...

If you choose the most specific encoder (code128 for generic symbols; hibccode128 for HIBC symbols; ean14 for an EAN-14, etc.) then the check digits will be handled automatically and verified where they are supplied. The documentation for each encode provides details of each specific case.

**Comment by rptpaulino** [comment]
Hello Terry,

Thank you very much for your help.

Have a nice evening.

Best regards,

2016-10-24 16:26 GMT+01:00 Terry Burton <notifications@github.com>:
