### ISSUE TITLE
Question: GS1 Barcode Stacked barheight Option

### ISSUE THREAD

**Issue by terrancesnyder** [metafloor/bwip-js#53]
Tried the defaults and searched the docs, any hints on how to do a GS1 barcode, and condense the height of each bar of the stack to make it smaller. Similar to the general barcode height options on other barcodes like UPCA/E?

Below are examples of when we applied "height=20" and left the defaults. Notice the padding around the GS1 when height is applied also the stretch of the gs1 as well.

![default](https://cloud.githubusercontent.com/assets/379950/20650987/f83a1184-b4a9-11e6-8df1-97081cd389b4.png)

![height](https://cloud.githubusercontent.com/assets/379950/20650988/f8439d94-b4a9-11e6-9c72-09f1131b4c96.png)

**Comment by metafloor** [comment]
I looked at the original postscript source code and do not see where there is an option to set the bar height of the linear parts of the symbol.

@terryburton Is it possible to control the linear bar heights in the databar* symbols?

**Comment by terryburton** [comment]
With the current code the bar height is always 34X. X being the minimum separator module height as per specification:

> GS1 DataBar Expanded may be stacked in two to eleven rows ... GS1 DataBar Expanded Stacked is used when the symbol area or print mechanism is not wide enough to accommodate the full single row symbol. Each row is 34X high with a 3X separator pattern between the rows.

Adjusting the ratio of the bar height in relation to the separator pattern height is non-standard. It's an easy feature to add but what's the use case?

**Comment by terrancesnyder** [comment]
@terryburton its done in coupon systems where you must fit the GS1 barcode on a limited real-estate. Similar to UPC-A/UPC-E barcodes truncating and resizing so that they can fit on smaller packaged goods.

**Comment by terryburton** [comment]
@terrancesnyder So am I right in thinking that it would suffice to provide an option to specify the bar height as a factor of the separator module height, say barxmult, default 34 (for GS1 DataBar Expanded)?

@metafloor The extra whitespace padding above the symbol appears to be BWIP-JS specific.

**Comment by terrancesnyder** [comment]
@terryburton yes that would work great!

**Comment by terryburton** [comment]
In release 2016-12-15 of BWIPP I've added a barxmult option to GS1 DataBar Stacked Omnidirectional (default barxmult=33) and GS1 DataBar Expanded Stacked (default barxmult=34).

https://github.com/bwipp/postscriptbarcode/releases/tag/2016-12-15

I've going to hold off documenting this non-standard option until I can find more evidence that adjustment of the bar heights relative to the separator pattern is a common scenario that scans reliably in practise.

**Comment by terrancesnyder** [comment]
We'll go ahead and use our $10,000 barcode quality checker and let you know how things worked out.
