### ISSUE TITLE
API URL Down

### ISSUE THREAD

**Issue by CraigRosenbaum** [metafloor/bwip-js#54]
Barcodes calling the API are not generating. I went to http://api-bwipjs.rhcloud.com/ and get a 503 Service Temporarily Unavailable

**Comment by metafloor** [comment]
I signed up for a free monitoring service that is supposed to text me when that link goes down.  I guess you get what you pay for....

API is back up.  Thanks.

**Comment by CraigRosenbaum** [comment]
Awesome, thanks for the quick turnaround.

On Dec 7, 2016 5:32 PM, "metafloor" <notifications@github.com> wrote:

I signed up for a free monitoring service that is supposed to text me when
that link goes down. I guess you get what you pay for....

API is back up. Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/metafloor/bwip-js/issues/54#issuecomment-265607632>,
or mute
the thread
