### ISSUE TITLE
Re-Size QR Code

### ISSUE THREAD

**Issue by PeterA1** [metafloor/bwip-js#55]
Hi,

I want to re-size the .png produced for a QR code.  If I apply a scale the QR code produced is smaller, but the QR code has white space to the top and right?

Any help appreciated.

![image](https://cloud.githubusercontent.com/assets/6002680/21333023/72949bba-c644-11e6-9aa6-ef8686d54721.png)

Peter

**Comment by metafloor** [comment]
Can you provide some example input parameters/options so I can understand the issues you are seeing?

**Comment by PeterA1** [comment]
using bwip-js@1.1.1

![image](https://cloud.githubusercontent.com/assets/6002680/21345026/72e8c74c-c696-11e6-9e48-08874cd532c5.png)

**Comment by metafloor** [comment]
There is a bug here that I believe we also saw in issue #53.  But fortunately for your use case, there is a work around until I can track down the error.

At scale factor 1, each "module" of the qr-symbol is a 2x2 square.  At scale factor 2, each module is a 4x4 square.  The only possible size in between those would use a scale factor of 1.5.  Specifying `scale:1.65` is causing the extra padding.

I just verified that this works without adding padding using both the online demo and the online API.  For example, this produces a qr-symbol with a 3x3 module size and no extra padding:

http://api-bwipjs.rhcloud.com/?bcid=qrcode&text=http%3A%2F%2Fgoo.gl%2F0bis&eclevel=M&scale=1.5

**Comment by RUSHt** [comment]
Thanks, the 1.5 Ratio sorted the Skewed Padding.

However I did notice that if I set Options { scale: 1.5, paddingwidth: 5, paddingheight: 5 } then I got...

![blankbarcode](https://cloud.githubusercontent.com/assets/14270948/21360315/4d6c8f94-c6d7-11e6-9e03-fb75141cdd3d.png)

**Comment by metafloor** [comment]
It turns out the padding works when the scale factor is an integer, but not when fractional.  I have a fix for the issue and will roll-out a new release later today.

**Comment by liu-minjie** [comment]
> It turns out the padding works when the scale factor is an integer, but not when fractional. I have a fix for the issue and will roll-out a new release later today.

fractional still not work, @metafloor
