### ISSUE TITLE
Width / height calculation

### ISSUE THREAD

**Issue by thoean** [metafloor/bwip-js#58]
The documentation says the width and height parameters are in millimeters. How do I reliably convert that to pixels, for example when I want the barcode to be 100px high? Height 100 (mm) gives me a 566 high image (px). So I ended up dividing by 5.66 before calling bwip-js. However, that doesn't relate to 72 or 144 dpi nor to factor 25.4 to convert from mm to inch.

Thanks for providing insight why 566 is the magic number.

**Comment by metafloor** [comment]
Please include the sample bar code parameters you are using.

**Comment by thoean** [comment]
I've the following example test:

```javascript

    it('width / height test', function (done) {

        let options = {
            bcid: 'code128',
            text: '123456789',
            height: 100
        };

        bwipjs.toBuffer(options, (err, result) => {
            if (err) {
                done.fail(err);
            } else {
                let fs = require('fs');
                fs.writeFile('test.png', result, (err) => {
                    if (err) {
                        done.fail(err);
                    } else {
                        done();
                    }
                });
            }
        });
    });
```

It results in a PNG file that is 202px wide and 566px high. Specifically this:

![test](https://cloud.githubusercontent.com/assets/7394947/21974723/d0c531c4-dbc8-11e6-8c29-da80fa2ea1e8.png)

**Comment by metafloor** [comment]
The height is in millimeters.  100mm == 3.937in and bwip-js (and BWIPP) renders 72pixels/inch.

  72*3.937 == 283

Hope that helps.
