### ISSUE TITLE
Aztec Code Binary Data

### ISSUE THREAD

**Issue by Fujnky** [metafloor/bwip-js#59]
Hello, I'm trying to encode binary data in an Aztec 2D code. Currently my code looks like that: 

```javascript
data = fs.readFileSync('file.bin').toString('latin1')
bwipjs.toBuffer({
    bcid: 'azteccode',
    text: data
}, function (err, png) {
    if (err) {
        console.log(err);
    } else {
        fs.writeFileSync('code.png', png, 'binary')
    }
});
```

which produces exactly the same result as encoding the bytes with `^NNN` and the `parse` option. My problem is, that the decoded data is different from the original data:

```
$ hexdump file.bin
0000000 4430 2002 a642 6a4d 5340 28ca 12ca 0ef7
0000010 84c7 24c6 f781 4baf b66e 0b4b 8df9 2d50
0000020 cf99 b8f2 2002 0a34 ee56 7ba0 264d 4279
0000030 55fd d7a7 5bca 407a 276c 2080 b11d 3a92
0000040 1dbe e04a 510b                         
0000046
```

opposed to

```
$ hexdump file2.bin
0000000 4430 2002 c242 4da6 406a c353 288a 8ac3
0000010 c312 0eb7 87c3 84c2 86c3 c224 c381 c2b7
0000020 4baf c26e 4bb6 c30b c2b9 508d c22d c399
0000030 c38f c2b2 02b8 3420 560a aec3 a0c2 4d7b
0000040 7926 c342 55bd a7c2 97c3 8ac3 7a5b 6c40
0000050 c227 2080 c21d c2b1 3a92 bec2 4a1d a0c3
0000060 510b 000a                              
0000063
```

Apparently encoding it as `latin1` changes the data, but I don't know how or whether I can "convert it back". Is there any better method of putting binary data in the code?
Thank you very much.

**Comment by Fujnky** [comment]
I actually just tried changing the symbology – it works exactly the way it should with Data Matrix and PDF417. This just adds to my confusion..

**Comment by terryburton** [comment]
Sounds like this could be a problem with the high-level encoding for Aztec Code in the supporting BWIPP library that I maintain.

Would you mind conducting your test (using ^NNN notation) on the generator here:

https://the-burtons.xyz/barcode-generator/

If it has the same problem then please provide me with your input and I'll take a look. What are you using to decode/scan the result?

**Comment by Fujnky** [comment]
@terryburton You seem to be right. I am using zxing to read the codes. I tried to encode `^128^128^128` using the generator, this is the result:

```
$ zxing aztec.png | xxd
00000000: c280 c280 c280 0a                        .......
$ zxing datamatrix.png | xxd
00000000: 8080 800a                                ....
```

The Data Matrix representation is the correct one. Maybe it's a problem with zxing, but I don't know any oher open source scanning software for Aztec..

**Comment by terryburton** [comment]
A very brief look reveals that calling BWIPP as follows:

    0 0 moveto (^128^128^128) (parse) /azteccode /uk.co.terryburton.bwipp findresource exec

Results in the following internal bitstream sequence:

    (11111) (00011) (10000000) (10000000) (10000000)

Which represents:

    {Binary shift} {length 3} {128} {128} {128}

So it seems that BWIPP/BWIP-JS are generating a correct symbol.

I note that `c280` is the hex UTF-8 encoding of a "raw 128 byte" (technically the first character of the Latin-1 suppliment): http://www.fileformat.info/info/unicode/char/0080/index.htm

Therefore I think that your aim should be to tell ZXing to provide output in the form of a byte array rather than a UTF-8 encoded string. Why this should be different between Aztec Code and other format is a mystery... or a bug ;-)

**Comment by Fujnky** [comment]
Thank you very much for your help. I'll try to find out what's wrong over there.

**Comment by terryburton** [comment]
For anyone passing, it looks as though this may have been addressed here: https://github.com/zxing/zxing/pull/591
