### ISSUE TITLE
A Possibility for Ionic 2? 

### ISSUE THREAD

**Issue by SliceofCheese** [metafloor/bwip-js#62]
Perhaps I'm merely overlooking something in the documentation, but is there any sort of support for Ionic 2 applications with this library, or more specifically Angular2? I've attempted to use it, and I've run into a bit of a snag with Type Errors and FreeType2. There is a claim by the debugger that TypeError: str.charCodeAt is not a function in line1 of FreeType, and I'm not sure if it's some sort of error between how things are handled with how bwip-js communicates with FreeType2, or Freetype2 itself (I've already attempted to contact them as well, as I'm willing to fix the issue if I can find some sort of place to pinpoint for the error).

**Comment by metafloor** [comment]
You will need to provide a lot more information and code examples before I can hope to help you.  Freetype (or more correctly, emscripten compiled code) does not play well with others.  You have to load it just right and let it run its `main()` before using.  I suspect you are trying to call into the freetype library before it is fully initialized (takes several hundred millis).

**Comment by SliceofCheese** [comment]
Here was a basic set of code that I had to test to see compatibility: 

import { Component } from '@angular/core';

import { NavController } from 'ionic-angular';
import { loadFont, toBuffer } from 'bwip-js';
import {  } from 'freetype2';

let term: any;

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})

export class HomePage {

  public image: string; 

  constructor(public navCtrl: NavController) {

  }

  public search(event) {
    term = event.target.value;
  }

  public createMatrix() {
    console.log('We have made it inside');
  
    loadFont('Arial', 25, '');
    toBuffer({
      bcid: 'datamatrix',
      text: '23402398423094829034',
    }, function (err, png) {
      debugger;
      if (err) {
        console.log('this failed');
      
      }
      this.image = png; 
    }

    );

  }

}

No errors were actually given until run time.

**Comment by metafloor** [comment]
What version of bwip-js are you running?  There are no modules named freetype2 nor bwip-js in this project.

I am not familiar with ionic but assume your code is running under node?

**Comment by SliceofCheese** [comment]
I was using the most recent installation of bwip-js. The modules that are used are in the package.json in the build folder. It's a bit different, but that's how you actually use modules in ionic. THe version of freetype2 is ^0.3.0, so any version that's .3 or if more recent, higher. And for bwip-js, I'm currently using 1.2.3.

**Comment by metafloor** [comment]
Looking at your sample code again, I see one issue.  You are not providing the font data to the `loadFont()` method.  The third argument should be something like (from the README):

```
  require('fs').readFileSync('fonts/Inconsolata.otf', 'binary')
```

Also, you don't want to load fonts on each call to a bar code renderer.  That should be done at global scope (once).

**Comment by SliceofCheese** [comment]
Okay, so I'll try removing that and then calling 'binary' for the loaded fonts when I have the chance to to see how that works out afterward. I'll let you know how the results turn out.

**Comment by SliceofCheese** [comment]
Seems to cause less of a problem that way. I thought I had sent a response. Thanks for the catch.

**Comment by adamdabbracci** [comment]
@SliceofCheese I don't know if this helps you at all, but I just ran into this exact issue. I solved it by moving the PNG generation to my API (which is a Node API) and returning the PNG as a buffer. It's a bit of a hack (the call becomes async which is a bit frustrating when generating PDFs) but it works!

**Comment by DominikTrenz** [comment]
I had the same issue with ionic 2. Freetype is the problem. I deleted freetype from the module and it works

**Comment by metafloor** [comment]
Can anyone provide a simplified test case that shows this issue?  A URL that exercises the problem would be great!

**Comment by DominikTrenz** [comment]
@metafloor You can just use the ionic starter app and add your lib to the imports of a page 
`import { toBuffer } from 'bwip-js';`
(https://ionicframework.com/docs/intro/tutorial/). But it is actually a freetype problem.

In this fork i removed freetype (I don't need any of it's functions) and it works:
https://github.com/DominikTrenz/bwip-js
