### ISSUE TITLE
React Application to use this package

### ISSUE THREAD

**Issue by SoniaBalodi** [metafloor/bwip-js#63]
Hi,

I need to include this package in react application.
I started with requiring all the js:
var	bwipp = require('../node_modules/bwip-js/bwipp');
var	bwipjs = require('../node_modules/bwip-js/bwipjs');
var	zlibPNG	= require('../node_modules/bwip-js/node-zlibPNG');
var	freetype = require('../node_modules/bwip-js/freetype');

getting error : str.charCodeAt is not a function

CAn you help me in rectifying this? Also can you help me how i can set the text and formatoptions.

**Comment by metafloor** [comment]
Please read issue #62.  Same thing.  Please provide some code that shows the issue.  I cannot read minds (at least not over the interwebs ;-).

Looks like you are trying to make your own node-bwipjs.js module.  Why not use the one provided?  It is debugged and working and has all the exports a node application should need.

> Also can you help me how i can set the text and formatoptions.

That is covered in the README.  Take a look at the image generator section.  It shows a detailed example of options being passed in.

**Comment by tmfksoft** [comment]
I'm getting the exact same issue while trying to use it with NodeWebkit.

I'm simply trying to require bwip-js.
Using this:
```var bwipjs = require('bwip-js');```

It then results in this:
```
(unknown) Uncaught TypeError: str.charCodeAt is not a function
    at lengthBytesUTF8 (Z:\DEV\NodeJS\David Labels\node_modules\bwip-js\freetype.js:1:128533)
    at intArrayFromString (Z:\DEV\NodeJS\David Labels\node_modules\bwip-js\freetype.js:1:133363)
    at Object.callMain (Z:\DEV\NodeJS\David Labels\node_modules\bwip-js\freetype.js:15:3226)
    at doRun (Z:\DEV\NodeJS\David Labels\node_modules\bwip-js\freetype.js:15:4065)
    at run (Z:\DEV\NodeJS\David Labels\node_modules\bwip-js\freetype.js:15:4233)
    at Object.<anonymous> (Z:\DEV\NodeJS\David Labels\node_modules\bwip-js\freetype.js:15:5402)
    at Module._compile (module.js:595:32)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
```

This is purely from just trying to include it.
Using latest NodeWebkit with NodeJS v7.10.0

**Comment by metafloor** [comment]
I do not use webpack so may not be able to help you.  I suspect that webpack is providing its own version of `require()` that is confusing the runtime detection code embedded by emscripten in `freetype.js`.

This issue is obviously a show stopper for a lot of people but I find it interesting that no one can be troubled to craft up a working example.  If you provide sample code and step by step instructions on how to install and reproduce this issue, then I am willing to give it a try.  But I am not willing to spend hours reading webpack documentation to figure out what you are trying to do.

**Comment by tmfksoft** [comment]
I'm not using WebPack, I'm using NodeWebkit. Works very similar to Electron.

**Comment by metafloor** [comment]
My mistake but really doesn't change anything.  The framework has to be messing with the `require()` functionality to run inside a web-worker thread.  I need to see code and instructions on how to reproduce if you want any assistance with this.

**Comment by tmfksoft** [comment]
No problem,
It's pretty simple to reproduce.
Download NodeWebkit SDK from nwjs.io and run it against this repo:
https://github.com/tmfksoft/bwip-nwjs

I'm using the example shown in your README.
You'll want to run `npm install` in the repo.

**Comment by kyledecot** [comment]
I'm also getting this w/ a React application created w/ `create-react-app` (version 1.4.0). I simply took the code from the README and dropped it in `App.js`. Here's that code if it's helpful at all

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import bwipjs from 'bwip-js';

class App extends Component {
  createBarcode() {
    bwipjs.toBuffer({
            bcid:        'code128',       // Barcode type
            text:        '0123456789',    // Text to encode
            scale:       3,               // 3x scaling factor
            height:      10,              // Bar height, in millimeters
            includetext: true,            // Show human-readable text
            textxalign:  'center',        // Always good to set this
            textfont:    'Inconsolata',   // Use your custom font
            textsize:    13               // Font size, in points
        }, function (err, png) {
            if (err) {
                // Decide how to handle the error
                // `err` may be a string or Error object
            } else {
                // `png` is a Buffer
                // png.length           : PNG file length
                // png.readUInt32BE(16) : PNG image width
                // png.readUInt32BE(20) : PNG image height
            }
        });
  }

  render() {
    {this.createBarcode()}
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default App;
```

**Comment by metafloor** [comment]
Thank you for posting that code.  I may actually be able to use it for testing.  I am away from the office until Tuesday, so can't make any progress on this until probably end of next week.

**Comment by metafloor** [comment]
I have the code snippet above working with the freetype-less version of bwip-js but, having never worked with react before, I cannot see how to display the bar code on the page.  Can you provide a bit more "glue"?  Thanks.

**Comment by metafloor** [comment]
Now that I have dug into the React documentation, I am a bit surprised.   React is not at all what I thought it was.  All of the code that has been posted for this issue is trying to execute native node javascript in the browser without any marshalling between client and server.  Of course that is not going to work.

So, digging deeper into React, I see where the differentiation needs to be made.  Here's a working React app that uses the upcoming version 1.5 release of bwip-js:

```javascript
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import bwipjs from 'bwip-js';

class App extends Component {
  constructor(props) {
	super(props);

    bwipjs('mycanvas', {
            bcid:        'code128',       // Barcode type
            text:        '0123456789',    // Text to encode
            scale:       3,               // 3x scaling factor
            height:      10,              // Bar height, in millimeters
            includetext: true,            // Show human-readable text
            textxalign:  'center',        // Always good to set this
            textfont:    'Inconsolata',   // Use your custom font
            textsize:    13               // Font size, in points
        }, function (err, cvs) {
            if (err) {
                // Decide how to handle the error
                // `err` may be a string or Error object
		console.log(err);
            } else {
		// Nothing to do?
            }
        });
  }

  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
	<canvas id="mycanvas"></canvas>
      </div>
    );
  }
}
export default App;
```
![image](https://user-images.githubusercontent.com/385436/29950770-22fb321c-8e7b-11e7-9902-60b4e7946ec5.png)

As you can see, it renders directly to a canvas element, either via its `id` or passing the canvas element directly.  I don't claim to know React and/or WebPack, so improvements to the interface may be needed.

In the future, it may be possible to support data-urls for img elements, but that will require a lot more work.  So for now, bwip-js will support canvas only.

**Comment by metafloor** [comment]
Version 1.5 is out.  The project home page now has a description of using bwip-js in a React app along with additional information about using in other browser frameworks.
