### ISSUE TITLE
What files should cdnjs host?

### ISSUE THREAD

**Issue by hare1039** [metafloor/bwip-js#64]
Hi,
I am a member from cdnjs, and we want to add this library to our server.
What files should we host?

Thank you for any help you can provide.
https://github.com/cdnjs/cdnjs/pull/10581

**Comment by metafloor** [comment]
A lot depends on usage, but the bare minimum that needs to be available:
```
freetype.js
bwipjs.js
bwipp.js
```
All other files are either nodejs modules or supporting files for the browser demo.

**Comment by hare1039** [comment]
Thanks!

**Comment by hare1039** [comment]
Do we need bwipp.js in latest version? Thanks.

**Comment by metafloor** [comment]
Yes.  The three files listed are the minimum needed.

**Comment by hare1039** [comment]
OK
Thanks.
