### ISSUE TITLE
Generating multiple barcodes using bwip-js

### ISSUE THREAD

**Issue by Dineshrajaa** [metafloor/bwip-js#66]
Hi all,

I am trying to make a small utility app with bwip-js which will generate barcodes for a range based on the starting and ending values
[Code](https://gist.github.com/Dineshrajaa/ddf704a8a76e7a32bafeb78004c28388)
The code is working if I generate only one barcode say if I enter starting as 1 and ending as 2
but when I enter starting 1 and ending 3, I am getting the following issue
[Error](https://gist.github.com/Dineshrajaa/baa399fd92f2b30504ab986c55575285)

**Comment by metafloor** [comment]
Put the `var bwipjs = require('bwip-js');` at global scope (above the `var readline = require('readline');`).  It should only be `required()` once.

**Comment by Dineshrajaa** [comment]
Thanks for the tip @metafloor, I have updated the code still I am facing the same issue! can you please help me to get rid of that issue?

**Comment by metafloor** [comment]
Also try moving the `bwipjs.loadFont()` out of the function.  It should only be called once per font.

**Comment by Dineshrajaa** [comment]
> Also try moving the bwipjs.loadFont() out of the function. It should only be called once per font.
This is cool, now I am not getting any error but the problem is it is working only once have I made any logical error?
Example:
`Enter starting value: 1
Enter ending value: 15
starting:1, ending:15
1
Generated Barcode
2
`

**Comment by metafloor** [comment]
Is the code now working for you?  I ran it with the fixes recommended above and it worked.

> should I clean up the buffer?

The buffers will be gc'd just like any other javascript object.  Unless they contain sensitive information and are running in a multi-user server framework, then you should fill them with zeros.  Otherwise, just let v8 take care of them.

**Comment by Dineshrajaa** [comment]
Thank you so much for your support @metafloor  now code is working fine.. closing this issue.
