### ISSUE TITLE
nodejs type: 'gs1qrcode' error

### ISSUE THREAD

**Issue by rainweb** [metafloor/bwip-js#69]
Error: array-marker-not-found

`var bwipjs = require('bwip-js');
    var p = new Promise(function(resolve,reject){
        //includetext height=0.5 textyoffset=2
        bwipjs.toBuffer({
            bcid:        options.type || 'code128',       // Barcode type
            text:        options.code,    // Text to encode
            scale:       2,               // 3x scaling factor
            height:      options.height || 17,              // Bar height, in millimeters
            includetext: true,            // Show human-readable text
            textxalign:  'center',        // Always good to set this
            textyoffset: 2
        }, function (err, png) {
            if (err) {
                resolve();
            } else {
                resolve(png)
            }
        });
    });`

**Comment by metafloor** [comment]
You need to provide the actual values that are being used.  That code dump above tells me nothing helpful.

**Comment by rainweb** [comment]
@metafloor value:201149000971

**Comment by metafloor** [comment]
GS1 requires a data identifier to precede each data segment.  See the example text in the online demo.  If you just need a qr-code, then use the qrcode type.

**Comment by rainweb** [comment]
@metafloor Thanks for your help, it's ok~

**Comment by metafloor** [comment]
Closing this as solved.
