### ISSUE TITLE
Can this be used in a phonegap app?

### ISSUE THREAD

**Issue by hdramos** [metafloor/bwip-js#7]
Im trying to use this in a phonegap app but I am having trouble understanding how it works. I would appreciate an example. Thank you.

**Comment by metafloor** [comment]
I do not develop with phonegap but my understanding is that it supports JavaScript and the HTML canvas element.  It may be possible but I am concerned trying to host bwip-js within a phonegap client could be too heavy a hit.

You may be able to make it work depending on the types of bar codes needed.  Which bar code types do you need to display?

Alternately, can you display &lt;img>'s with a remote/internet URL?  If so, you may want to try bwip-js using either the public API hosted on rhcloud or your own node.js server.

Details on the public API are available here:  https://github.com/metafloor/bwip-js/wiki/bwip-js-Online-Barcode-Generator-API.  This is the same API you would use if you hosted bwip-js on a private node.js server.

Please let me know what you would like to try and hopefully I can provide further help.

**Comment by hdramos** [comment]
I think I got it. It just took me sometime to understand the demo. I did think about the online api but I need offline access. I'm going to try to do it locally and see how it performs. thanks.
