### ISSUE TITLE
Question: How to Test the Generated Barcode?

### ISSUE THREAD

**Issue by dannilics2015** [metafloor/bwip-js#74]
Hi, I am using the Master branch to render some Aztec Barcodes. How do I test/validate the barcodes besides seeing the barcodes are rendering? I saw in Wiki page saying that the Developer branch contains a test framework, but how to use it? Any suggestion would be greatly appreciated. Thanks a lot...

**Comment by metafloor** [comment]
There are two primary means of testing barcodes:  2d scanners and image processing software.  2d scanners can be expensive but they recognize the most types.  Image processing is inexpensive (can be free) but may have limits on what is recognized.

For starters, try:  https://zxing.org/w/decode.jspx

I have had good luck with that project and it is getting better at what bar codes it recognizes.

The other solution is to fork over some cash and get a 2d scanner.  They are getting cheaper by the year.  Used to be minimum US$700 to buy one.  Looking at amazon, I see several for under US$100.  For example:

https://www.amazon.com/dp/B0716PQYJP

Haven't used it but it says it does aztec, pdf417, qr-code, data matrix, so might be worth a try.
