### ISSUE TITLE
Question: Barcode Sizing

### ISSUE THREAD

**Issue by dannilics2015** [metafloor/bwip-js#75]
I notice if the data is a longer string then the 2D barcode tends to be bigger, is there a way to make it a default size? If so, will it affect the reading?

**Comment by metafloor** [comment]
Most of the 2d symbols supported by BWIPP allow you to specify size.  For example, aztec code uses `layers`.  Data matrix uses `version` and `format`.  Etc.  

Consult the BWIPP documentation for the symbol of interest.  And then pick a size that will match your largest data needs.  Smaller amounts of data can usually be padded using EC bytes to fit larger symbol sizes.
