### ISSUE TITLE
Integration into Adobe PhotoShop, Illustrator, InDesign

### ISSUE THREAD

**Issue by duckrabbitstudio** [metafloor/bwip-js#76]
Hi,
I'd like to implement this code into an Adobe Extendscript script into Adobe CC apps.

Adobe's apps can be scripted through Extendscript, an ECMAscript-based JS variation, so most of the BWIPJS code will work flawlessly. The actual "drawing" would of course be done in the scripts themselves, probably vector output, so as to scale more easily.

ANy pointers as to how to capture the "binary" data ("0" = gap width 1 unit; "111" = stroke 3 units thick)?

**Comment by metafloor** [comment]
I have often thought it would be useful to integrate bwip-js into jspdf or some other javascript-based pdf library.  It would be in essence a full circle cross-compiler- from PostScript to JavaScript back to PostScript.

What you are proposing is similar and the same hurdles likely exist.  It represents a lot of work.

The optimal way to do it would be to replace the PostScript graphics context, implemented in the file `bwipjs.js`.  That implements the PS graphic primitives like `moveto`, `rlineto`, etc. and you would only need to "record" the calls and convert them to the corresponding vector primitives you are working with.  Dealing with the fonts would be the hardest part.  You can either embed the fonts or you will need to pull in a javascript library that can render truetype fonts.  jspdf has the ability, I think.  There is also font.js and fontkit that may help.

The other way is as you suggest, and work with the generated BWIPP barcode data directly.  These are the dictionary structures that are passed to the three BWIPP renderers, `renlinear`, `renmatrix`, and `renmaximatrix`.  You will need to look at the original BWIPP source, the included `barcode.ps` file, to see how they are implemented.

bwip-js has modified the stock renderers so they look for a `bwipjs_dontdraw` flag and leave the rendering objects on the stack.  This is the `dontdraw` option that can be passed into the `bwipp` constructor.  Below is how the test framework invokes the cross-compiled code:

```javascript
var bwipp = require('./bwipp');
var bwipjs = require('./bwipjs');
var freetype = require('./freetype');

var bw = new bwipjs(freetype);
try {
    var stack = bwipp()(bw, "$sym", "$jstext", "$opts", true);    // true == dontdraw
} catch (e) { ... }
```

The above code is embedded in a bash heredoc, so those `$vars` get replaced with text.  The return value is the PostSript data stack, which will contain one or more rendering instances.  You then walk the stack (it's a JavaScript array) to extract each dictionary object:

``` javascript
for (var i = 0; i < stack.length; i++) {
    var dict = stack[i];
   ....
}
```

This is where you will need to start experimenting.  The format of the data in each `dict` object is based on the renderer that would draw it.  For example, here is what a dictionary object looks like for `renlinear` (in PostScript):

```postscript
    <<
    /ren //renlinear
    /sbs [sbs {48 sub} forall]
    /bhs [sbs length 1 add 2 idiv {height} repeat]
    /bbs [sbs length 1 add 2 idiv {0} repeat]
    /txt [ [text textxoffset textyoffset textfont textsize] ]
    /textxalign (center)
    /opt options
    >>
```
The `sbs`, `bhs`, and `bbs` are arrays that describe the linear bar code.   `sbs` are the bars and space widths.  `bhs` are the bar heights.  `bbs` are the baselines (starting points) for each bar.  All dimensions are in points. Think of UPC codes where the bars are different heights and all of this should begin to make sense.

The dict object for `renmatrix` is completely different....

As I said earlier, this will be a lot of work to implement.  And is the reason I haven't integrated bwip-js into jspdf - I simply don't have the time - even though it would be really useful.

**Comment by duckrabbitstudio** [comment]
Actually, the font part would become a whole lot easier, as the font handling can be done in the scripts depending upon the (graphical) programs. PS, AI an InD all have different ways of handling this, but it is manageable.

After studying the code, I start to grasp the way it all fits together, so I could base everything upon the basic input data (although configuring all options for all symbologies will take some work) and then create a way to replace `renlinear`, `renmatrix` and `renmaximatrix` by the graphical objects in aforementioned programs.

**Comment by duckrabbitstudio** [comment]
Incidentally… are there any "guides" or documentation as to the exact format the  `renlinear`, `renmatrix` and `renmaximatrix` dict objects are structured? I've been looking through the documentation, but would like to know how they're structured.

**Comment by metafloor** [comment]
There is no documentation for the dictionary objects passed to the renderers; the `barcode.ps` source code is the best documentation, albeit requiring learning PostScript's unique syntax and stack-based way of thinking.  While the renderers are not formally defined and may be subject to (infrequent) change - usually only by the addition of new keys - they have been relatively stable over a long period of time.  

If you have any questions about the purpose of different keys in the dict-objects, ask away.  I have bumbled through enough testing of the renderers that I can hopefully help you.

**Comment by duckrabbitstudio** [comment]
Okay… getting a grasp on the renderers now… I'll be able to rewrite them when I get the basic "encoding" to work, as it'll be a breakdown of the PS statements. As most of the elements (`sbs`, `bhs`, `bbs`,…) are reused again and again, it'll be relatively simple to write an InDesign translation of the graphical elements, and construct the barcode(s) in vectors (ie in contrast to pixels).

Also understand now how the `dontDraw` flag works, so debugging the encoding should be possible too.

Only puzzle now is the general structure of the BWIPP/BWIPJS code.

I'm not familiar with `$$`, `$0` or `$1` as a notation, and don't really understand where and how these functions (no arguments?) are "called". 

As Adobe ID,PS and AI aren't running on a remote server, I'm writing a script that does this…
```
<PSEUDOSCRIPT>
some values (text, encoding, options, etc…) are found in the document, and initialised as vars;
call the simplest form of the encoding module possible / do the encoding;
feed the resulting "dict" content to the appropriate ID-specific renderer (to write);
render the element, then if necessary scale back in ID (easy as it's a vector graphic)
do some mojo to merge overlapping/touching paths;
lock the barcode in place as a security measure;
</PSEUDOSCRIPT>
```
Is there an example of how the code is called "locally" on a given set of `vars`?

In first instance I'd need to rewrite only the renlinear renderer, so it stays manageable ;-)

**Comment by metafloor** [comment]
All of those $-vars are declared and commented in the *develop* branch's barcode-hdr.js.  The names are cryptic because they have been manually minified.  For example, `$$` is the BWIPJS graphics emulation object.  `$0` is the global dictionary.  `$1` is a local (scoped) dictionary.  `$k` is the operand stack.  `$j` is the stack "pointer".

Note that the bwip-js emulation optimizes away the run-time dictionary stack.  This was achievable because the BWIPP code is very well behaved.  The improvement in performance using this trick was simply amazing as it allowed the JavaScript optimizer to also come into play.

The more I think about this project, the more I think you will be better off replacing the bwip-js graphics context rather than the renderers.  That way, you are working solely in javascript and do not need to worry about the emulation.

Have another look at `bwipjs.js`, specifically functions like `stroke`, `pathbox`, `charpath`, and `stringwidth`.  These are the postscript graphics primitives used by `renlinear`.  You will need a copy of the "red book", the postscript reference manual, to understand their behavior.  If you don't already have it, here is the link:

https://www.adobe.com/products/postscript/pdfs/PLRM.pdf

By replacing the implementation of those functions, you can use the cross-compiled code "as is" and will likely be able to run bwip-js using the standard interfaces.

**Comment by metafloor** [comment]
Forgot one very important graphics primitive in the list above, `show`, which does the font/character drawing.

**Comment by duckrabbitstudio** [comment]
Still plowing through the online discussions/documentation about Factory method patterns and callbacks…

I'm desperately trying to feed the input into the `BWIPP` function, but these lines still leave me baffled:
```
    // The BWIPP symbol is a factory object.  When called, it returns this
    // function, which is a re-usable postscript emulation for BWIPP.
    return function(bwipjs, encoder, text, opts, dontdraw) { […] }
```
1. How and where should I call this function? 
2. As it is a nameless function… how do I call it? 
3. It is created as a result of `function BWIPP() {[…]} `, but how do I get it to work?
4. I'm OK with feeding it the `encoder`, `text`, `opts` variables, and get the `dontdraw` flag, but what does the `bwipjs` stand for? What variable should be fed into this? 

…Or am I not getting this?

I'm sorry to ask this much guidance, but this is the single most ambitious project I've tackled this far, and it would be truly useful to me and other designers.

Thx in advance!

**Comment by metafloor** [comment]
You are looking at the low level code and should be using the higher level interfaces.  Take a look at demo.html, around line # 242:

    // Render the bar code
    try {
        // Create a new BWIPP instance for each
        BWIPP()(bw, elt.sym, text, opts);
    } catch (e) {
        // Watch for BWIPP generated raiseerror's.
        ...
    }

As discussed previously, if you add a fifth `true` parameter to the call above, the rendering data will be returned to you as an array (whatever is left on the postscript data stack).  You need to modify the above to capture it:

    let stack = BWIPP()(bw, elt.sym, text, opts, true);

`stack` will contain the dictionary object(s) passed to the renders.

No not use the BWIPP `dontdraw` option as it doesn't work with bar code types that have *composite* in their names.  The fifth parameter, `bwipjs_dontdraw` in the low-level code, causes the renders to return without consuming the stack contents.

**Comment by duckrabbitstudio** [comment]
Back from well deserved holiday… still stumped…

Can't seem to find any decent documentation on how to use this "Factory Method"… at least not in an offline setting. Many examples goin' all over the place in "online" "server" settings…

Fact is: to make this work, I need to "#include" into the "ExtendScript" (Adobe's name for their scripting environment) all the script element I'll be needing.

I then need to disable anything to do with rendering in PS, loading/using fonts,… as I won't be needing them (yet).

I wrote a short interface to insert necessary vars, which are…
```
var myEnc = "the Encoding, eg 'gs1-128'"
var myText = "the text to be encoded, eg '96(05)123400'"
var myOpts = "eg 'includetext"
```
If I take the "bwipp.js", I believe I got "everything" necessary… right?

If I try the `var stack = BWIPP()(bw, elt.sym, text, opts, true);` option, however, everything stays "undefined"…

Any pointers to truly understand what's really going on? Most tutorials and examples are poorly constructed, as if the tutor himself doesn't really get it, and just copied a `foo bar` example to illustrate something they never constructed themselves…

I'm not a professional coder, so maybe I'm missing something obvious… My main talents are in making the Adobe Apps' DOM's do special stuff.

I'm quite confident that if I could just get the different encoders to work (if necessary in a shell environment), I could hash up a configurable, extendable, batch-production-ready BarCode script, and get it to work in any Adobe Print App (ie PhotoShop, Illustrator, InDesign,… maybe even as an Acrobat script)

**Comment by metafloor** [comment]
Don't get hung up terminology.  A factory method is simply a function that creates and returns something, usually an object, but not necessarily.  In the case of `BWIPP()`, it is returning a function with an outer scope that captures the cross-compiled code.  That function gives you an encapsulated run-time for the PostScript emulation.

Have you done some debugging to understand what is happening?  I like to run bwip-js in the browser (using `demo.html` - not bundled with webpack or other tech) when I need to debug something.  It allows stepping through the code, placing breakpoints, etc.

For example, in `bwipp.js`, near the bottom of the file is the code:

```javascript
        // Don't draw? (See file runtest)
        $0.bwipjs_dontdraw = dontdraw || false;

        // Invoke the encoder
        $$ = bwipjs;
        $k = [text, opts];
        $j = 2;
        $0[encoder]();

        // Return what is left on the stack.  This branch should only be taken
        // when running tests with the dontdraw option.
        if ($j) {
            return $k.splice(0, $j);
        }
```

Have you verified that `$0.bwipjs_dontdraw` is being set and the return of the stack `return $k.splice(0, $j);` is happening?

**Comment by duckrabbitstudio** [comment]
This is the structure I'm working on… 
Note: this runs in the Adobe Extendscript app, in the Adobe InDesign Engine (whose DOM contains everything basic from JS + the InDesign DOM)

```
// TODO: Set variables by reading the ScriptLabels of some text frames, 
// or through an interface in Adobe Apps, 
// that let you enter desired values or choose from popups …

// … here for testing purposes replaced by setting of some vars: 
    var bw = new BWIPP();
    var encoding = "gs1-128"
    var text = "(01)95012345678903(3103)000123"
    var opts = "includetext"

// render "stack" to be analysed, not drawing the barcode.
try {
    // Create a new BWIPP instance for each
    var stack = BWIPP()(bw, encoding, text, opts, true); /*PROBLEM AREA*/
    } 
catch (e) {
    // Watch for BWIPP generated raiseerror's.    ...
    }
// TODO: convert "stack" into useful data

// TODO: convert this data in InDesign/PhotoShop/Illustrator commands, to "render" the barcode

// TODO: If Necessary: scale vectors to needed

// Followed by the entire BWIPP() {…} function and the code that is 
// injected below the cross-compiled code.

// The renderers (renlinear etc) are "disabled" so I can replace them if needed 
// with the right Adobe-compatible "vector" "renderers" when needed. 
```
Where I noted /*PROBLEM AREA*/ I believe I'm calling the code in the wrong way… I'm not familiar with calling functions "this way", so I can't figure out what's going on…

Debugging doesn't help… I get no errors but my Stack remains "undefined" and the code below the crosscompiled code doesn't seem to impact anything…

**Comment by metafloor** [comment]
First line is wrong.  You need to create a `BWIPJS` object (and pass in a font-manager object and monochrome flag).  Here is the node version of your code, using the most recent release, which has a new font library:

```javascript
const BWIPJS  = require('./bwipjs');
const BWIPP   = require('./bwipp');
const fontlib = require('./node-fonts');

var bw = new BWIPJS(fontlib, false);
var encoding = "gs1-128"
var text = "(01)95012345678903(3103)000123"
var opts = "includetext"

// render "stack" to be analysed, not drawing the barcode.
try {
    // Create a new BWIPP instance for each
    var stack = BWIPP()(bw, encoding, text, opts, true); /*PROBLEM AREA*/
    console.log(stack);
} catch (e) {
    console.log(e);
}
```

The output is:

    [{"opt":{"includetext":true,"height":0.5,"dontdraw":true,"parsefnc":true},
    "textxalign":"center",
    "txt":[["(01)95012345678903(3103)000123",0,-8.5,"Courier",10]],
    "bbs":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...snip...],
    "bhs":[0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...snip...],
    "sbs":[2,1,1,2,3,2,4,1,1,1,3,1,2,2,2,1,2,2,1,1,4,1,1,3,2,2,2,1,2,2,3,1,2,1,3,1,1,1,...snip...]}]

**Comment by metafloor** [comment]
Thinking more about your example, you actually don't need a BWIPJS object since you aren't using the graphics layer.  I tested the code as you originally had it and it worked just fine.   For how you are using bwip-js, you can pass `{}` in place of the `bw` parameter.  I tested that as well and it worked.

So not actually sure why you are having issues with the code...

**Comment by duckrabbitstudio** [comment]
I'm having issues mainly because I need to get this working in the Adobe Extrendscript DOM.
Extendscript as such doesn't do "font management", so I try to "ignore" this part for now.

Actually all I need is the true "calculating" part of the code. I'll try again with `var bw = {}` and try to go from there.

The output you posted is exactly what I need :-) so I'm quite confident I should be able to get this to work.

On the other hand, it will be necessary to consolidate everything in one script, or use the extendscript-compatible `#include` notation to add multiple files.

But `#include` is known for having some other issues (concerning scopes and whatnot), so maybe getting this to work in one consolidated script is my main focus for now :-)

Already thanks for the help.

**Comment by duckrabbitstudio** [comment]
Seems to work, except for `let` and `Uint8Array`, which (as I found out) has to do with the fact that Adobe's ExtendScript language/IDE is based upon ECMAscript 3, and the web is currently all about ECMAscript 6… 'let' should work with `var`, unless I overlook something (as I'm bound to do ;-) )

I'm looking into adding a `Uint8Array prototype` manually, so I can circumvent this. :-)

**Comment by metafloor** [comment]
If you are using ES3 (late 1990s!) you may have issues with using bwip-js.  The lack of Uint8Array is huge - it is tightly coupled to PostScript emulated strings.  Fortunately, I think it will be possible to use a polyfill.  Here is one that looks encouraging:  https://github.com/substack/typedarray

BTW, where did you find a `let`?  Those aren't supposed to be in the code.  I work in modern JS but try to keep bwip-js using older constructs but every now and then force of habit kicks in....

**Comment by duckrabbitstudio** [comment]
Oh! I meant a `const`… encountered some `let`'s in code examples on blogs of other coders I was trying to learn from ;-P

tried shims, shams and polyfills (am learning a lot, btw) but to no avail…

I'll have to debug the code and check if `Uint8Array` is actually necessary… If it's only used to check for arrays, a simple `Array` will do just fine…

Otherwise it might complicate stuff…

**Comment by metafloor** [comment]
If you use Arrays in place of Uint8Arrays, you must subclass them so that postscript strings are type distinct from postscript arrays (which are plain Arrays).  Download the *develop* branch of bwip-js and look at the file `barcode-hdr.js` - that is where the postscript operators are emulated.  For example, look at the `get` operator (`function $get`) and you will see lots of branches based on operand types.  PostScript operators a highly type overloaded.

**Comment by duckrabbitstudio** [comment]
I'm not sure I'd know how to do that… still a newbie in the JS prototyping/subclassing world… FabianMoronZirfas suggested doing all through CEP panels… not sure if that would work… Terminal etc… makes for a loss in ease of use I'm not prepared to handle…

Thinking of adapting [OkapiBarcode](https://github.com/woo-j/OkapiBarcode) from Java to JavaScript… may be a lot of work, but the Java ends up delivering nice arrays of binary data I can feed into my custom Adobe renderers :-)

**Comment by metafloor** [comment]
From the looks of it, CEP is the way to go.  It brings modern JavaScript to ancient ActionScript, albeit via proxy interface.  You can run bwip-js in a panel and get the results back, including the arrays of binary data you seem so intent on.

IMO, learning CEP will be orders of magnitude easier than manually converting a java library to actionscript.  Most Java code is highly class structured, which maps well to JavaScript, but requires a solid understanding of JS's prototypal subclassing.

**Comment by metafloor** [comment]
Closing this as no longer active.
