### ISSUE TITLE
Barcode not visible on canvas

### ISSUE THREAD

**Issue by vbnvicky** [metafloor/bwip-js#77]
I have added bwip-js library into a designer [developed using HTML5 and jQuery] where i need to place GS1 DataMatrix in it. User can place the GS1 DataMatrix from toolbox to Canvas.
But unfortunately, placed GS1 DataMatrix not visible on canvas. I have other elements in toolbox it works well. Can you please suggest.

**Comment by metafloor** [comment]
Since you didn't post any code, I assume this is not a very important issue to you...

But my guess is you didn't customize the Bitmap `render()` method to draw to the canvas.
