### ISSUE TITLE
Browserify

### ISSUE THREAD

**Issue by tnyeanderson** [metafloor/bwip-js#8]
For some reason browserify throws the following error when it tries to access the library:

Uncaught Error: Cannot find module '/node_modules/bwip-js/node-zlibPNG'

Looks like it might be trying to load it from the root directory? Perhaps switching to relative paths would be better? This could also simply be a problem with browserify. I really appreciate the work you put into this library and I want to be able to use it in browser if possible! Thanks!

**Comment by tnyeanderson** [comment]
Making the path relative ('./node-zlibPNG') instead of using __dirname seems to fix that issue for me (don't know how this affects the node side of things, but it shouldn't). May send in a pull request later if I can figure out how to get fs to work browser side.

**Comment by metafloor** [comment]
The code already works in-browser (see the demo from the links on the 
project page).

What are you trying to do?

**Comment by tnyeanderson** [comment]
Sorry that whole thing was written in a substance-fueled coding session. I understand it made no sense. Sorry about that, I was going about the issue in the stupidest way possible. Closing the issue now.
