### ISSUE TITLE
Can this API can handle lackhs of requests per day for generating barcodes 

### ISSUE THREAD

**Issue by Chennuri-SaiCharan-Reddy** [metafloor/bwip-js#80]
Can this API can generate lakhs of barcodes per day.I am of the opinion that it can generate but for the benefit of doubt I am asking,Can you clarify my doubt

**Comment by metafloor** [comment]
Are you asking about the number of bar codes per day?  If so, you need to quantify what you consider "lots".  And are you referring to the node.js server functionality?

Linear bar codes generate in under 100ms, 50ms typical.

2D bar codes depend on the size of the data to be encoded and its complexity.  But typical responses are between 100ms - 500ms.

If you need massive numbers of bar codes, a node cluster is recommended with one worker process per CPU.

**Comment by Chennuri-SaiCharan-Reddy** [comment]
I am thinking of implementing it in my app and I asked to know whether when my user base grows I need to setup my own server or the one provided by you would be the deal

**Comment by metafloor** [comment]
The public API is constrained to a single CPU (the free version of the rhcloud services) and is hosted on the US east coast.  You will need to do some suitability testing to verify whether that will work with your needs.
