### ISSUE TITLE
bwip-js/node-bitmap.js causes uncaughtException: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by flemming-fridthjof** [metafloor/bwip-js#81]
Newly added file bwip-js/node-bitmap.js causes error "uncaughtException: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode" originating from bwip-js/node-bwipjs.js line 9.
Issue isolated to NodeJS version 4.

**Comment by metafloor** [comment]
I don't use such an old version of node.  Does adding `"use strict"` at the top of the file fix the issue?

**Comment by flemming-fridthjof** [comment]
Yes, it did. By adding it to the following files (which uses const and let):

bwip-js/bwipp.js
bwip-js/bwipp-min.js
bwip-js/node-bitmap.js
bwip-js/server.js

**Comment by m-burst** [comment]
@metafloor I can confirm it is a regression introduced since v1.3.3. v1.3.3 works fine on node v4.

**Comment by metafloor** [comment]
Decided just to replace `const`/`let` with `var` for now.  I will install node4 and set up a test framework to use it at a later date.  New version 1.4.2.
