### ISSUE TITLE
ReferenceError: monocolor is not defined

### ISSUE THREAD

**Issue by kyledecot** [metafloor/bwip-js#83]
I'm attempting to use your recently released `1.5.1` release w/ the basic React snippet provided in the `README.md` however when I load the react app up in my browser I'm getting the following:

<img width="1240" alt="screen shot 2017-09-01 at 9 07 51 pm" src="https://user-images.githubusercontent.com/192464/29991702-e6c3ac54-8f59-11e7-89fd-6a668e4e5b50.png">

**Comment by metafloor** [comment]
Just caught me before I left for the day.  Version 1.5.2 is out that fixes this.

**Comment by kyledecot** [comment]
Thanks for getting this out quickly and for adding React support!
