### ISSUE TITLE
1.5 is incompatible to previous versions

### ISSUE THREAD

**Issue by apricote** [metafloor/bwip-js#85]
After doing an `npm update` and upgrading the version from `bwip-js@1.4.2` to `bwip-js@1.5.4` the server crashed at the beginning with following Exception:

```
/home/apricote/api/node_modules/bwip-js/node-bwipjs.js:193
	freetype.FS_createDataFile('/', fontname, fontfile, true, false);
	        ^

TypeError: Cannot read property 'FS_createDataFile' of undefined
    at Function.module.exports.loadFont (/home/apricote/api/node_modules/bwip-js/node-bwipjs.js:193:10)
```

This update seems to include a breaking change (exclusion of freetype.js) that is generating errors for users of the previous Interface. According to [Semver 2.0 §8](http://semver.org/#spec-item-8) an incompatible API change MUST be released as a new major version.

**Comment by metafloor** [comment]
Probably should have bumped the major version but at this point, not going to.

Are you using a custom font?

**Comment by apricote** [comment]
Just wanted to notify you and other users of this possible source for errors.

Yes, we are using custom fonts, we will stay with `1.4.2` for now, until we have time and the need to upgrade.

**Comment by metafloor** [comment]
Fixed a bit of code and updated the project's README to show freetype usage with node (only available from node).  From the README:

```
// To use the freetype library for font rendering, you must enable it via useFreetype(),
// then load your custom font(s).  This shows how to load the Inconsolata font, supplied
// with the bwip-js distribution.  The path to your fonts will likely be different.
bwipjs.useFreetype();
bwipjs.loadFont('Inconsolata', 108,
      require('fs').readFileSync(__dirname + '/fonts/Inconsolata.otf', 'binary'));
```
