### ISSUE TITLE
Buffer.alloc is not a function

### ISSUE THREAD

**Issue by bhargavmullakuru** [metafloor/bwip-js#86]
Hi im getting some error..can you help me with that

**Comment by metafloor** [comment]
`Buffer.alloc()` is node v5.10.  Hard to break the habit of using modern JavaScript.  Changed to using `new Buffer()` in version 1.5.5.

**Comment by bhargavmullakuru** [comment]
I am using These versions:
node - 5.8.0
npm - 4.3.0

**Comment by metafloor** [comment]
Have you verified version 1.5.5 is working for you?

**Comment by bhargavmullakuru** [comment]
@metafloor ..thank you ..i am getting PNG buffer now ..Working fine..thanks a lot 👍

**Comment by bhargavmullakuru** [comment]
@metafloor ..i am getting buffer...by using .toString('base64')..i am getting empty base64 image

**Comment by metafloor** [comment]
Are you checking the error parameter?  And the buffer size?  Please post some code.

**Comment by bhargavmullakuru** [comment]
@metafloor ..here is the piece of code ... i am not getting error ...
bwipjs.toBuffer({
        bcid:        'code128',       // Barcode type
        text:        result.Invoice.InvoiceNumber,    // Text to encode -i am passing number here
        scale:       3,               // 3x scaling factor
        height:      10,              // Bar height, in millimeters
        includetext: true,            // Show human-readable text
        textxalign:  'center',        // Always good to set this
    }, function (err, png) {
        if (err) {
            console.log("err",err);            
        } else {
            console.log("png",png);
            var base64String = png.toString('base64');
            console.log("base64String", base64String);
        }
    });

**Comment by metafloor** [comment]
You already stated the problem in your comment.  `text` needs to be a string, not a number.

**Comment by bhargavmullakuru** [comment]
Oh..it works only for the Text...not Numbers...actually my requirement is number not text

**Comment by metafloor** [comment]
Then convert the number to text:  `''+result.Invoice.InvoiceNumber`

**Comment by bhargavmullakuru** [comment]
Thank you @metafloor for helping..I will try and let you know

**Comment by bhargavmullakuru** [comment]
@metafloor ...i have passed text as you said...but i am getting empty image only
bwipjs.toBuffer({
            bcid: 'code128',       // Barcode type
            text: "hello..!" ,// Text to encode
            scale: 3,               // 3x scaling factor
            height: 10,              // Bar height, in millimeters
            includetext: true,            // Show human-readable text
            textxalign: 'center',        // Always good to set this
        }, function (err, png) {
            if (err) {
                console.log("err", err);
                // Decide how to handle the error
                // `err` may be a string or Error object
            } else {
                console.log("png", png);
                var base64String = png.toString('base64');
                console.log("base64String", base64String);
}
});

**Comment by metafloor** [comment]
Don't know what to tell you.  Your code works.  Here it is with node v4:

```
$ npm install bwip-js
C:\tmp
`-- bwip-js@1.5.6

$ node4
> process.version
'v4.0.0'
> var bwipjs = require('bwip-js')
> bwipjs.toBuffer({
    bcid: 'code128', // Barcode type
    text: "hello..!" ,// Text to encode
    scale: 3, // 3x scaling factor
    height: 10, // Bar height, in millimeters
    includetext: true, // Show human-readable text
    textxalign: 'center', // Always good to set this
    }, function (err, png) {
    if (err) {
       console.log("err", err);
       // Decide how to handle the error
       // err may be a string or Error object
    } else {
       console.log("png", png);
       var base64String = png.toString('base64');
       console.log("base64String", base64String);
    }
    });
png <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 01 71 00 00 00 6f 08 03 00 00 00 2d f2 00 c9 00 00 00 1e 74 45 58 74 53 6f 66 74 77 61 72 65 00 ... >
base64String iVBORw0KGgoAAAANSUhEUgAAA ...snip... AAAAABJRU5ErkJggg==
```

Similar results with more modern nodes.

**Comment by bhargavmullakuru** [comment]
@metafloor ...after Upgrading **bwip-js** to latest 1.5.6 ...it is generating fine..thank you for your patience and helping me... 🌝
