### ISSUE TITLE
RedHat OpenShift hosted API discontinued

### ISSUE THREAD

**Issue by metafloor** [metafloor/bwip-js#89]
I was just informed that RedHat is discontinuing their free service that is used to host the bwip-js public API.  The existing solution provided up to three VPS with 24/7 availability.  In place of this, they are offering a "starter" platform that offers a single VPS that, according to https://www.openshift.com/pricing/index.html, must sleep 18 hours in any 72 hour period.  That is hardly comparable and does not serve a global user base.

Because of this, the public API will likely shutdown on October 1.  Sorry for the short notice.  This caught me up short as well. 

I have configured the API on their new platform.  It can be reached at:

http://api-bwip-js.7e14.starter-us-west-2.openshiftapps.com/

Same usage as before, but be aware that it may be sporadically unavailable.

If anyone knows of a free VPS platform with 24/7 availability that can run node.js version 5+, please let me know.  I will happily migrate the service.

**Comment by metafloor** [comment]
The public API is now hosted on an AWS EC2 instance:

http://ec2-13-58-67-69.us-east-2.compute.amazonaws.com/

This will be its permanent home after October 1, 2017 so long as costs don't get out of hand.

**Comment by metafloor** [comment]
Added a CNAME record to my hosting provider's DNS database so the API can be moved transparently in the future.  Please use:

http://bwipjs-api.metafloor.com

**Comment by krzaczek** [comment]
@metafloor is there a change for HTTPS support ?

**Comment by metafloor** [comment]
No plans at the present but will look into getting a certificate through Let's Encrypt.  I will keep this issue open for status updates.

**Comment by auctifera-josed** [comment]
Hi @metafloor not sure if you are aware but you can easily add HTTPS support using [AWS Certificate Manager](https://aws.amazon.com/certificate-manager/), I'm assuming you own metafloor.com, you'll just need to create a Certificate in AWS and accept the email AWS sends you to validate you actually own the domain, and then just add the certificate to your EC2 instance. (If you are using Elastic Beanstalk to host your app is just as easy as selecting the certificate from the AWS Console).

**Comment by metafloor** [comment]
Thanks for the heads up but ACM certs do not work with EC2, at least according to the ACM FAQ.  Would have been a nice easy solution if they did...

**Comment by auctifera-josed** [comment]
Yeah, you'll need a load balancer between your EC2 instance and your ACM certificate which adds some cost.

**Comment by metafloor** [comment]
https service is now available for the public api, as of 31-Mar-2018.
