### ISSUE TITLE
Struggling with integration in Angular 4 bwipjs-fonts not loaded

### ISSUE THREAD

**Issue by itc123** [metafloor/bwip-js#91]
I am trying to use bwip-js with angular 4, 

```typescript
import { Injectable } from '@angular/core';
import bwipjs from 'bwip-js/browser-bwipjs';

@Injectable()
export class BwipjsService {

  example(): void {
    const canvas = document.createElement( 'canvas' );
    bwipjs( canvas,
      {
        bcid: 'interleaved2of5',
        text: '0123456789',
        includetext: true // <----- doesn't work because fonts aren't loaded
      }, function ( err, cvs ) {
        if (err) {
          console.log( err );
        } else {
          console.log( canvas.toDataURL( 'image/png' ) );
        }
      } );

}
```
I always get the 
`http://localhost:4200/undefined/bwipjs-fonts/fnt0-desc.js 404 (Not Found)`

Any ideas how to fix that ?

**Comment by metafloor** [comment]
You hit the one piece of the implementation puzzle that I am not happy with.  If you review the project's README concerning using with React, there are two items that you must do after installing bwip-js:

- Link the fonts directory so that it is reachable as a publicly visible URL path.
- Ensure the global variable `process.env.PUBLIC_URL` is set to the public path (which for React is `/public`).

I am not sure how Angular accomplishes this.  If you know, please reply and I will update the documentation with an Angular section.

**Comment by champunes** [comment]
The problem with the `process.env.PUBLIC_URL` variable is that it is not setted if you don't use create-react-app. I don't know why is mandatory to use `process.env.PUBLIC_URL` when it's possible to use relative paths. If you try to get `bwipjs-fonts/fnt0-desc.js`, it will work if you set your public folder in your web-server framework. I'm using express v4.x and with
`xhr.open('GET', process.env.PUBLIC_URL || '' + '/bwipjs-fonts/fnt' + id + '-desc.js', true);` works.

Would it be possible to eliminate the obligation to set `process.env.PUBLIC_URL`?

**Comment by metafloor** [comment]
I will be releasing a minor update this week and will build up the URLs as:

```
(typeof process == 'object' && typeof process.env == 'object' && process.env.PUBLIC_URL || '') +
        '/bwipjs-fonts/fnt' + id + '-desc.js'
```

**Comment by fusiondesign** [comment]
Is this still planned?

**Comment by biowheel** [comment]
I keep getting the font not found error. I am a newbie so I tried pasting the fonts directory all over. I need one help, how can I output the location to which bwip is searching like @itc123  did?

**Comment by metafloor** [comment]
I am not familiar with angular so can only provide some general help but I assume you are running against a node-based server (via `npm run` or something similar).  

Can you see the font file requests on the server?  Specifically what URL is being requested?

**Comment by biowheel** [comment]
Hi, when I checked I got this: http://localhost:4200/assets/bwipjs-fonts/fnt1-desc.js but in my assets/bwipjs-fonts folder I only find fnt0-desc.js. Probably I should re-install the npm?

**Comment by biowheel** [comment]
Well thats what I did and it works. I used bwip-angular2, dont know what went wrong. Thanks btw.

**Comment by metafloor** [comment]
You need to copy all of `node_modules/bwip-js/fonts/*` to the `assets/bwipjs-fonts` directory.

**Comment by biowheel** [comment]
And I dont see fnt3-desc.js in the fonts folder.. as a result some of the barcodes are not being rendered. However, QR codes come out well. Is there something I am missing?

**Comment by metafloor** [comment]
That's normal.  The code keeps requesting font descriptors until it hits a not-found condition.

**Comment by metafloor** [comment]
This issue should go away in the 2.0 release.  Fonts are embedded and no longer loaded async.  Browser code is fully synchronous when drawing to canvas.
