### ISSUE TITLE
Integration with browserifier library on nodejs project

### ISSUE THREAD

**Issue by real050280** [metafloor/bwip-js#94]
Hello,

I recently tried this library and is very awesome so far until I browserified it for AWS microservice via serverless framework. I always received the error below and I don't why until recently...

> Unable to import module 'test/index': Error
> at Function.Module._resolveFilename (module.js:469:15)
> at Function.Module._load (module.js:417:25)
> ...

Current configuration is below:

> serverless.yml

```
package:
  individually: true

plugins:
  - serverless-plugin-browserifier
package.json
...
"dependencies": {
    "aws-sdk": "2.104.0",
    "bardcode": "1.0.0",
    "bwip-js": "1.5.6",
    "pdfkit": "0.8.3"
  },
"devDependencies": {
    "chai": "4.1.1",
    "mocha": "3.5.0",
    "nock": "9.0.14",
    "serverless": "1.20.2",
    "serverless-plugin-browserifier": "1.0.5"
  }
```

Code snippet.
```
'use strict';

const bardcode = require('bardcode');
const fs = require('fs');
const bwipjs = require('bwip-js');
```

HOWEVER, I discovered that if I changed the following lines in node-bwipjs.js, my project runs smoothly even browserified:

> node-bwipjs.js

```
var url	= require('url'),
	bwipp = require(__dirname + '/bwipp'),
	bwipjs = require(__dirname + '/bwipjs'),
	Bitmap = require(__dirname + '/node-bitmap'),
	fixedfont = require(__dirname + '/node-fonts')	// freetype alternative, default
	;
```

to

```
var url	= require('url'),
	bwipp = require('./bwipp'),
	bwipjs = require('./bwipjs'),
	Bitmap = require('./node-bitmap'),
	fixedfont = require('./node-fonts')	// freetype alternative, default
	;
```

Please tell me guys if what I did is the correct way to do it.

Until then, this library has been AWESOME so far!

**Comment by metafloor** [comment]
There was another issue raised that was having similar trouble.  I am preparing a new release and will make the paths relative.  Will respond again on this issue when the release is available.
