### ISSUE TITLE
Adding Function code

### ISSUE THREAD

**Issue by real050280** [metafloor/bwip-js#95]
Hello,

How do you guys add Function code (ie FNC1) ?

My scanner always fails because of a missing function code FNC1 after the STARTC character.

Sample options:
```
bwipjs.toBuffer({
        bcid: 'code128',
        text: '(00)12345678901234567890',
        height: 27,
        inkspread: -0.245
      }
```

Actual results from the scanner:
STARTC0012345678901234567890

Expected results:
STARTCFNC10012345678901234567890

How to resolve this ?

Thank you very much.

**Comment by terryburton** [comment]
In general for `code128` (and other symbologies that accept data in GS1 Application Identifier standard format) you can use the `parsefnc` option which allows you to specify an FNC1 at any point in the data via `^FNC1`, e.g. `^FNC100123456789012345675`. (Note that parentheses are not included in the raw Code 128 data.)

It is however more convenient to use the `gs1-128` encoder instead as this allows you to simply specify the input data in human-readable format, e.g. `(00)123456789012345675`. The required FNC1 characters will be inserted automatically including in their role as field separators.

Better still, for GS1 data containing a single (00) Application Identifier you could use the most-specific `sscc18` encoder with the same input with the benefit that it will actually verify that the 18-digit SSCC-18 is valid using the integrated check digit. However I note that your input data isn't 18 digits and is therefore not valid.

**Comment by real050280** [comment]
Hello Terryburton,

Thank you for the quick reply.
I will try that 'parsefnc' option and will get back to you after the output confirmation.

By the way, you mentioned about GS1-128 encoder, but that's the exact implementation I was using before but still didn't passed the verification process due to missing FNC1 function code.

Also, how should I use the 'sscc18' encoder ? My input data is actually 18-digits (including the check digit). My specification mentioned about using 'SSCC' barcodes but not sure if this is the same with 'sscc18' you mentioned above.

Best regards.

**Comment by metafloor** [comment]
@real050280:  To use the gs1-128 encoder, change your code to:

```
bwipjs.toBuffer({
        bcid: 'gs1-128',
        text: '(00)12345678901234567890',
        height: 27,
        inkspread: -0.245
      }
```

Similar change to use the `sscc18` encoder.

**Comment by real050280** [comment]
hello metafloor,

I want to use 'code-128' instead of 'gs1-128'. I'm not sure if that would make much difference in the output though.
Is there a way to insert FNC1 in the output above aside from inserting '^FNC1' character in the raw data manually?

**Comment by metafloor** [comment]
That is one of the primary points of the gs1-128 encoder: to insert the FNC1's automatically for you, based on the parenthesized application ids (numbers).  The code128 encoder is lower-level and requires you to specify the FNC1's explicitly.

**Comment by real050280** [comment]
That makes sense. Thanks a lot.
