### ISSUE TITLE
Online Barcode API - This request has been blocked; the content must be served over HTTPS- error

### ISSUE THREAD

**Issue by Anshdeep** [metafloor/bwip-js#96]
Hello,

Using Online Barcode API for generating the barcode from XMLHttpRequest in angular 2 but getting below error message.

Mixed Content: The page at 'https://test-spiderexe.herokuapp.com/test' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://bwipjs-api.metafloor.com/?bcid=code128&text=123456'. This request has been blocked; the content must be served over HTTPS.

Do you have any idea to resolve the issue?

**Comment by metafloor** [comment]
https service is now available for the public api, as of 31-Mar-2018.
