### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by Anshdeep** [metafloor/bwip-js#97]
Hello,

Using Online Barcode API for generating the barcode from XMLHttpRequest in angular 2 but getting below error message.

Failed to load http://bwipjs-api.metafloor.com/?bcid=code128&text=123456: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://test-spiderexe.herokuapp.com' is therefore not allowed access.

But, I have already included headers.
let req = new XMLHttpRequest();
req.open('get', url, true);
req.responseType = "blob";
req.setRequestHeader("Access-Control-Allow-Headers", "Cache-Control, Pragma, Origin,             Authorization, Content-Type, X-Requested-With");
req.setRequestHeader("Access-Control-Allow-Methods", "GET, PUT, POST");
req.setRequestHeader("Access-Control-Allow-Origin", "*");

Do you have any idea to resolve the issue?

**Comment by metafloor** [comment]
The access-control-allow-origin must be part of the server's response headers, not the client's request headers.  Is there a reason you are using XHR and not an <img> tag or via CSS background-image url?  Both of those methods avoid the CORS restrictions that are baked into modern browsers.

**Comment by metafloor** [comment]
The public API has been updated to allow CORS.  `Access-Control-Allow-Origin: *` is now in the response headers.

**Comment by gastonelhordoy** [comment]
Thanks a lot @metafloor !
