### ISSUE TITLE
How to force 128 C generation?

### ISSUE THREAD

**Issue by swftvsn** [metafloor/bwip-js#99]
I need to make sure that all generated bar codes are 128 C compliant, or else an error should be thrown. How can I for 128C? 

Currentyl I'm using 
```ts
bwipjs.toBuffer({
        bcid:        'code128',                                         // Barcode type
        text:        thecode,                                           // Text to encode
        scale:       3,                                                 // 3x scaling factor
        height:      11,                                                // Bar height, in millimeters
        includetext: false,                                             // Show human-readable text
        textxalign:  'center'                                           // Always good to set this
      },....
```
to generate the barcode and ONLY feeding it numbers. Am I safe to assume that the generated barcodes are of type C?

**Comment by metafloor** [comment]
To ensure only C-codeset, the input must meet two requirements:

 - Must be comprised of pairs of digits.
 - Any FNC1 characters must not "split" a pair of digits.

RegExp-wise, it must match:
```
    /^(\d\d|\^FNC1)+$/
```

And if `^FNC1` will be in the input, you need to add the `parsefnc: true` option.
